### ISSUE TITLE
Invalid syntax for version: when build with bnd gradle plugin 3.0

### ISSUE THREAD

**Issue by m3git** [bndtools/bnd#1069]
When using bnd gradle plugin 3.0 to build, I cannot get the SNAPSHOT qualifier to be appended to the jar. Looking at the Version.java file, it shows that I am forced to use this format to get the SNAPSHOT qualifer "major.minor.micro.SNAPSHOT" instead of "major.minor-SNAPSHOT" or "major.minor.micro-SNAPSHOT"

**Comment by bjhargrave** [comment]
Versions should conform to the OSGi version syntax which requires micro to be specified if you want to use a qualifier. Also no hyphen.

The output file name of the jar can be controlled with the [`-outputmask`](http://bnd.bndtools.org/instructions/outputmask.html) instruction in your bnd file. You could set it to:

```
-outputmask:            ${@bsn}-${version;==;${@version}}-SNAPSHOT.jar
```

So the file name would be the bundle symbolic name followed by major.minor (==) followed by -SNAPSHOT.jar

**Comment by m3git** [comment]
It looks like I was incorrect when I said it was the name of the jar. The exception is rather due to the conversion from version to bundle-version as indicated in the stackctrace. Much appreciated if there is alternative.

Caused by: java.lang.IllegalArgumentException: Invalid syntax for version: 1.2-SNAPSHOT
        at aQute.bnd.version.Version.<init>(Version.java:47)
        at aQute.bnd.version.Version.parseVersion(Version.java:161)
        at aQute.bnd.version.Version$parseVersion.call(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure2.doCall(BundleTaskConvention.groovy:163)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:492)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
        at org.gradle.util.Configurable$configure.call(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention.buildBundle(BundleTaskConvention.groovy:99)
        at aQute.bnd.gradle.BundleTaskConvention.this$2$buildBundle(BundleTaskConvention.groovy)
        at aQute.bnd.gradle.BundleTaskConvention.invokeMethod(BundleTaskConvention.groovy)
        at org.gradle.api.internal.BeanDynamicObject$GroovyObjectAdapter.invokeMethod(BeanDynamicObject.java:275)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:212)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
        at org.gradle.api.tasks.bundling.Jar_Decorated.invokeMethod(Unknown Source)
        at aQute.bnd.gradle.BndBuilderPlugin$_apply_closure1_closure2_closure3.doCall(BndBuilderPlugin.groovy:36)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

**Comment by bjhargrave** [comment]
`Bundle-Version` is set from the gradle project's version property if `Bundle-Version` is unset.

```groovy
        // set bundle version from task's version if necessary
        def String bundleVersion = builder.getProperty(Constants.BUNDLE_VERSION)
        if (isEmpty(bundleVersion)) {
          builder.setProperty(Constants.BUNDLE_VERSION, Version.parseVersion(version).toString())
        }
```

So if your gradle project's version property is not a valid OSGi version, which seems to be the case, then you must set `Bundle-Version` for the bundle you are building.

**Comment by bjhargrave** [comment]
I am working on a fix for the gradle plugin to handle maven style versions. Hold tight...

**Comment by m3git** [comment]
Thank you!
