### ISSUE TITLE
Maven Plugin to export a bndrun

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1107]
This maven plugin should be able to export one or more bndrun files.

Note. The -runpath in the bndrun file defines the launcher with as default the biz.aQute.launcher. It is the launcher that must be used for exporting this. The remote launcher will support exporting to WAR, KAR, etc. based on a distro.

**Comment by cschneider** [comment]
I just added an integration test and fixed the version problem in travis. From my side this should be complete. 
@pkriens Do you agree to also offer a resolve option beside the export with a default of false?
@bjhargrave If you are fine with the current status I will squash the commits into one again

**Comment by cschneider** [comment]
I just tested the new plugin with my osgi-chat example and got this error:
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0-SNAPSHOT:export (default) on project net.lr.demo.chat.packaging.service: Default handler for Launcher-Plugin not found in biz.aQute.launcher -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0-SNAPSHOT:export (default) on project net.lr.demo.chat.packaging.service: Default handler for Launcher-Plugin not found in biz.aQute.launcher
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
	at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:51)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
	at aQute.bnd.build.Project.getHandler(Project.java:2533)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2482)
	at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:56)
	at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:47)
	... 21 more

**Comment by cschneider** [comment]
@bjhargrave Just wanted to bump this issue as you plan a release pretty soon.

**Comment by bjhargrave** [comment]
This issue is closed. If you have a new problem, please open a new issue.
