### ISSUE TITLE
Using the @Reference annotation on a field leads to an NPE in the aQute.bnd.component.AnnotationReader.doReference

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1148]
Since OSGi Compendium 6.0 ($112.8.1) the `Reference` annotation can also be used on fields (not only on methods). But then running bnd on those files leads to the following exception
```
java.lang.NullPointerException
	at aQute.bnd.component.AnnotationReader.doReference(AnnotationReader.java:272)
	at aQute.bnd.component.AnnotationReader.annotation(AnnotationReader.java:190)
	at aQute.bnd.osgi.Clazz.doAnnotations(Clazz.java:1169)
	at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:849)
	at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:824)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:609)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:439)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:428)
	at aQute.bnd.component.AnnotationReader.getDef(AnnotationReader.java:90)
	at aQute.bnd.component.AnnotationReader.getDefinition(AnnotationReader.java:86)
	at aQute.bnd.component.DSAnnotations.analyzeJar(DSAnnotations.java:32)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:312)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:163)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:324)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:342)
	at aQute.bnd.osgi.Builder.build(Builder.java:77)
```

The example component source code looks like this:
```
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.component.annotations.Reference;


@Component(configurationPolicy=ConfigurationPolicy.REQUIRE)
public class SomeComponent {

    @Reference
    private HttpService httpService;

```

Although not 100% clear from the spec I would expect bnd to create the according bind method automatically (as the maven-scr-plugin did in the past). At least the exception should be handled in a more graceful way, so that I get an exception like 
`Could not find bind method with name ... for the field ... annotated with @Reference`

**Comment by bjhargrave** [comment]
There must be something else at play here. We have numerous tests for using @Reference on fields.
 What version of bnd are you using? It is possible you are using an older version (pre 3.0) which does not understand @Reference on fields.

In version 3.0, [line 272 of the `AnnotationReader` class](https://github.com/bndtools/bnd/blob/3.0.0.REL/biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java#L272) is not in the `doReference` method.

**Comment by djencks** [comment]
Along with what BJ said, the @Reference on field support in DS 1.3 works directly on fields, not by modifying the class byte code.  I think this is pretty clearly expressed in the spec.

david jencks

**Comment by kwin** [comment]
It was together with the maven-bundle-plugin 3.0, the full stack trace is
```
[INFO] --- maven-bundle-plugin:3.0.0:bundle (default-bundle) @ module ---
java.lang.NullPointerException
	at aQute.bnd.component.AnnotationReader.doReference(AnnotationReader.java:272)
	at aQute.bnd.component.AnnotationReader.annotation(AnnotationReader.java:190)
	at aQute.bnd.osgi.Clazz.doAnnotations(Clazz.java:1169)
	at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:849)
	at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:824)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:609)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:439)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:428)
	at aQute.bnd.component.AnnotationReader.getDef(AnnotationReader.java:90)
	at aQute.bnd.component.AnnotationReader.getDefinition(AnnotationReader.java:86)
	at aQute.bnd.component.DSAnnotations.analyzeJar(DSAnnotations.java:32)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:312)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:163)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:324)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:342)
	at aQute.bnd.osgi.Builder.build(Builder.java:77)
	at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:651)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:371)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:288)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:279)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Bundle <groupId>:<artifactId>:bundle:0.0.1-SNAPSHOT : During generation of a component on class <MyComponentClass>, exception java.lang.NullPointerException

```
The problem really was caused by using the bnd plugin org.apache.felix.scrplugin.bnd.SCRDescriptorBndPlugin which transitively depends on bnd 2.1. I opened https://issues.apache.org/jira/browse/FELIX-5074 for that.

**Comment by bjhargrave** [comment]
If you are using the OSGi R6 annotations, why are you even then using the `org.apache.felix.scr.bnd` maven plugin? You don't need that for OSGi R6 annotations.

**Comment by kwin** [comment]
I know, but we are in a transition phase, so some services in the same project still use Felix SCR annotations!

**Comment by bjhargrave** [comment]
Good luck to you then :-)
