### ISSUE TITLE
Package import missing when type is used with J8 method reference

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1310]
I found a scenario where bnd fails to add an import for a package that is needed. A minimal demonstrator project can be found here: [github.com/njbartlett/bnd_j8_bug](https://github.com/njbartlett/bnd_j8_bug).

To summarise, I have a service which returns a collection of objects. The collection content type is from a different package than the service API. I.e.:

	package org.example.api;
	public interface FooService {
		Collection<org.example.model.Foo> getFoos();
	}

Now a consumer bundle uses `FooService` as follows:

	fooSvc.getFoos().forEach(System.out::println);

This throws an exception because our consumer bundle fails to import `org.example.model`:

	Caused by: java.lang.NoClassDefFoundError: org/example/model/Foo
		at org.example.client.ExampleCommand.crash(ExampleCommand.java:22)
		... 29 more
	Caused by: java.lang.ClassNotFoundException: org.example.model.Foo not found by org.example.client [5]
		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)
		at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 30 more

Note that if you use the service in a slightly different way, with a lambda instead of a method reference, bnd imports the package and all is well:

	fooSvc.getFoos().forEach(f -> System.out.print(f));

To see the crash happening, run `org.example.client/launch.bndrun` from the exemplar project and type the Gogo command `crash`.

**Comment by njbartlett** [comment]
Here is the disassembled code for ExampleCommand (using `javap -p -c`):

	public class org.example.client.ExampleCommand {
	  private org.example.api.FooService fooSvc;
	
	  public org.example.client.ExampleCommand();
	    Code:
	       0: aload_0
	       1: invokespecial #12                 // Method java/lang/Object."<init>":()V
	       4: return
	
	  public void crash();
	    Code:
	       0: getstatic     #19                 // Field java/lang/System.out:Ljava/io/PrintStream;
	       3: ldc           #25                 // String Crashing in 3... 2... 1...
	       5: invokevirtual #27                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
	       8: aload_0
	       9: getfield      #33                 // Field fooSvc:Lorg/example/api/FooService;
	      12: invokeinterface #35,  1           // InterfaceMethod org/example/api/FooService.getFoos:()Ljava/util/Collection;
	      17: getstatic     #19                 // Field java/lang/System.out:Ljava/io/PrintStream;
	      20: invokedynamic #44,  0             // InvokeDynamic #0:accept:(Ljava/io/PrintStream;)Ljava/util/function/Consumer;
	      25: invokeinterface #45,  2           // InterfaceMethod java/util/Collection.forEach:(Ljava/util/function/Consumer;)V
	      30: return
	}

**Comment by bjhargrave** [comment]
Here is the larger javap. The interesting thing is constant pool entry #48 which references the interesting type. However #48 is only referenced by the bootstrap method at the end. It is possible bnd does not know about or process bootstrap methods for type references.
```
$ javap -v -cp org.example.client/bin org.example.client.ExampleCommand
Classfile /Users/hargrave/git/tmp/bnd_j8_bug/org.example.client/bin/org/example/client/ExampleCommand.class
  Last modified Feb 10, 2016; size 1714 bytes
  MD5 checksum 1bed104c5bcc1393dfed108a57e29bb0
  Compiled from "ExampleCommand.java"
public class org.example.client.ExampleCommand
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #11.#34        // java/lang/Object."<init>":()V
   #2 = Fieldref           #35.#36        // java/lang/System.out:Ljava/io/PrintStream;
   #3 = String             #37            // Crashing in 3... 2... 1...
   #4 = Methodref          #38.#39        // java/io/PrintStream.println:(Ljava/lang/String;)V
   #5 = Fieldref           #10.#40        // org/example/client/ExampleCommand.fooSvc:Lorg/example/api/FooService;
   #6 = InterfaceMethodref #41.#42        // org/example/api/FooService.getFoos:()Ljava/util/Collection;
   #7 = Methodref          #11.#43        // java/lang/Object.getClass:()Ljava/lang/Class;
   #8 = InvokeDynamic      #0:#49         // #0:accept:(Ljava/io/PrintStream;)Ljava/util/function/Consumer;
   #9 = InterfaceMethodref #50.#51        // java/util/Collection.forEach:(Ljava/util/function/Consumer;)V
  #10 = Class              #52            // org/example/client/ExampleCommand
  #11 = Class              #53            // java/lang/Object
  #12 = Utf8               fooSvc
  #13 = Utf8               Lorg/example/api/FooService;
  #14 = Utf8               RuntimeInvisibleAnnotations
  #15 = Utf8               Lorg/osgi/service/component/annotations/Reference;
  #16 = Utf8               <init>
  #17 = Utf8               ()V
  #18 = Utf8               Code
  #19 = Utf8               LineNumberTable
  #20 = Utf8               LocalVariableTable
  #21 = Utf8               this
  #22 = Utf8               Lorg/example/client/ExampleCommand;
  #23 = Utf8               crash
  #24 = Utf8               SourceFile
  #25 = Utf8               ExampleCommand.java
  #26 = Utf8               Lorg/osgi/service/component/annotations/Component;
  #27 = Utf8               service
  #28 = Utf8               Ljava/lang/Object;
  #29 = Utf8               immediate
  #30 = Integer            1
  #31 = Utf8               property
  #32 = Utf8               osgi.command.scope=bug
  #33 = Utf8               osgi.command.function=crash
  #34 = NameAndType        #16:#17        // "<init>":()V
  #35 = Class              #54            // java/lang/System
  #36 = NameAndType        #55:#56        // out:Ljava/io/PrintStream;
  #37 = Utf8               Crashing in 3... 2... 1...
  #38 = Class              #57            // java/io/PrintStream
  #39 = NameAndType        #58:#59        // println:(Ljava/lang/String;)V
  #40 = NameAndType        #12:#13        // fooSvc:Lorg/example/api/FooService;
  #41 = Class              #60            // org/example/api/FooService
  #42 = NameAndType        #61:#62        // getFoos:()Ljava/util/Collection;
  #43 = NameAndType        #63:#64        // getClass:()Ljava/lang/Class;
  #44 = Utf8               BootstrapMethods
  #45 = MethodHandle       #6:#65         // invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #46 = MethodType         #66            //  (Ljava/lang/Object;)V
  #47 = MethodHandle       #5:#67         // invokevirtual java/io/PrintStream.println:(Ljava/lang/Object;)V
  #48 = MethodType         #68            //  (Lorg/example/model/Foo;)V
  #49 = NameAndType        #69:#70        // accept:(Ljava/io/PrintStream;)Ljava/util/function/Consumer;
  #50 = Class              #71            // java/util/Collection
  #51 = NameAndType        #72:#73        // forEach:(Ljava/util/function/Consumer;)V
  #52 = Utf8               org/example/client/ExampleCommand
  #53 = Utf8               java/lang/Object
  #54 = Utf8               java/lang/System
  #55 = Utf8               out
  #56 = Utf8               Ljava/io/PrintStream;
  #57 = Utf8               java/io/PrintStream
  #58 = Utf8               println
  #59 = Utf8               (Ljava/lang/String;)V
  #60 = Utf8               org/example/api/FooService
  #61 = Utf8               getFoos
  #62 = Utf8               ()Ljava/util/Collection;
  #63 = Utf8               getClass
  #64 = Utf8               ()Ljava/lang/Class;
  #65 = Methodref          #74.#75        // java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #66 = Utf8               (Ljava/lang/Object;)V
  #67 = Methodref          #38.#76        // java/io/PrintStream.println:(Ljava/lang/Object;)V
  #68 = Utf8               (Lorg/example/model/Foo;)V
  #69 = Utf8               accept
  #70 = Utf8               (Ljava/io/PrintStream;)Ljava/util/function/Consumer;
  #71 = Utf8               java/util/Collection
  #72 = Utf8               forEach
  #73 = Utf8               (Ljava/util/function/Consumer;)V
  #74 = Class              #77            // java/lang/invoke/LambdaMetafactory
  #75 = NameAndType        #78:#82        // metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #76 = NameAndType        #58:#66        // println:(Ljava/lang/Object;)V
  #77 = Utf8               java/lang/invoke/LambdaMetafactory
  #78 = Utf8               metafactory
  #79 = Class              #84            // java/lang/invoke/MethodHandles$Lookup
  #80 = Utf8               Lookup
  #81 = Utf8               InnerClasses
  #82 = Utf8               (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #83 = Class              #85            // java/lang/invoke/MethodHandles
  #84 = Utf8               java/lang/invoke/MethodHandles$Lookup
  #85 = Utf8               java/lang/invoke/MethodHandles
{
  public org.example.client.ExampleCommand();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 13: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lorg/example/client/ExampleCommand;

  public void crash();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=1, args_size=1
         0: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
         3: ldc           #3                  // String Crashing in 3... 2... 1...
         5: invokevirtual #4                  // Method java/io/PrintStream.println:(Ljava/lang/String;)V
         8: aload_0
         9: getfield      #5                  // Field fooSvc:Lorg/example/api/FooService;
        12: invokeinterface #6,  1            // InterfaceMethod org/example/api/FooService.getFoos:()Ljava/util/Collection;
        17: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
        20: dup
        21: invokevirtual #7                  // Method java/lang/Object.getClass:()Ljava/lang/Class;
        24: pop
        25: invokedynamic #8,  0              // InvokeDynamic #0:accept:(Ljava/io/PrintStream;)Ljava/util/function/Consumer;
        30: invokeinterface #9,  2            // InterfaceMethod java/util/Collection.forEach:(Ljava/util/function/Consumer;)V
        35: return
      LineNumberTable:
        line 19: 0
        line 22: 8
        line 26: 35
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      36     0  this   Lorg/example/client/ExampleCommand;
}
SourceFile: "ExampleCommand.java"
RuntimeInvisibleAnnotations:
  0: #26(#27=[c#28],#29=Z#30,#31=[s#32,s#33])
InnerClasses:
     public static final #80= #79 of #83; //Lookup=class java/lang/invoke/MethodHandles$Lookup of class java/lang/invoke/MethodHandles
BootstrapMethods:
  0: #45 invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #46 (Ljava/lang/Object;)V
      #47 invokevirtual java/io/PrintStream.println:(Ljava/lang/Object;)V
      #48 (Lorg/example/model/Foo;)V
```

**Comment by njbartlett** [comment]
To clarify...

With the method reference version of the code, the client bundle only imports `org.example.api`. With the lambda version, bnd generates an import for both `org.example.api` AND `org.example.model`. This is why the lambda version works.

In both cases, Java is requesting the `org.example.model.Foo` class from the client bundle.
