### ISSUE TITLE
Repo macro in -include directive crashes build

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1499]
Currently if we use the ${repo;} macro under the -include directive the build crashes with the following exception:

> **java.util.UnknownFormatConversionException: Conversion = 'F'**
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at aQute.bnd.osgi.Processor.formatArrays(Processor.java:1973)
	at aQute.bnd.osgi.Processor.error(Processor.java:285)
	at aQute.bnd.osgi.Processor.doIncludes(Processor.java:1035)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:947)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:1169)
	at aQute.bnd.osgi.Processor.forceRefresh(Processor.java:1134)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:150)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:138)
	at bndtools.central.Central.bndCall(Central.java:595)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:138)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

(Though this appears to be an error thrown as a side-effect of attempting to format the *actual* error, so the cause is lost.)

In conjunction with #1498 I feel like this could provide a nice strategy to resolve common .bnd files as an alternative to e.g. git submodules (which is sub-optimal imo, no matter what [this page](http://bnd.bndtools.org/chapters/140-best-practices.html) says!)

**Comment by eliasvasylenko** [comment]
On reflection this is not be a problem with the usage of the repo macro, it's because the resulting path string has a bunch of % characters in it and the error reporting tries to format the string and gets confused.

I'll assume it *would* work if the path pointed to something it could actually include, and report a new issue for the actual bug in a mo.
