### ISSUE TITLE
Exception when calling bnd-export-maven-plugin "Default handler for Launcher-Plugin not found"

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1590]
I just tested the new plugin with my osgi-chat example and got this error:
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0-SNAPSHOT:export (default) on project net.lr.demo.chat.packaging.service: Default handler for Launcher-Plugin not found in biz.aQute.launcher -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0-SNAPSHOT:export (default) on project net.lr.demo.chat.packaging.service: Default handler for Launcher-Plugin not found in biz.aQute.launcher
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:51)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
Caused by: java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
at aQute.bnd.build.Project.getHandler(Project.java:2533)
at aQute.bnd.build.Project.getProjectLauncher(Project.java:2482)
at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:56)
at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:47)
... 21 more

**Comment by bjhargrave** [comment]
Can you please make a PR with a new test case which demonstrates the problem?

**Comment by cschneider** [comment]
Not sure what caused the problem but after doing a full build of bnd master it now works. I guess I had some stale snapshot of some lib.
