### ISSUE TITLE
pom repo error on entity references

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1638]
See the repo https://github.com/rotty3000/pom.tests to reproduce.

```
org.xml.sax.SAXParseException; lineNumber: 83; columnNumber: 27; The entity "nbsp" was referenced, but not declared.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at aQute.maven.provider.POM.<init>(POM.java:71)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:309)
	at aQute.maven.provider.MavenRepository$2.apply(MavenRepository.java:338)
	at aQute.maven.provider.MavenRepository$2.apply(MavenRepository.java:331)
	at org.osgi.util.promise.PromiseImpl$Map.call(PromiseImpl.java:409)
	at org.osgi.util.promise.PromiseImpl$Then.run(PromiseImpl.java:240)
	at org.osgi.util.promise.PromiseImpl.notifyCallbacks(PromiseImpl.java:137)
	at org.osgi.util.promise.PromiseImpl.onResolve(PromiseImpl.java:175)
	at org.osgi.util.promise.PromiseImpl.then(PromiseImpl.java:184)
	at org.osgi.util.promise.PromiseImpl.then(PromiseImpl.java:192)
	at org.osgi.util.promise.PromiseImpl.map(PromiseImpl.java:393)
	at aQute.maven.provider.MavenRepository.getPomPromise(MavenRepository.java:331)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:317)
	at aQute.bnd.repository.maven.pom.provider.Traverser.parseArchive(Traverser.java:174)
	at aQute.bnd.repository.maven.pom.provider.Traverser.access$000(Traverser.java:42)
	at aQute.bnd.repository.maven.pom.provider.Traverser$1.run(Traverser.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rotty3000** [comment]
BTW this is only a reported error. It does not prevent the repo from being usable.

**Comment by seanbright** [comment]
`&nbsp` is not valid XML. Any idea what POM this came from?

**Comment by bjhargrave** [comment]
Yes, that is a bad pom. I bet it is the only one....

**Comment by rotty3000** [comment]
Closing because bad poms!
