### ISSUE TITLE
ConcurrentModificationException when refreshing repositories

### ISSUE THREAD

**Issue by lukewink** [bndtools/bnd#1684]
I got the following exception when refreshing the workspace repositories.

    Exception:java.util.ConcurrentModificationException: null
    	 at java.util.Hashtable$Enumerator.next(Hashtable.java:1367)
    	 at aQute.bnd.osgi.Processor.keySet(Processor.java:2237)
    	 at aQute.bnd.osgi.Processor.iterator(Processor.java:2210)
    	 at aQute.bnd.osgi.Processor.getProperty(Processor.java:1284)
    	 at aQute.bnd.osgi.Processor.mergeProperties(Processor.java:2551)
    	 at aQute.bnd.osgi.Processor.mergeProperties(Processor.java:2546)
    	 at aQute.bnd.osgi.Processor.getMergedParameters(Processor.java:2562)
    	 at aQute.bnd.build.Workspace.addExtensions(Workspace.java:638)
    	 at aQute.bnd.osgi.Processor.getPlugins(Processor.java:521)
    	 at aQute.bnd.osgi.Processor.getPlugins(Processor.java:465)
    	 at bndtools.central.WorkspaceRepositoryChangeDetector$1.run(WorkspaceRepositoryChangeDetector.java:130)
    	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I am not able to reliably reproduce the issue.  It seems to happen somewhat randomly.

**Comment by bjhargrave** [comment]
What version of bndtools are you using? Are you using the latest RC2 or DEV build from cloudbees? That code was changed for RC2 and the stacktrace looks pre-RC2.

**Comment by lukewink** [comment]
I am running the master branch from September 2.  I can update and see if the issue happens with the latest RC (it can take days for the issue to happen though).

**Comment by bjhargrave** [comment]
Please do.

**Comment by lukewink** [comment]
I  haven't seen this issue running the latest RC.  I will close this issue for now and re-open if I see it again.
