### ISSUE TITLE
[3.3.0 RC1] MavenRepository not using localRepository from settings / cannot follow symlink

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bnd#1685]
In our corporate environment we set our local-maven-repo to another location than ~/.m2/repository due to performance issues with the virus-scanner. 
The location is configured in Mavens settings.xml:
`<localRepository>C:/Development/temp/maven-local-repository</localRepository>`
Since some tools still use the default location I've also setup a symlink (Windows mklink) which also points to the configured location (this usually works).

Now BndTools is able to download the maven-artifacts I specify to the configured local-repo and the Repositories-View is able to open the file, but using the artifact as build-dependency yields the following exception.

`java.lang.reflect.InvocationTargetException
	at org.osgi.util.promise.PromiseImpl.getValue(PromiseImpl.java:159)
	at aQute.bnd.repository.maven.provider.MavenBndRepository.get(MavenBndRepository.java:390)
	at bndtools.model.repo.RepositoryEntry.getFile(RepositoryEntry.java:117)
	at bndtools.views.repository.RepositoriesView$7$1.run(RepositoriesView.java:372)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: For Maven artifact org.ops4j.pax.cdi:pax-cdi-api:1.0.0-SNAPSHOT,
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Root exception:
java.io.FileNotFoundException: For Maven artifact org.ops4j.pax.cdi:pax-cdi-api:1.0.0-SNAPSHOT,
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

The error-log complains about the missing file, which actually exists on the filesystem.

Bnd should either honor the repository-location specified within the settings, or make sure to follow symlinks.

**Comment by seanbright** [comment]
@lostiniceland, can you paste your repository configuration please?

**Comment by bjhargrave** [comment]
use the `-Dmaven.repo.local=C:/Development/temp/maven-local-repository`system property to set another local repo value. Bnd only uses the connection information from settings.xml not all the information.

**Comment by seanbright** [comment]
Assuming that `aQute.libg` is upgraded to at least Java 7 in the future, we can detect and follow symlinks. With Java 1.6 we don't have that ability.

**Comment by lostiniceland** [comment]
`-Dmaven.repo.local=C:/Development/temp/maven-local-repository` solved it.

Regarding symlinks in general: wasnt it planned to upgrade to Java 8 with BndTools 4? Will this be the next version in development?

**Comment by bjhargrave** [comment]
> Regarding symlinks in general: wasnt it planned to upgrade to Java 8 with BndTools 4? 

Yes.

> Will this be the next version in development?

Not sure at this point. Need some more discussion in the dev team to reach consensus.

**Comment by bjhargrave** [comment]
Closing this issue since Bnd only processing connection settings in settings.xml. See <http://bnd.bndtools.org/instructions/connection-settings.html> for more information.
