### ISSUE TITLE
NPE in aQute.maven.provider.MavenRemoteRepository.fetch(MavenRemoteRepository.java:48)

### ISSUE THREAD

**Issue by tonit** [bndtools/bnd#1762]
Stack trace:
````
java.lang.reflect.InvocationTargetException
	at org.osgi.util.promise.PromiseImpl.getValue(PromiseImpl.java:159)
	at aQute.bnd.repository.maven.provider.MavenBndRepository.get(MavenBndRepository.java:393)
	at bndtools.model.repo.RepositoryEntry.getFile(RepositoryEntry.java:117)
	at bndtools.views.repository.RepositoriesView$8$1.run(RepositoriesView.java:396)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at aQute.maven.provider.MavenRemoteRepository.fetch(MavenRemoteRepository.java:48)
	at aQute.maven.provider.MavenRepository.fetch(MavenRepository.java:200)
	at aQute.maven.provider.MavenRepository.getFile(MavenRepository.java:178)
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````
What i do:
Try to resolve an artefact like biz.aQute.bnd:biz.aQute.bndlib:3.3.0

Bndtools version:   Bndtools	3.4.0.DEV-20161031-223445-g37c29c8 (from CI latest repo)
eclipse.buildId=4.6.1.M20160907-1200
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/tonit/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/tonit/.eclipse_keyring

**Comment by bjhargrave** [comment]
You also tweeted a screen cap which would be useful to add to this issue. It had a useful message in it. Thanks.

**Comment by tonit** [comment]
![event_details](https://cloud.githubusercontent.com/assets/67375/19897202/7167a8da-a057-11e6-8694-dcb4c4282712.png)

**Comment by bjhargrave** [comment]
This is a bizarre scenario where the Workspace does not have an HttpClient instance registered. Can you share a workspace which shows this error on github?

**Comment by tonit** [comment]
i will try to prepare something.

**Comment by bjhargrave** [comment]
Please reopen if you can make an example repo which shows the problem.
