### ISSUE TITLE
NPE in aQute.bnd.repository.maven.provider.IndexFile.refresh(IndexFile.java:216)

### ISSUE THREAD

**Issue by tonit** [bndtools/bnd#1765]
I was just upgrading to   Bndtools	3.4.0.DEV-20161102-194936-g37c29c8 to check if another NPE from yesterday had been fixed, just stumpled over another NPE.
Yeah maybe i need to stop following all ci builds..

Anyway, what was i doing. Well just tried to make refresh my repositories (infact only one that is Maven based)

Stacktrace:
````
java.lang.NullPointerException
	at aQute.bnd.repository.maven.provider.IndexFile.refresh(IndexFile.java:216)
	at aQute.bnd.repository.maven.provider.MavenBndRepository.refresh(MavenBndRepository.java:583)
	at bndtools.central.Central.refreshPlugins(Central.java:469)
	at bndtools.views.repository.RepositoriesView$11$1.runInWorkspace(RepositoriesView.java:585)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
````

Session Data:
`````
eclipse.buildId=4.6.1.M20160907-1200
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/tonit/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data file:/Users/tonit/Documents/workspaceNeon2/ -keyring /Users/tonit/.eclipse_keyring
`````

**Comment by tonit** [comment]
![event_details](https://cloud.githubusercontent.com/assets/67375/19963852/ba414ee0-a1be-11e6-95cc-fefee5ca004a.png)

**Comment by tonit** [comment]
thanks for the fix
