### ISSUE TITLE
bnd-testing-maven-plugin exception on completion

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1819]
Whenever the `bnd-testing-maven-plugin` completes it's execution of the test suite (whether there are failures or everything passed), the following exception is thrown:

```
Exception in thread "Equinox Shutdown Hook" java.lang.NullPointerException
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at org.eclipse.osgi.storage.Storage.saveGenerations(Storage.java:1084)
	at org.eclipse.osgi.storage.Storage.save0(Storage.java:1037)
	at org.eclipse.osgi.storage.Storage.save(Storage.java:1010)
	at org.eclipse.osgi.internal.framework.StorageSaver$StorageSaverTask.run(StorageSaver.java:28)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjhargrave** [comment]
I guess this is why you just kill the VM under test rather than trying to be nice and shutting down the framework :-)

**Comment by rotty3000** [comment]
This is BECAUSE we're just killing the VM and not shutting it down properly.

**Comment by rotty3000** [comment]
However, I'm not sure why we only see this on the maven testing side... though I haven't spent time recently with integration testing on the gradle (or bnd workspace) side.

**Comment by rotty3000** [comment]
I haven't seen this issue in quite a while so closing.
