### ISSUE TITLE
Project.exportRunbundles tries to copy JARs from the workspace, even though -runrepos excludes the workspace

### ISSUE THREAD

**Issue by gravelld** [bndtools/bnd#1825]
bndtools 3.3.0.

I have a bndrun file with the following declarations:

```
-runbundles: \
...
	com.elsten.bliss.regexrule.trim;version='[1.0.21,1.0.22)',\
...
-runrepos: \
	Release,\
	Local,\
	InfoRepositoryWrapper[1]
```
My repositories look like:

![screenshot_2016-12-19_14-02-24](https://cloud.githubusercontent.com/assets/873704/21315386/d3850e4c-c5f3-11e6-8440-a13e93ccfc93.png)

So it's both in the workspace and the Release repository.

When I run the `runbundles` Gradle task it fails. I use `--stacktrace` and it shows:

```
Caused by: org.gradle.api.GradleException: Creating a distribution of the runbundles in /home/gravelld/eclipse-workspaces/bliss-neon/com.elsten.bliss.build.bnd/product.bndrun failed
	at aQute.bnd.gradle.BndPlugin$_apply_closure1_closure23_closure58_closure60.doCall(BndPlugin.groovy:389)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
Caused by: java.io.FileNotFoundException: During copy: /home/gravelld/eclipse-workspaces/bliss-neon/com.elsten.bliss.regexrule.trim/generated/com.elsten.bliss.regexrule.trim.jar
	at aQute.lib.io.IO.copy(IO.java:248)
	at aQute.bnd.build.Project.exportRunbundles(Project.java:1926)
	at aQute.bnd.build.Project$exportRunbundles$16.call(Unknown Source)
```
Now, in the workspace the .trim project is not compiling. 

So it appears `runbundles` is trying to copy from the Workspace rather than my repository? 

I thought `-runrepos` would stop this? 

Is this useful from a release process point of view? I thought users would want to release bundles to Release, then run a build that picks up those JARs. If the workspace is edited between release and product build, you could end up with incorrect JARs in the resulting build.

**Comment by rotty3000** [comment]
Dan can you please show a picture of the Repositories view in the run editor?

**Comment by gravelld** [comment]
Sure:

![screenshot_2016-12-19_15-22-53](https://cloud.githubusercontent.com/assets/873704/21317918/0f27bdfe-c5ff-11e6-9b29-96d19092dd71.png)

Unfortunately the list box is a fixed size - the strikethrough items are _Workspace_ and _Templates_.

**Comment by bjhargrave** [comment]
Looking at the code for Bnd, I see that `-runrepos` is only used by the resolver: https://github.com/bndtools/bnd/blob/master/biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java#L340-L348

It is not consulted for any other purpose including export.

According to the (limited) documentation for `-runrepos` at http://bnd.bndtools.org/chapters/825-instructions-ref.html:

`Order and select the repository for resolving against. The default order is all repositories in their plugin creation order.`

So I am unsure there is a bug here or whether `-runrepos` is intended to only apply to resolve operations.

**Comment by gravelld** [comment]
Yeah, I'm prepared to accept this isn't a bug - but then because it's called `-runrepos` and not `-resolverepos` that tipped the balance.

In reality I think a way of choosing which repositories are used for Project.exportRunbundles is needed.

Actually and also... I thought the bndtools plugin did use '-runrepos' when running an OSGi framework with a bndrun file?

So can anyone think of a workaround?

**Comment by bjhargrave** [comment]
Can you make a PR to add support for `-runrepos` for bndrun launching/exporting?

**Comment by gravelld** [comment]
Unfortunately I'm currently in the process of withdrawing from OSGi, so it's probably not the best use of my time... thanks for your help though.
