### ISSUE TITLE
[3.4 RC2] Nullpointer when refreshing a BndPomRepository

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bnd#2084]
Since of today I cannot use my configured BndPomRepository any more. I am not able to update nor to browse it. I always get a nullpointer.

```
java.lang.NullPointerException
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.refresh(BndPomRepository.java:101)
	at bndtools.central.Central.refreshPlugins(Central.java:438)
	at bndtools.views.repository.RepositoriesView$11$1.runInWorkspace(RepositoriesView.java:595)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

The repo is connecting against a corporate Nexus

```
-plugin:\
	aQute.bnd.deployer.repository.wrapper.Plugin; \
		location="${build}/cache/wrapper"; \
		reindex=true, \
	\
	aQute.bnd.deployer.repository.LocalIndexedRepo; \
		name=Local; \
		local=${workspace}/cnf/localrepo; \
		pretty=true,\
	\
	aQute.bnd.deployer.repository.LocalIndexedRepo;\
		name=Release; \
		local=${workspace}/cnf/releaserepo; \
		pretty=true, \
	\
	aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        name=Nexus; \
        pom="${build}/maven.xml"; \
        releaseUrls=https://nexus.ourdomain/nexus/content/groups/repo/
```

The repo worked just some days ago but after some metadata changed on the nexus I always get the exception

**Comment by lostiniceland** [comment]
Deleting cnf/cache solved the problem.
