### ISSUE TITLE
Windows: Build fails occasionally due to strange biz.aQute.junit related NoClassDefFoundError

### ISSUE THREAD

**Issue by JanMosigItemis** [bndtools/bnd#2140]
Hi everyone,

on a customer project we have a bnd build that runs JUnit tests as well as some OSGi integration tests and Groovy tests. Recently we migrated from 3.3.0 to 3.4.0. We noticed that in like 1 out of 5 builds, the build fails with one of the following errors:

`#0   WARNING > Corrupted subjar file junit.jar for bundle org.junit. It will be extracted from the bundle jar.
#0   ERROR   > Error occurred while trying to activate bundle biz.aQute.junit 3.4.0.201707252008!
java.lang.NoClassDefFoundError: junit/framework/Test`

OR

`! Unexpected error in the run body: junit/framework/Test
INFO  Bundle #90 - "biz.aQute.junit-3.4.0": STOPPED - (90)
java.lang.NoClassDefFoundError: junit/framework/Test
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at <classified>.framework.BundleImpl.startIt(BundleImpl.java:4404)
        [...]
        at aQute.launcher.Launcher.update(Launcher.java:500)
        at aQute.launcher.Launcher.activate(Launcher.java:400)
        at aQute.launcher.Launcher.run(Launcher.java:283)
        at aQute.launcher.Launcher.main(Launcher.java:138)
Caused by: java.lang.ClassNotFoundException: junit.framework.Test: not in imports of bundle biz.aQute.junit
        at <classified>.framework.PackagesManager.loadImportedClass0(PackagesManager.java:2128)
        at <classified>.framework.PackagesManager.loadImportedClass(PackagesManager.java:2001)
        [...]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more`

The problem does seem to only occur on Windows machines. I suspected my antivirus might cause the problems but we were able to spot it on another Windows machine that does not run any antivirus except for Windows Defender. No problems could be found when running the build on our CI servers (running Linux).

The problem occurs on a regular basis but does not seem to follow a pattern. However, it tends to show up more often if we clone the repo and load the cnf cache from scratch.

Today I switched back to our bnd 3.3.0 build which we know works and did not have this issue. Unfortunately I could also reproduce the problem there:

`#0   WARNING > Corrupted subjar file junit.jar for bundle org.junit. It will be extracted from the bundle jar.
#0   ERROR   > Error occurred while trying to activate bundle biz.aQute.junit 3.3.0.201611071523!
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/NoTestsRemainException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at <classified>.framework.BundleImpl.startIt(BundleImpl.java:4404)
        [...]
        at aQute.launcher.Launcher.update(Launcher.java:386)
        at aQute.launcher.Launcher.activate(Launcher.java:310)
        at aQute.launcher.Launcher.run(Launcher.java:199)
        at aQute.launcher.Launcher.main(Launcher.java:90)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.NoTestsRemainException: not in imports of bundle biz.aQute.junit
        at <classified>.loadImportedClass0(PackagesManager.java:2128)
        [...]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more`

My wild guess is that it may have something to do with recent Windows patches and how bz.aQute.junit is loaded on container startup. Any help on that issue is appreciated.

**Comment by pkriens** [comment]
Is this still occurring?

**Comment by JanMosigItemis** [comment]
I just saw this yesterday, although it does not bug me that often.

**Comment by JanMosigItemis** [comment]
I have not seen this error with our current build based on bnd 4.0.0 and gradle 4.7.
