### ISSUE TITLE
bnd-indexer-maven-plugin fails if inputDir folder contains a folder.

### ISSUE THREAD

**Issue by nport** [bndtools/bnd#2208]
If the folder to be indexed with the "local-index" goal contains a folder, the indexing process fails with the following exception:

```
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index (equinox) on project it.tim.probe.bndrun: <inputDir>\AAAA -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index (equinox) on project it.tim.probe.bndrun: <inputDir>\AAAA
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: D:\Develop\repositories\easyacs\easyacs-probes\it.tim.probe.bndrun\plugins\equinox\AAAA
        at aQute.bnd.maven.indexer.plugin.LocalIndexerMojo.execute(LocalIndexerMojo.java:77)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.nio.file.AccessDeniedException: D:\Develop\repositories\easyacs\easyacs-probes\it.tim.probe.bndrun\plugins\equinox\AAAA
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at aQute.lib.io.IO.stream(IO.java:866)
        at aQute.lib.io.IO.stream(IO.java:862)
        at aQute.bnd.osgi.Domain.domain(Domain.java:468)
        at aQute.bnd.osgi.resource.ResourceBuilder.addFile(ResourceBuilder.java:681)
        at aQute.bnd.maven.indexer.plugin.LocalIndexerMojo.execute(LocalIndexerMojo.java:75)
        ... 22 more
```
I am using bnd-indexer-maven-plugin 3.5.0 on Windows 10.

I guess that the problem could be in the following two classes:

* ResourceBuilder (of bndlib) because the addFile() method accepts a File that is a directory, but then it is not able to handle it. I would suggest a more appropriate exception.
* LocalIndexerMojo because it passes a File that is actually a directory.

I got this exeption while trying to index folder
```
<eclipse workspace folder>\.metadata\.plugins\org.eclipse.pde.core\.bundle_pool\plugins
```
that on Eclipse contains the current target platform that in turns contains some 'unzipped' bundles.

**Comment by bjhargrave** [comment]
Reading the doc for the local-index goal, it says the input folder must contain bundles. You seem to be passing it a folder that can contain directories as well as bundles. Perhaps you should sanitize the input?

**Comment by nport** [comment]
Actually I could and I did, but this is only a workaround. I submitted this issue because probably the plugin could continue the indexing process (and maybe prints some warnings), instead exititing with an exception.
Good would be if the indexer is able to process also unzipped bundles.

**Comment by timothyjward** [comment]
> Actually I could and I did, but this is only a workaround. I submitted this issue because probably the plugin could continue the indexing process (and maybe prints some warnings), instead exititing with an exception.

The person writing the pom is in full control of the input folder and the indexer documentation is clear. It is much safer and more reliable to fail in these scenarios rather than allowing known bad input to propagate through the build.

> Good would be if the indexer was able to process also unzipped bundles.

This doesn't work because we can't generate a suitable `osgi.content` capability. What would the mime-type be? How would we generate the SHA-256 checksum? What URL would we provide?

I think the best thing that could be done in this situation is to check whether the file being indexed is actually a directory and then fail with a clearer error.

**Comment by nport** [comment]
I agree to fail with a more clearer error. Same if a wrong or unexistent filename is passed to the maven plugin. Currently it also throws an NPE.

In any case what if the folder contains, in addition to bundles, also additional files or folders (for instance documentation, release notes). 
I mentioned unzipped bundles, because Eclipse use to unzip bundles in certain cases (see my initial comment).

**Comment by bjhargrave** [comment]
> Same if a wrong or unexistent filename is passed to the maven plugin. Currently it also throws an NPE.

I already fixed this.



> It is the build owner's job to ensure that the input to the indexing step is a directory containing only bundles.

Yes, but it it can be the case that some one else created the folder and it has mixed contents. For example, a maven shaped repo or a p2 shaped repo. It would be nice to support ant-style include/exclude patterns. We need to do something similar in the Bnd build to index the release repo which is maven shaped and has pom files, sources jars, javadoc jars which we don't want in the generated index.

https://github.com/bndtools/bnd/blob/54952227991820e1c4b9478fe25f5e328dbe34f2/dist/build.gradle#L30-L36
