### ISSUE TITLE
bnd-indexer-maven-plugin throws NPE if inputDir folder does not exist or is a file.

### ISSUE THREAD

**Issue by nport** [bndtools/bnd#2209]
The bnd-indexer-mave-plugin 3.5.0 on Windows 10, when used with the local-index goal, throws NPE if inputDir contains a file that does not exist. Probably this error should be better reported to maven:

```
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index (target-platform) on project it.tim.probe.bndrun: Execution target-platform of goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index (target-platform) on project it.tim.probe.bndrun: Execution target-platform of goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution target-platform of goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:local-index failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at aQute.bnd.maven.indexer.plugin.LocalIndexerMojo.execute(LocalIndexerMojo.java:66)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

**Comment by bjhargrave** [comment]
> if inputDir contains a file that does not exist

How does a directory contain a file that does not exist? 

Can you provide more specific information on how to reproduce this?

**Comment by nport** [comment]
Sorry, for not being clear on this.  When I say inputDir I am referring to the <inputDir> tag text in the pom.xml file. If the path specified in the <inputDir> tag does not exists in the filesystem an NPE is thrown, instead of a more useful error message.
