### ISSUE TITLE
export launch.bndrun to folder  sets launch.embedded=true

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2236]
If a .bndrun is exported (using bndtools) as a folder, the product will fail after calling start with:

# starting in embedded mode
! Unexpected error in the run body: null
java.lang.NullPointerException
        at aQute.launcher.Launcher.getDigest(Launcher.java:674)
        at aQute.launcher.Launcher.installEmbedded(Launcher.java:695)
        at aQute.launcher.Launcher.update(Launcher.java:455)
        at aQute.launcher.Launcher.activate(Launcher.java:371)
        at aQute.launcher.Launcher.run(Launcher.java:289)
        at aQute.launcher.Launcher.main(Launcher.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:48)

When I edit the launch.properties and set launch.embedded=false everything works as expected.

This happens, when using bndtools 3.5 and the launchers Version is 3.5.0 as well.

**Comment by bjhargrave** [comment]
This appears to be an issue in Bndtools and how it exports the bndrun to a folder.

https://github.com/bndtools/bndtools/blob/66286cac9368f1a106cae41d8a8afcf4d525366d/bndtools.core/src/bndtools/wizards/bndfile/GenerateLauncherJarRunnable.java#L29-L35

It requests a launcher executable (i.e. embedded launcher) and then just writes the jar to a folder. So the launch.properties were generated assuming embedded launching from a jar.

**Comment by bjhargrave** [comment]
@njbartlett Can you look at changing Bndtools to fix this?

**Comment by bjhargrave** [comment]
@ungeildodger Maybe you make a PR (in the bndtools repo) to fixup the launch.properties file after it is written to the folder?
