### ISSUE TITLE
bnd run prevents use of JLine Gogo shell

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2239]
I'm trying to use the `org.apache.felix.gogo.jline` bundle to get command history, highlighting etc in Gogo shell. This works perfectly if I export my bndrun file and run the resulting JAR with `java -jar application.jar`. However when I run the bndrun file directly with `bnd run application.bndrun` then bnd does something to the terminal which prevents JLine from using it:

    Dec 19, 2017 4:15:48 PM org.jline.utils.Log logr
    WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

After turning on debug logging (i.e. edit `$JAVA_HOME/jre/lib/logging.properties`, set default level=FINEST):

    Dec 19, 2017 4:16:40 PM org.jline.utils.Log logr
    WARNING: Creating a dumb terminal
    java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:184)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:149)
        at org.apache.felix.gogo.jline.Activator.startShell(Activator.java:117)
        at org.apache.felix.gogo.jline.Activator.serviceFound(Activator.java:73)
        at org.apache.felix.gogo.jline.SingleServiceTracker.update(SingleServiceTracker.java:168)
        at org.apache.felix.gogo.jline.SingleServiceTracker.findMatchingReference(SingleServiceTracker.java:124)
        at org.apache.felix.gogo.jline.SingleServiceTracker.open(SingleServiceTracker.java:90)
        at org.apache.felix.gogo.jline.Activator.start(Activator.java:57)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at aQute.launcher.Launcher.startBundles(Launcher.java:502)
        at aQute.launcher.Launcher.activate(Launcher.java:409)
        at aQute.launcher.Launcher.run(Launcher.java:289)
        at aQute.launcher.Launcher.main(Launcher.java:142)
        Suppressed: java.lang.NoClassDefFoundError: com/sun/jna/Platform
            at org.jline.terminal.impl.jna.JnaNativePty.current(JnaNativePty.java:37)
            at org.jline.terminal.impl.jna.JnaSupportImpl.current(JnaSupportImpl.java:15)
            at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:217)
            ... 15 more
        Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform not found by org.jline [11]
            at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
            at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
            at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 18 more
        Suppressed: java.io.IOException: Not a tty
            at org.jline.terminal.impl.ExecPty.current(ExecPty.java:44)
            at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:226)
            ... 15 more
        Caused by: java.io.IOException: Error executing 'tty': not a tty
            at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
            at org.jline.terminal.impl.ExecPty.current(ExecPty.java:41)
            ... 16 more

**Comment by njbartlett** [comment]
I tried to see if there was any useful logging output when JLine works. Unfortunately it doesn't log anything in this case, even with debug level FINEST.

**Comment by psoreide** [comment]
Is this in the eclipse terminal? I got the same and concluded the eclipse "terminal" is not smart enough or compatible.

**Comment by njbartlett** [comment]
I noticed the NCDFE for class `com/sun/jna/Platform`, so I tried adding `-runsystempackages: com.sun.jna`. The same result... even the same NCDFE in the log output, despite apparently `com.sun.jna` being correctly wired into the JLine bundle:

    g! lb
        ...
        10|Active     |    1|Apache Felix Gogo JLine Shell (1.0.10)|1.0.10
        11|Active     |    1|JLine Bundle (3.2.0)|3.2.0
    g! inspect req osgi.wiring.package 11
    inspect req osgi.wiring.package org.jline [11] requires:
    ------------------------
    osgi.wiring.package; (osgi.wiring.package=com.sun.jna) resolved by:
    osgi.wiring.package; com.sun.jna 0.0.0 from org.apache.felix.framework [0]

**Comment by njbartlett** [comment]
@psoreide No this is all in a normal termina (iTerm2.app on Mac OS). The only difference is between running with `java -jar application.jar` versus `bnd run application.bndrun`. Both times are running in the same terminal.

**Comment by rotty3000** [comment]
JNA (often mistaken for JNI) is a standalone native integration library:
https://github.com/java-native-access/jna

**Comment by rotty3000** [comment]
I believe the output is this lib: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.java.dev.jna%22%20AND%20a%3A%22jna%22

**Comment by njbartlett** [comment]
Thanks @rotty3000 I'll give that a try, but TBH I think the JNA thing is a red-herring. How could this library be present when running as `java -jar` but not when running as `bnd run`? I think the message `Error executing 'tty': not a tty` is the important one.
