### ISSUE TITLE
Cannot use classes from aQute.maven.api in plugin

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#2242]
I'm writing a plugin for bnd (3.4.0). Things seemed to work fine until I tried to use a class from `aQute.maven.api`. For all classes from that package, I get:
```
java.lang.NoClassDefFoundError: aQute/maven/api/Program
	at de.mnl.osgi.bnd.repository.maven.provider.NexusSearchRepositoryProvider.init(NexusSearchRepositoryProvider.java:108)
	at de.mnl.osgi.bnd.repository.maven.provider.NexusSearchRepositoryProvider.versions(NexusSearchRepositoryProvider.java:262)
	at aQute.bnd.build.Project.getBundle(Project.java:1150)
	at aQute.bnd.build.Project.getBundles(Project.java:599)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:508)
	at aQute.bnd.build.Project.prepare(Project.java:362)
	at aQute.bnd.build.Project.getDependson(Project.java:794)
	at aQute.bnd.build.Workspace.getBuildOrder(Workspace.java:545)
	at bndtools.central.Central.getWorkspace(Central.java:241)
	at bndtools.central.Central.refreshPlugins(Central.java:436)
	at bndtools.views.repository.RepositoriesView$9.runInWorkspace(RepositoriesView.java:465)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: aQute.maven.api.Program not found, parent: org.eclipse.osgi.internal.loader.EquinoxClassLoader@3202753[biz.aQute.bndlib:3.5.0.201709291849(id=3)] urls:[file:/home/mnl/devel/de.mnl.osgi/de.mnl.osgi.bnd.repository/generated/de.mnl.osgi.bnd.repository.jar] exception:java.lang.ClassNotFoundException: aQute.maven.api.Program
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at aQute.bnd.osgi.Processor$CL.loadClass(Processor.java:1742)
	at de.mnl.osgi.bnd.repository.maven.provider.NexusSearchRepositoryProvider.init(NexusSearchRepositoryProvider.java:108)
	at de.mnl.osgi.bnd.repository.maven.provider.NexusSearchRepositoryProvider.versions(NexusSearchRepositoryProvider.java:262)
	at aQute.bnd.build.Project.getBundle(Project.java:1150)
	at aQute.bnd.build.Project.getBundles(Project.java:599)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:508)
	at aQute.bnd.build.Project.prepare(Project.java:362)
	at aQute.bnd.build.Project.getDependson(Project.java:794)
	at aQute.bnd.build.Workspace.getBuildOrder(Workspace.java:545)
	at bndtools.central.Central.getWorkspace(Central.java:241)
	at bndtools.central.Central.refreshPlugins(Central.java:436)
	at bndtools.views.repository.RepositoriesView$9.runInWorkspace(RepositoriesView.java:465)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

	at aQute.bnd.osgi.Processor$CL.loadClass(Processor.java:1753)
	... 13 more
```
Note that using other classes from bnd works (e.g. `aQute.bnd.build.Workspace`, `aQute.bnd.osgi.repository.BaseRepository`, `aQute.maven.provider.MavenBackingRepository`). I've checked that bnd has generated an import-package statement for `aQute.maven.api` for my bundle, so everything seems to be set up fine. Any ideas?

**Comment by bjhargrave** [comment]
You appear to have something wrong in your setup. You say you are using bnd 3.4 yet the stacktrace says: `biz.aQute.bndlib:3.5.0.201709291849`.

The stacktrace also contains `file:/home/mnl/devel/de.mnl.osgi/de.mnl.osgi.bnd.repository/generated/de.mnl.osgi.bnd.repository.jar` so perhaps you are repackaging Bnd code and have it mispackaged?

**Comment by mnlipp** [comment]
Thanks for the hint, made me aware that my description of the environment was incomplete. bnd 3.5.0 comes in because my plugin is used by "a bnd" which is run from inside Eclipse (Oxygen). I have switched to developing my plugin against bnd 3.5.0 to get rid of any version problems. (I'm quite sure I have fully succeeded in doing this because no older libraries can be found in the usual cache locations -- well and of course there is the explicit reference to 3.5.0 in the manifest)

The classes from `aQute.maven.api` can be used in my plugin without problems if I start a gradle build outside Eclipse. But I still get the `NoClassDefFoundError` when bnd is invoked during Eclipse startup. The obvious difference is that inside Eclipse the `EquinoxClassLoader` is used for loading the classes.

Do I have to do something special if I want a bnd plugin to also work in the "bndtools environment"?

**Comment by mnlipp** [comment]
I could get things working (for gradle *and* Eclipse) by putting a copy of the repository bundle in my plugin's path:

`...;path:="/home/mnl/devel/de.mnl.osgi/de.mnl.osgi.bnd.repository/generated/de.mnl.osgi.bnd.repository.jar,${.}/plugins/biz.aQute.repository-3.5.0.jar";...`

This brings up the question whether the content of this bundle is something that bnd plugins can rely on to be available. Or put differently, which behavior is correct when not adding the bundle explicitly: no error (the behavior exposed when bnd is called from gradle) or error (exposed when bnd is called from within eclipse)?

**Comment by bjhargrave** [comment]
Plugins use a URLClassLoader which use the class loader of `Processor` (which is in the biz.aQute.bndlib` bundle) as the parent class loader. Since biz.aQute.bndlib bundle does not import any packages from biz.aQute.repository, then plugins do not have access to those types.

So I think you can do what you have done and put the needed classes on the plugin path.

**Comment by mnlipp** [comment]
Thanks. Leaves the point why bnd when called from gradle does not use the limited classpath. But as long as this doesn't cause problems...

**Comment by BramCoding** [comment]
> Plugins use a URLClassLoader which uses the class loader of `Processor` (which is in the biz.aQute.bndlib bundle) as the parent class loader. Since biz.aQute.bndlib bundle does not import any packages from biz.aQute.repository, then plugins do not have access to those types.
> 
> So I think you can do what you have done and put the needed classes on the plugin path.

I'm not entirely sure where to put what. I am getting the biz.aQute.bndlib bundle via Maven repository, so how can I make sure that this bundle imports the biz.aQute.repository-bundle (which is also pulled from Maven repository)? Thanks in advance!

**Comment by bjhargrave** [comment]
@BramCoding I am unclear on what you are trying to do. Are you writing a Bnd plugin? e.g. extending AnalyzerPlugin? What runtime environment are you using? You mention maven. 

I suggest you send an email to the bndtools-users mail list, with sufficient details on what you are trying to do, where we can try and help you since this issue is not the proper venue for such a discussion. See <https://github.com/bndtools/bnd#feedback>.
