### ISSUE TITLE
bnd should not log error when update package decoration 

### ISSUE THREAD

**Issue by simonjhy** [bndtools/bnd#2270]
We used  bndtools 4.0.0.DEV-20180108-212757-ga57fb84 to build Liferay osgi bundle. We found two erros  about it. 
1) bnd-m2e projectDecorator couldn't get maven project raw classpath because it has been executed together, but the maven project didn't finished at all. So we got the Java Model Exception: Java Model Status [MavenSample does not exist]. Error happend the line 193 in BndConfigurator.java.
2) bnd-m2e should not throw exception when the first time to create bundle output jar. I think the package decorator job should be executed after the maven build job finished phase. The error happened in line 66 in BndConfigurator.java.

Java Model Exception: Java Model Status [MavenSample does not exist]
at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:560)
at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2492)
at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2202)
at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2224)
at org.bndtools.builder.decorator.ui.PackageDecorator.updateDecoration(PackageDecorator.java:79)
at org.bndtools.builder.decorator.ui.ProjectDecoratorImpl.updateDecoration(ProjectDecoratorImpl.java:11)
at bndtools.m2e.BndConfigurator$2.call(BndConfigurator.java:193)

**Comment by rotty3000** [comment]
Could you provide a small sample project that reproduces the error?

**Comment by simonjhy** [comment]
[dsafsdaf.tar.gz](https://github.com/bndtools/bnd/files/1647107/dsafsdaf.tar.gz) You need to import this project into latest Liferay IDE code,

**Comment by rotty3000** [comment]
Does this issue happen in a pure bndtools environment (no Liferay IDE)? 

Secondly, since this is a problem in `bnd-m2e` can you actually move this report to the bndtools repo? https://github.com/bndtools/bndtools

**Comment by simonjhy** [comment]
ok, It seems that Our ide problem. I will try to check it in pure bndtools environment.
