### ISSUE TITLE
Gradle Build fails on task testOSGi with NoSuchMethodException

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2311]
When running a build a test fails with the following message:

```
> Task :org.gecko.rest.jersey.tests:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':org.gecko.rest.jersey.tests:testOSGi'.
> Project org.gecko.rest.jersey.tests failed to test

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':org.gecko.rest.jersey.tests:testOSGi'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Project org.gecko.rest.jersey.tests failed to test
        at aQute.bnd.gradle.BndPlugin$_apply_closure1$_closure23$_closure66.doCall(BndPlugin.groovy:310)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more
Caused by: java.lang.NoSuchMethodException: aQute.tester.plugin.ProjectTesterImpl.<init>(aQute.bnd.build.Project)
        at aQute.bnd.build.Project.getHandler(Project.java:2772)
        at aQute.bnd.build.Project.getProjectTester(Project.java:2735)
        at aQute.bnd.build.Project.test(Project.java:2280)
        at aQute.bnd.build.Project$test$19.call(Unknown Source)
        at aQute.bnd.gradle.BndPlugin$_apply_closure1$_closure23$_closure66.doCall(BndPlugin.groovy:308)
        ... 37 more
```

The ProjectTesterImpl has a constructor as that takes a Project and another bundle thats runs tests in a similar fashion runs successfully right before this one. The tests run successful in BND Tools.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? You must have something misconfigured where the code finds a `aQute.tester.plugin.ProjectTesterImpl` which is not type compatible with `Project` and `Container` in bndlib.

Also, run gradle with `--debug` and look for the debug statements starting `found handler`.

**Comment by bjhargrave** [comment]
Also, you do not mention what version of Bnd/Bndtools you are using.

**Comment by juergen-albert** [comment]
I use the latest version of bnd and bndtools. But apparently the jars in cnf/cache/4.0.0/bnd-cache/* don't get updated automatically. Thus the ProjectTesterImpl bndtools places there contains a biz.aQute.tester-4.0.0.jar with a ProjectTesterImpl that looks like this:

```java
public class ProjectTesterImpl extends ProjectTester implements TesterConstants, EclipseJUnitTester {
	int					port	= -1;
	String				host;
	boolean				prepared;
	private Container	me;

	public ProjectTesterImpl(Project project, Container me) throws Exception {
		super(project);
		this.me = me;
	}
...
```

**Comment by bjhargrave** [comment]
That is correct and how it is supposed to be.

**Comment by bjhargrave** [comment]
You will see the code
https://github.com/bndtools/bnd/blob/624cff0f191034b6d5b9cd98f4f916cd7554135a/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L2764-L2773
looks for that constructor first before falling back to look for a Project only arg constructor.

**Comment by juergen-albert** [comment]
In debug, it states:

```
13:56:22.786 [DEBUG] [aQute.bnd.build.Project] found handler biz.aQute.tester from N:/git/osgi_impl/jersey_jaxrs_whiteboard/cnf/cache/4.0.0/bnd-cache/biz.aQute.tester/biz.aQute.tester-4.0.0.jar
```

which is the jar with the ProjectTesterImpl  I posted  above.

**Comment by juergen-albert** [comment]
sorry, closed the issue accidentally

**Comment by juergen-albert** [comment]
It seems to be caused by having gogo shell bundles in the runbundles. After removing the following Bundles (and the requirements thats caused them to be resolved) it works like a charm.

```
	org.apache.felix.gogo.command;version='[1.0.2,1.0.3)',\
	org.apache.felix.gogo.runtime;version='[1.0.10,1.0.11)',\
	org.apache.felix.gogo.shell;version='[1.0.0,1.0.1)',\
```

Is it worth investigating or should we close the issue?

**Comment by bjhargrave** [comment]
Since I did not reproduce this, can we close?

**Comment by JanMosigItemis** [comment]
I am afraid @bjhargrave but I ran into this only recently. I took some time to debug into things and believe I found a bug in the bndtools code.

I provided a repo that showcases the error: [https://github.com/JanMosigItemis/bnd-no-such-method](https://github.com/JanMosigItemis/bnd-no-such-method)

There are multiple things to consider here:

1. The bug is caused by a trailing comma in the `-runproperties` section in `bnd.bnd`, so the solution / workaround is to check your bnd files for trailing commas (maybe in other sections than `-runproperties` as well).
2. This problem is not identified by bndtools, i. e. the project is reported "green" in Eclipse.
3. When running unit tests via bnd launcher, the method `aQute.bnd.build.Project.getHandler(Project.java:2840)` performs a constructor search via exclusion process:
```java
try {
    Constructor<? extends T> constructor = handlerClass.getConstructor(Project.class, Container.class);
    return constructor.newInstance(this, c); // this may also cause an exception
} catch (Exception e) {
    // ignore <- all exceptions will be swallowed
}
// may cause an unhandled exception if constructor isn't found.
Constructor<? extends T> constructor = handlerClass.getConstructor(Project.class); 
return constructor.newInstance(this); // What if this call causes an exception?
```
4. Unfortunately the try..catch construction there does not only fail if a constructor isn't found, but also if calling it causes an exception. This exception is then swallowed (empty catch block) which subsequently leads to the program thinking that it has not found a proper constructor. This leads to searching for the second constructor option, which also fails and causes the NoSuchMethodException we see here.
5. The constructor that is actually found will cause a parse of the bnd file's `-runproperties` section. The parser will collect all "lines" in this section and joins them with a space into a comma separated "list", e. g.:
```
-runproperties: key=value, \
    key2=value2, \
    key3=value3, \
```
becomes `key=value, key2=value2, key3=value3,`. You see, the last comma is not removed and will cause the parser to fail with an IllegalArgumentException (Trailing comma) which is then swallowed by the getHandler code in class Project.
6. As to the parsing, there is a consistency issue here. While a trailing comma is allowed in several commands like for example `-buildpath`:
```
# We end with ,\ to be able to easly add or remove lines with cut & paste
-buildpath: \
    ${bundles.junit},\
    ${bundles.jetty.client},\
    ${bundles.jetty.server},\
```
it is obviously not allowed in other commands like `-runproperties`:
```
# Will cause the described error
-runproperties: key=value, \
    key2=value2, \
    key3=value3, \
```
It would be nice if things where more consistent so that results may be more predictable.

**Comment by JanMosigItemis** [comment]
Thanks for the quick reaction. With which version will this be released?

**Comment by bjhargrave** [comment]
In 4.2. Thanks for the detailed problem report!
