### ISSUE TITLE
Failure on `@org.osgi.annotation.bundle.Capability.uses`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2365]
When applying the uses attribute on the `@org.osgi.annotation.bundle.Capability` annotation:

```
@org.osgi.annotation.bundle.Capability(
    uses = Foo.class
)
```

 the result is an error as follows:
```
[INFO] --- bnd-maven-plugin:4.0.0-SNAPSHOT:bnd-process (bnd-process) @ org.apache.aries.cdi.extender ---
[ERROR] /home/rotty/projects/aries/cdi/cdi-extender/bnd.bnd [0:0]: Exception: java.lang.IllegalArgumentException: No conversion found for class aQute.bnd.osgi.Descriptors$ConcreteRef to java.lang.Class<?>
    at aQute.lib.converter.Converter.error(Converter.java:515)
    at aQute.lib.converter.Converter.convert(Converter.java:329)
    at aQute.lib.converter.Converter.array(Converter.java:444)
    at aQute.lib.converter.Converter.convert(Converter.java:145)
    at aQute.lib.converter.Converter$1.invoke(Converter.java:563)
    at com.sun.proxy.$Proxy33.uses(Unknown Source)
    at aQute.bnd.osgi.AnnotationHeaders.doCapability(AnnotationHeaders.java:719)
    at aQute.bnd.osgi.AnnotationHeaders.annotation(AnnotationHeaders.java:238)
    at aQute.bnd.osgi.ClassDataCollectors$Collectors.annotation(ClassDataCollectors.java:138)
    at aQute.bnd.osgi.Clazz.doAnnotations(Clazz.java:1555)
    at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:1034)
    at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:1010)
    at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:818)
    at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:553)
    at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:538)
    at aQute.bnd.osgi.ClassDataCollectors.parse(ClassDataCollectors.java:32)
    at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:248)
    at aQute.bnd.osgi.Builder.analyze(Builder.java:397)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:798)
    at aQute.bnd.osgi.Builder.build(Builder.java:109)
    at aQute.bnd.maven.plugin.BndMavenPlugin.execute(BndMavenPlugin.java:276)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by bjhargrave** [comment]
Bnd’s handling of annotation elements which return `Class` or `Class[]` need to avoid directly calling the element since the converter has no way to construct arbitrary `Class` objects from the bundle being built.
