### ISSUE TITLE
Windows: IOException when trying to move a temp file to another drive

### ISSUE THREAD

**Issue by seanbright** [bndtools/bnd#2401]
Selecting the "Add Compile Dependencies" menu option on an artifact (in this case `hibernate-osgi`) in the Repositories View of Bndtools causes the following exception to be thrown:

```
java.nio.file.AccessDeniedException: C:\Users\osgiguy\AppData\Local\Temp\index734292428195435347.tmp -> D:\Projects\foobar\cnf\central.maven
    at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
    at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
    at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
    at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
    at java.nio.file.Files.move(Unknown Source)
    at aQute.bnd.repository.maven.provider.IndexFile.saveIndexFile(IndexFile.java:389)
    at aQute.bnd.repository.maven.provider.IndexFile.add(IndexFile.java:129)
    at aQute.bnd.repository.maven.provider.RepoActions.addDependency(RepoActions.java:192)
    at aQute.bnd.repository.maven.provider.RepoActions.access$100(RepoActions.java:21)
    at aQute.bnd.repository.maven.provider.RepoActions$4.run(RepoActions.java:76)
    at bndtools.views.repository.RepositoriesView$17$1$1.run(RepositoriesView.java:844)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Afterwards, `central.maven` no longer exists. The repository configuration is:

```
-plugin.1.Central: \
    aQute.bnd.repository.maven.provider.MavenBndRepository;\
        releaseUrl=https://repo.maven.apache.org/maven2/;\
        index=${.}/central.maven;\
        name="Central"
```

While this occurs in bndtools, the bug appears to be in bnd.

**Comment by seanbright** [comment]
After some testing, moving files across volumes does not appear to be the problem. If the file `central.maven` is open in Eclipse, the move fails because the file is locked. If the file is not open, everything works as expected.

One potential solution is to write directly to the index file without first writing to a temp file.

**Comment by seanbright** [comment]
https://github.com/bndtools/bnd/issues/2401#issuecomment-377971817
