### ISSUE TITLE
Gradle 5.0 deprecation warning

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#2439]
**Is it fixed right now?**

My build using your class is a reason of following warning:

`sh gradlew jar -Dorg.gradle.warning.mode=all --warning-mode=all --rerun-tasks -S -i`

```
  Executed with '--rerun-tasks'.
Do not cast FileCollection to File[]. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at org.gradle.api.internal.file.AbstractFileCollection.asType(AbstractFileCollection.java:167)
        at sun.reflect.GeneratedMethodAccessor987.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:913)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:904)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:591)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure6_closure7.doCall(BundleTaskConvention.groovy:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

I hope that it will be fixed within 4.0.0

**Comment by pun-ky** [comment]
When it will become available / be released and deployed on Maven Central? The latest version on it is still 3.5.0... Hope using 4.0.0 soon

**Comment by timothyjward** [comment]
When did you last look? 4.0.0 was announced and released to Maven Central about 12 hours ago.

**Comment by pun-ky** [comment]
Still only 3.5.0 available here: https://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd.gradle

**Comment by bjhargrave** [comment]
https://repo.maven.apache.org/maven2/biz/aQute/bnd/biz.aQute.bnd.gradle/4.0.0/biz.aQute.bnd.gradle-4.0.0.jar

http://search.maven.org/#artifactdetails%7Cbiz.aQute.bnd%7Cbiz.aQute.bnd.gradle%7C4.0.0%7Cjar
