### ISSUE TITLE
[bnd 4.0.0] NPE building OSGi enRoute

### ISSUE THREAD

**Issue by cdealti** [bndtools/bnd#2474]
I'm getting this building the OSGi enRoute [1] quickstart.
Full debug [Maven logs](https://github.com/bndtools/bnd/files/2105026/osgi.enroute.log.zip) are attached. I'm also getting the same error in Eclipse with Bndtools 4.0.0 using a minimal project of mine.
This happens with Maven 3.3.9 and 3.5.0 on two different Macs. In this specific case I was using Mac OS Sierra 10.12.6 and Oracle Java SE 8u144.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] quickstart ......................................... SUCCESS [  0.004 s]
[INFO] rest ............................................... SUCCESS [  5.787 s]
[INFO] app ................................................ FAILURE [  5.219 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.308 s
[INFO] Finished at: 2018-06-15T08:35:44+02:00
[INFO] Final Memory: 25M/254M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0:export (default) on project app: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0:export (default) on project app: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:111)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at aQute.bnd.repository.osgi.OSGiIndex.<init>(OSGiIndex.java:49)
	at aQute.bnd.repository.osgi.OSGiRepository.getIndex(OSGiRepository.java:155)
	at aQute.bnd.repository.osgi.OSGiRepository.getIndex(OSGiRepository.java:106)
	at aQute.bnd.repository.osgi.OSGiRepository.prepare(OSGiRepository.java:297)
	at aQute.bnd.build.Workspace.getRepositories(Workspace.java:559)
	at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:135)
	at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:108)
	... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :app
```

[1] https://enroute.osgi.org/tutorial/020-tutorial_qs.html

**Comment by bjhargrave** [comment]
I cannot reproduce this. I made a fresh clone of https://github.com/osgi/osgi.enroute and it builds fine.

```
$ mvn --version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.5", arch: "x86_64", family: "mac"
```

I suspect you may have an issue with your maven configuration:

```
[DEBUG] Reading global settings from /usr/local/apache-maven-3.5.0/conf/settings.xml
[DEBUG] Reading user settings from /Users/cristiano.dealti/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/local/apache-maven-3.5.0/conf/toolchains.xml
[DEBUG] Reading user toolchains from /Users/cristiano.dealti/.m2/toolchains.xml
[DEBUG] Using local repository at /Users/cristiano.dealti/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/cristiano.dealti/.m2/repository
[DEBUG] Failed to decrypt password for server aws.amazon.com: org.sonatype.plexus.components.cipher.PlexusCipherException: javax.crypto.BadPaddingException: Given final block not properly padded
```

Your debug log includes:
```
[DEBUG] Reported exception
javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:989)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:845)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at aQute.lib.mavenpasswordobfuscator.MavenPasswordObfuscator.decrypt(MavenPasswordObfuscator.java:49)
	at aQute.lib.mavenpasswordobfuscator.MavenPasswordObfuscator.decrypt(MavenPasswordObfuscator.java:66)
	at aQute.bnd.connection.settings.ConnectionSettings.parse(ConnectionSettings.java:366)
	at aQute.bnd.connection.settings.ConnectionSettings.readSettings(ConnectionSettings.java:80)
	at aQute.bnd.build.Workspace.setTypeSpecificPlugins(Workspace.java:628)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:508)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:460)
	at aQute.bnd.build.Workspace.getRepositories(Workspace.java:556)
	at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:135)
	at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:108)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[DEBUG] Trying pre-plugin aQute.bnd.repository.osgi.OSGiRepository
```

This would indicate you have a maven master password in `~/.m2/settings-security.xml` which is causing a problem. Bnd is failing to decrypt the server credentials in settings.xml.

**Comment by cdealti** [comment]
I do have a master password in `~/.m2/settings-security.xml` and renaming it to something else fixes the problem. Thanks!
Now, I can live with this but it has never caused issues with Maven in the last five years.

Is this a bnd specific issue?

**Comment by bjhargrave** [comment]
> Is this a bnd specific issue?

Bnd does not use Maven libraries and has its own code to process the settings.

I am guessing you have long had (non-fatal) issues since your debug output includes this from `mvn`: 

```
[DEBUG] Failed to decrypt password for server aws.amazon.com: org.sonatype.plexus.components.cipher.PlexusCipherException: javax.crypto.BadPaddingException: Given final block not properly padded
```
which is the same underlying BadPaddingException as in Bnd's code.

That said, Bnd should probably handle the bad password better. I will make a PR to log the exception rather then let it be thrown.
