### ISSUE TITLE
Importing Existing Workspace May Yield JCE Exceptions

### ISSUE THREAD

**Issue by JanMosigItemis** [bndtools/bnd#2511]
**Environment**  
* [Eclipse Photon June 2018 (4.8.0) 64bit for Java developers](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/photon/R/eclipse-java-photon-R-win32-x86_64.zip)
* Bndtools 3.5.0.REL-20170929-190052-ga0d7a6b
* Groovy Compiler 2.4 3.0.0.xx-201806290029-e48
* Groovy-Eclipse M2E integration 3.0.0.xx-201806290029-e48
* JDK 1.8.0_172-b11 (64 bit), unlimited strength crypto is activated.
* Microsoft Windows [Version 10.0.17134.112] (also verified for **.165)

**Observed Problem**  
When I import an existing bnd workspace into an Eclipse workspace that does already contain other projects, the bnd import fails with the following error:
![image](https://user-images.githubusercontent.com/16935994/42230643-c7afae82-7ee9-11e8-9aef-88ccbd8c1d8e.png)

```java
javax.net.ssl.SSLException: java.lang.RuntimeException: PRF failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at aQute.bnd.http.HttpClient.doConnect(HttpClient.java:496)
	at aQute.bnd.http.HttpClient.access$100(HttpClient.java:67)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:314)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:311)
	at aQute.bnd.http.HttpClient.connectWithProxy(HttpClient.java:404)
	at aQute.bnd.http.HttpClient.send0(HttpClient.java:311)
	at aQute.bnd.http.HttpClient.send(HttpClient.java:144)
	at aQute.bnd.http.HttpRequest.go(HttpRequest.java:187)
	at aQute.bnd.http.HttpClient.connect(HttpClient.java:123)
	at aQute.bnd.deployer.repository.CachingUriResourceHandle.request(CachingUriResourceHandle.java:195)
	at aQute.bnd.deployer.repository.AbstractIndexedRepo.init(AbstractIndexedRepo.java:256)
	at aQute.bnd.deployer.repository.AbstractIndexedRepo.init(AbstractIndexedRepo.java:171)
	at aQute.bnd.deployer.repository.AbstractIndexedRepo.versions(AbstractIndexedRepo.java:408)
	at aQute.bnd.build.Project.getBundle(Project.java:1150)
	at aQute.bnd.build.Project.getBundles(Project.java:599)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:508)
	at aQute.bnd.build.Project.prepare(Project.java:362)
	at aQute.bnd.build.Project.getBuildpath(Project.java:799)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateProjectClasspath(BndContainerInitializer.java:290)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.access$000(BndContainerInitializer.java:196)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater$1.call(BndContainerInitializer.java:238)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater$1.call(BndContainerInitializer.java:235)
	at bndtools.central.Central.bndCall(Central.java:612)
	at bndtools.central.Central.bndCall(Central.java:576)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:235)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:121)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:166)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:55)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.RuntimeException: PRF failed
	at sun.security.ssl.HandshakeMessage$Finished.getFinished(HandshakeMessage.java:1990)
	at sun.security.ssl.HandshakeMessage$Finished.<init>(HandshakeMessage.java:1896)
	at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1258)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1178)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	... 37 more
Caused by: java.security.NoSuchAlgorithmException: SunTls12Prf KeyGenerator not available
	at javax.crypto.KeyGenerator.<init>(KeyGenerator.java:169)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:223)
	at sun.security.ssl.JsseJce.getKeyGenerator(JsseJce.java:251)
	at sun.security.ssl.HandshakeMessage$Finished.getFinished(HandshakeMessage.java:1979)
	... 46 more
```
On rare occasions I did get a `NoClassDefFoundError: sun/security/ec/ECPrivateKeyImpl` instead. I could only reliably reproduce when the cnf/build.bnd contained a reference to the Bndtools-Hub under `https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz`.

What happens after the errors appear does seem to depend on which kind of projects exist in your Eclipse workspace and in the imported bnd workspace. It ranges from **import not possible at all** over **cnf folder only is imported** to **Subsequent connections to https sources (e. g. JavaDoc) do also fail**.

Once the error showed up, it is reproducible by reloading the cnf/build.bnd file.

The error does not pop up if the workspace is imported before any other project. Seems like some sort of race condition.

I could also reproduce on Oxygen 3a, so I don't think this is a Photon related problem.

**How To Reproduce**  
I have prepared a little repo that contains code with which I can reproduce the problem on my machine: https://github.com/JanMosigItemis/bnd.prf

* Clone the repo.
* Fire up Photon (bnd and groovy plugins installed) and select a new empty workspace.
* Chose `Import existing maven project` and select `bnd.prf.test`.
* Wait until the workspace has been build.
* Chose `Import existing bnd workspace` and select `bnd.prf.workspace`.
* **Expected result:** The described errors pop up. The IDE continues to behave weird, e. g. when trying to access JavaDoc of JDK classes by hovering over appropriate code with the mouse or by accessing the class with F3.

**Why is this bad?**
Well, the IDE is left in a rather unpredictable state and the import does not work at all or only half way through, making it hard for new colleagues to checkout projects and start working.

**Comment by bjhargrave** [comment]
This looks like an issue with an SSL connection to github. Not a Bnd issue _per se_. Also, the current version of Bndtools is 4.0, so you might want to update to that.

Github recently changed the SSL protocols/algorithms supported: https://githubengineering.com/crypto-removal-notice/.

**Comment by JanMosigItemis** [comment]
Thanks for the hint. I will try migrating our build to 4.0.0 and see how this goes. 

FYI: http://bndtools.org/installation.html#nonstandard_versions states that 3.5.0 is the current version. You may want to update this page.

**Comment by JanMosigItemis** [comment]
Well, I migrated our workspace to 4.0.0 and the problem persists. + In some rare cases I now get a ConcurrentModificationException when importing it into the IDE.

When building on the command line (gradle+bnd plugin), no such errors ever occur and the downloads from github and the like are running just fine.

**Comment by bjhargrave** [comment]
What version of Java is Eclipse running under? Look at the configuration under installation details in the about eclipse menu.

**Comment by JanMosigItemis** [comment]
It says: `-vm
C:\Program Files\Java\jdk8\bin\..\jre\bin\server\jvm.dll`

Which is my 1.8.0_172-b11 (64 bit) installation as described in the OP.

**Comment by bjhargrave** [comment]
Not sure what to tell you. The bnd code is the same whether you are in Bndtools/Eclipse or Gradle (assuming you are using the same Bnd/Bndtools versions for both).

**Comment by JanMosigItemis** [comment]
I am afraid, but I just tested it on my private machine, which except for a fresh photon + bnd + groovy and JDK8 and up to date Windows 10 does not have anything in common with my development machine (software and hardware).

The error is reproducible there as well. With bnd 3.5.0 it is as described, with 4.0.0 the import works but the error pops up a few minutes later when bnd tries to update cnf/cache. Looks like this is at not caused by my development machine's setup.

**Comment by bjhargrave** [comment]
Can you provide complete directions on how to reproduce? Including a small github repo for the workspace to import? Thanks.

If this is a Windows 10 issue, I don't have a Windows system to test it out.

**Comment by JanMosigItemis** [comment]
It is all linked in the OP.

**Comment by bjhargrave** [comment]
> How To Reproduce
> I have prepared a little repo that contains code with which I can reproduce the problem on my machine: https://github.com/JanMosigItemis/bnd.prf

That workspace uses the old FixedIndexRepo and the old JPM repo which were both removed in Bnd 4.0. So there is no way to use this workspace on the latest Bndtools and attempt to reproduce the issue.

You should update to replace FixedIndexRepo with OSGiRepository and JPM with either MavenBndRepository or BndPomRepository.

**Comment by JanMosigItemis** [comment]
Please read my comments. There exists a branch called "bnd4" which contains an example for bnd 4.0.0.

**Comment by JanMosigItemis** [comment]
I have just encountered this problem with some non bnd build as well. Chances are pretty good that this is no bnd but some sort of JDK issue (and / or with my installation of the JDK). Closing this bug.

**Comment by pkriens** [comment]
Thanks, appreciated keeping us informed
