### ISSUE TITLE
NPE on bnd info in the Root Workspace Directory

### ISSUE THREAD

**Issue by dstivanov** [bndtools/bnd#2653]
Hello,

I found the following bug when using BND from command line:

**Steps to reproduce**
1) Navigate to the root directory of the BND workspace;
2) Execute `bnd inf` command
3) The following exception is logged on the console:
```
Errors
000: Exception: java.lang.NullPointerException
        at aQute.bnd.osgi.Processor.error(Processor.java:355)
        at aQute.libg.reporter.ReporterMessages$1.invoke(ReporterMessages.java:134)
        at com.sun.proxy.$Proxy0.NoProject(Unknown Source)
        at aQute.bnd.main.bnd._info(bnd.java:3031)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at aQute.lib.getopt.CommandLine.execute(CommandLine.java:150)
        at aQute.bnd.main.bnd._bnd(bnd.java:444)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at aQute.lib.getopt.CommandLine.execute(CommandLine.java:150)
        at aQute.bnd.main.bnd.start(bnd.java:292)
        at aQute.bnd.main.bnd.main(bnd.java:269)

001: null
```

**bnd version**: `4.1.0.201809260717-SNAPSHOT`
**java version**: `1.8.0_181-b13`
**OS**: `Microsoft Windows 7 Enterprise, version 6.1 (build 7601, Service Pack 1)`
G**it-Descriptor**: `4.1.0.DEV-417-g1a2bf2762`
**Git-SHA**: `1a2bf276224aa2c6e676a2c8b72cf8fe60a99058`

**Comment by pkriens** [comment]
Fixed in #2654
