### ISSUE TITLE
SSL errors when building with Java 11

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2710]
When building with Java 11 bnd fails with the following errors (note this is when using the gradle-5.0-rc-1 which makes all the other errors go away, only these remain)

```
> Task :biz.aQute.repository:test

aQute.bnd.deployer.http.HttpConnectorTest > testConnectWithUserPassHTTPS FAILED
    javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
        at aQute.bnd.deployer.http.HttpBasicAuthURLConnector.connectTagged(HttpBasicAuthURLConnector.java:178)
        at aQute.bnd.deployer.http.HttpBasicAuthURLConnector.connectTagged(HttpBasicAuthURLConnector.java:147)
        at aQute.bnd.deployer.http.HttpBasicAuthURLConnector.connect(HttpBasicAuthURLConnector.java:126)
        at aQute.bnd.deployer.http.HttpConnectorTest.testConnectWithUserPassHTTPS(HttpConnectorTest.java:262)

        Caused by:
        java.io.EOFException: SSL peer shut down incorrectly
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
            ... 9 more

aQute.bnd.deployer.http.HttpConnectorTest > testConnectHTTPS FAILED
    javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:90)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:64)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:59)
        at aQute.bnd.deployer.http.DefaultURLConnector.connect(DefaultURLConnector.java:43)
        at aQute.bnd.deployer.http.HttpConnectorTest.testConnectHTTPS(HttpConnectorTest.java:166)

        Caused by:
        java.io.EOFException: SSL peer shut down incorrectly
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
            ... 10 more

aQute.bnd.deployer.http.HttpConnectorTest > testConnectWithWrongUserPassHTTPS FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at junit.framework.TestCase.assertTrue(TestCase.java:201)
        at aQute.bnd.deployer.http.HttpConnectorTest.testConnectWithWrongUserPassHTTPS(HttpConnectorTest.java:295)

aQute.bnd.deployer.http.HttpConnectorTest > testConnectTaggedHTTPS FAILED
    javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:90)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:64)
        at aQute.bnd.deployer.http.DefaultURLConnector.connectTagged(DefaultURLConnector.java:59)
        at aQute.bnd.deployer.http.HttpConnectorTest.testConnectTaggedHTTPS(HttpConnectorTest.java:192)

        Caused by:
        java.io.EOFException: SSL peer shut down incorrectly
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
            ... 9 more
```

**Comment by bjhargrave** [comment]
I mentioned this to @pkriens in Ludwigsburg and asked him to investigate.

**Comment by pkriens** [comment]
I've removed jetty and the tests and objects being tested are deprecated. Everywhere the old classes were used I now use Http Client.

This is not 100% backward compatible but I gave up finding a way. Main problem was that the semantics were not compatible. We should make sure that users update their communication settings if they use LocalIndexedRepository and set a user id/password.

**Comment by bjhargrave** [comment]
OK, so we will need to make sure to document in the changes doc. Perhaps even the LocalIndexedRepository code can put out a useful error message if old settings are used advising the user how to reconfigure for HttpClient?
