### ISSUE TITLE
Enable handling OCD from external bundle

### ISSUE THREAD

**Issue by Zymus** [bndtools/bnd#2770]
I have two bundles, `species-config` and `species-provider`.

I want the `ObjectClassDefinition` to be in its own bundle, to enable different implementations of the component type.

Inside `species-config` I have the following (Kotlin) annotation

```kotlin
package hummingbird.species.config

import org.osgi.service.metatype.annotations.ObjectClassDefinition

@ObjectClassDefinition
annotation class SpeciesConfig (

	val species_name: String = "species-name.default"
)
```

Inside `species-provider` I have the component

```kotlin
package hummingbird.service.species

import hummingbird.species.config.SpeciesConfig
import org.osgi.service.component.annotations.Component
import org.osgi.service.component.annotations.ConfigurationPolicy
import org.osgi.service.metatype.annotations.Designate

@Component(
	configurationPolicy = ConfigurationPolicy.REQUIRE,
	service = [Species::class]
)
@Designate(
	factory = true,
	ocd = SpeciesConfig::class
)
class Species {

	fun activate(config: SpeciesConfig) {
		System.out.println("Species.activate config: $config")
		System.out.flush()
	}
}
```

I want to enable people to use different components if they want, for example

```kotlin
@Component(
	configurationPolicy = ConfigurationPolicy.REQUIRE,
	service = [OtherSpecies::class],
        property = [
            "some.property=foo"
        ]
)
@Designate(
	factory = true,
	ocd = SpeciesConfig::class
)
class OtherSpecies {

	fun activate(config: SpeciesConfig) {
            // do something else
	}
}
```

When I try to do this currently, I get the following build error

> error  : DS Component hummingbird.service.species.Species specifies ocd class hummingbird.species.config.SpeciesConfig which cannot be found; known classes []

`species-config` `bnd.bnd` file:
```
javac.source: 1.8
javac.target: 1.8

Bundle-Version: 0.0.0+${tstamp}

-buildpath: \
	osgi.annotation; version="[6.0, 7.0)",\
	osgi.cmpn; version="[6.0, 7.0)",\
	${jetbrains-annotations},\
	${kotlin}

-testpath: \
	${junit}

Import-Package: \
	kotlin.*; version="[1.3, 2.0)"

Export-Package: \
	hummingbird.species.config
```

`species-provider` `bnd.bnd` file:
```
javac.source: 1.8
javac.target: 1.8

Bundle-Version: 0.0.0+${tstamp}

-buildpath: \
	species-config; version="[0.0, 1.0)"

-testpath: \
	${junit}

Import-Package: \
	hummingbird.species.config; version="[0.0, 1.0)",\
	kotlin.*; version="[1.3, 2.0)"

Export-Package: \
	hummingbird.service.species
```

Built `species-config` `MANIFEST.MF`
```
Manifest-Version: 1.0
Bnd-LastModified: 1543972632472
Bundle-ManifestVersion: 2
Bundle-Name: species-config
Bundle-SymbolicName: species-config
Bundle-Version: 0.0.0.201812050117
Created-By: 1.8.0_131 (Oracle Corporation)
Export-Package: hummingbird.species.config;version="0.0";uses:=kotlin
Import-Package: kotlin;version="[1.3,2.0)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.1.0.201810181252
```

`species-config` `hummingbird.species.config.SpeciesConfig.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.2.0" localization="OSGI-INF/l10n/hummingbird.species.config.SpeciesConfig">
  <OCD id="hummingbird.species.config.SpeciesConfig" name="Hummingbird species config species config" description="">
    <AD id="species.name" type="String" name="Species name" default="species.name.default"/>
  </OCD>
</metatype:MetaData>
```

Build output
```
$ ./gradlew --stacktrace clean build
> Task :species-config:clean
> Task :species-provider:clean
> Task :species-provider-bundled:clean UP-TO-DATE
> Task :species-config:discoverMainScriptsExtensions
> Task :species-config:compileKotlin
> Task :species-config:compileJava
> Task :species-config:processResources NO-SOURCE
> Task :species-config:classes
> Task :species-config:inspectClassesForKotlinIC
> Task :species-config:jar
> Task :species-config:assemble
> Task :species-config:discoverTestScriptsExtensions
> Task :species-config:compileTestKotlin NO-SOURCE
> Task :species-config:compileTestJava NO-SOURCE
> Task :species-config:processTestResources NO-SOURCE
> Task :species-config:testClasses UP-TO-DATE
> Task :species-config:test NO-SOURCE
> Task :species-config:check UP-TO-DATE
> Task :species-config:build
> Task :species-provider:discoverMainScriptsExtensions
> Task :species-provider:compileKotlin
> Task :species-provider:compileJava
> Task :species-provider:processResources NO-SOURCE
> Task :species-provider:classes
> Task :species-provider:inspectClassesForKotlinIC

> Task :species-provider:jar FAILED
error  : DS Component hummingbird.service.species.Species specifies ocd class hummingbird.species.config.SpeciesConfig which cannot be found; known classes []

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':species-provider:jar'.
> Bundle species-provider.jar has errors

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':species-provider:jar'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
        at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Bundle species-provider.jar has errors
        at aQute.bnd.gradle.BundleTaskConvention.failBuild(BundleTaskConvention.groovy:310)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure6$_closure7.doCall(BundleTaskConvention.groovy:294)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure6.doCall(BundleTaskConvention.groovy:200)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:130)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:575)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:91)
        at org.gradle.util.Configurable$configure.call(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention.buildBundle(BundleTaskConvention.groovy:195)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:334)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
        at org.gradle.api.tasks.bundling.Jar_Decorated.invokeMethod(Unknown Source)
        at aQute.bnd.gradle.BndBuilderPlugin$_apply_closure1$_closure2$_closure6.doCall(BndBuilderPlugin.groovy:56)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:647)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:620)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
        ... 35 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
14 actionable tasks: 13 executed, 1 up-to-date
```

MVCE can be found at https://github.com/Zymus/bnd-example

**Comment by djencks** [comment]
I don’t know Kotlin.  Is SpeciesConfig a public class?

I think you might be able to narrow down where the problem is by seeing if this works if the annotation SpeciesConfig is in the same bundle as the DS component.  If not, there’s something wrong with your annotations. If it does work, there’s probably something wrong with how you tell bnd which packages are needed to analyze the DS component…. or maybe a bug in bnd.  I’d expect showing your bnd config would be necessary to get any advice on why the 2-bundle setup doesn’t work.

david jencks

**Comment by Zymus** [comment]
@djencks Yes, `SpeciesConfig` is a public class; lack of a modifier defaults to `public` in Kotlin (I can post a reproducible example in Java if necessary).

If the annotation is in the same bundle as the DS component, it works just fine. I've edited the OP with the bnd files for each, as well as posting an MVCE at https://github.com/Zymus/bnd-example

**Comment by Zymus** [comment]
I think that I should note that this is using Gradle Kotlin DSL, and non-workspace bnd.

**Comment by bjhargrave** [comment]
You are using Bnd/Gradle in non-Bnd workspace model where Gradle is solely in charge of the compile path. So `-buildpath` in the bnd file is completely ignored. You need to make sure the necessary artifacts are configured in the gradle build so that the Bnd Builder can see them.

**Comment by Zymus** [comment]
@bjhargrave I think there is more going on here.

If you look at the `build.gradle.kts` file in the `species-provider` folder in the github link I posted above, you'll see that I am in fact adding the `species-config` project as a dependency.

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
	val bndVersion = "4.1.0"
	val kotlinVersion = "1.3.10"

	repositories {
		mavenCentral()
	}

	dependencies {
		classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")

		classpath("biz.aQute.bnd:biz.aQute.bnd.gradle:$bndVersion")
	}
}

plugins {
	idea
	java
	id("biz.aQute.bnd.builder") version "4.1.0"
	kotlin("jvm") version "1.3.10"
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(project(":species-config"))
	implementation(kotlin("stdlib-jdk8"))
	implementation("org.osgi:osgi.annotation:6.0.1")
	implementation("org.osgi:osgi.cmpn:6.0.0")
}

val compileKotlin: KotlinCompile by tasks

compileKotlin.kotlinOptions {
	jvmTarget = "1.8"

}
```

**Comment by Zymus** [comment]
@bjhargrave I found the Using Kotlin with the Bnd Gradle Plugin for Workspace Builds page on the wiki; do I have to use the same code for a non-workspace build as well?

```
bnd.project.getDependson()*.getName().each { dependency ->
    compileKotlin.dependsOn(":${dependency}:assemble")
}```

**Comment by Zymus** [comment]
Also, I know that the `species-provider` is able to use the `species-config` project as a dependency, and use the `SpeciesConfig` class, as this builds just fine

```kotlin
package hummingbird.service.species

import hummingbird.species.config.SpeciesConfig
import org.osgi.service.component.annotations.Component
import org.osgi.service.component.annotations.ConfigurationPolicy
import org.osgi.service.metatype.annotations.Designate

@Component(
		configurationPolicy = ConfigurationPolicy.REQUIRE,
		service = [Species::class]
)
/*@Designate(
	factory = true,
	ocd = SpeciesConfig::class
)*/
class Species {

	fun activate(config: SpeciesConfig) {
		System.out.println("activating Species with $config")
	}
}
```

**Comment by rotty3000** [comment]
If I'm looking at this correctly, you've created a dependency that bnd
gradle plugin doesn't know about: `implementation`.

I think you need to feed this configuration into bnd's classpath.

See
https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#classpath

**Comment by bjhargrave** [comment]
I think the issue here is that the Designate annotation is to be used to

> Generate a Designate element in the Meta Type Resource for an ObjectClassDefinition using the annotated Declarative Services component.

Since SpeciesConfig (annotated with ObjectClassDefinition) is not in the bundle of the component annotated with Designate, then there is no ObjectClassDefinition in the component bundle which would result in a meta type resource into which a `Designate` element can be generated.

That is, the Designate annotation affects the generated meta type resource for the object class definition. Since the is no such resource in the component bundle, we get the error.

Since SpeciesConfig is simple annotation, the best solution is to just `-includepackage` it's package into any component bundle that needs it. Then it is in the component bundle as a private package. It can be used at runtime by SCR since it synthesizes the instance of SpeciesConfig passed to the activate method and it does not need to be a shared (imported) package.

**Comment by Zymus** [comment]
@bjhargrave Using the `-includepackage` works perfectly. You mentioned that
> Since SpeciesConfig is simple annotation, the best solution is to just -includepackage it's package into any component bundle that needs it. 

Is this advice only applicable for simple annotations, or is there some level where this becomes unwieldy?

**Comment by bjhargrave** [comment]
> Is this advice only applicable for simple annotations, or is there some level where this becomes unwieldy?

Assuming the class (annotation) is only used as an implementation detail and not share in your API, then it does not matter that your bundle will have its own private copy of the annotation. SCR doesn't care. It would only matter if you used the annotation type as a runtime visible method parameter, return type or field type.
