### ISSUE TITLE
Changing branches results in "failed to set build order"

### ISSUE THREAD

**Issue by ViToni** [bndtools/bnd#2777]
Using 4.2.0-DEV-something I get errors like theses after switching branches. The only solution is to close and reopen the respective project. (Refereshing does not help).

org.eclipse.core.internal.resources.ResourceException(/my.project.name)[274]: java.lang.Exception: Could not set the project description for 'my.project.name' because the project description file (.project) is out of sync with the file system.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1262)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1296)
	at org.bndtools.builder.BndtoolsBuilder.setBuildOrder(BndtoolsBuilder.java:369)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:166)
	at bndtools.central.Central.bndCall(Central.java:665)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:124)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by pkriens** [comment]
This bug indicates that Eclipse is not in sync with the file system. Fixing this specific error will likely cause other errors to pop later. It will be necessary to do a workspace refresh.
