### ISSUE TITLE
[m2e integration] bnd editor showing wrong set of repos

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2782]
Setup. An eclipse workspace contains:
- a cnf directory from a bndtools workspace
- a maven osgi project loaded using m2e
- the maven project contains a *.bnd file
- opening the bnd file from the maven project in the bnd editor incorrectly shows all the repositories from the bndtools workspace even though the bnd file should be considered standalone.

Furthermore, clicking the checkbox setting the standalone flag, and then attempting to save, causes an error:
```
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at aQute.bnd.osgi.Jar.buildFromZip(Jar.java:173)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:90)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:116)
	at bndtools.m2e.BndConfigurator$MavenProjectInfo.<init>(BndConfigurator.java:67)
	at bndtools.m2e.BndConfigurator$2.call(BndConfigurator.java:186)
	at bndtools.m2e.BndConfigurator$2.call(BndConfigurator.java:167)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at bndtools.m2e.BndConfigurator.execJarMojo(BndConfigurator.java:167)
	at bndtools.m2e.BndConfigurator.access$000(BndConfigurator.java:50)
	at bndtools.m2e.BndConfigurator$1$1.runInWorkspace(BndConfigurator.java:115)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
.. presumbably because now there are no repos and the framework probably can't be resolved or some other details.

**Comment by bjhargrave** [comment]
Fixed by recent changes.
