### ISSUE TITLE
Unable to Run As OSGi JUnit Test when using Maven

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2792]
If I'm using the bnd-testing-maven-plugin then I don't need to use a standalone index. If the plugin is configured for it then all of my maven dependencies are made available for resolve and run by the testing plugin, so no indexes are actually needed in that mode

This is great from the command line, but the resulting bndrun cannot be run from Bndtools. The main error is about a missing launcher plugin, but additional failures occur due to the lack of a Bndtools project nature. This also causes the Run As OSGi JUnit Test... option to disappear from the right click menu of the test class.

**Comment by rotty3000** [comment]
Ok so after review, what currently works is:
- right clicking on the bndrun file linked to the `bnd-testing-maven-plugin` and then selecting `-> Run As/Debug As -> Bnd OSGi Test Launcher (Junit)`

What does NOT work is:
- selecting any nodes in the project, including the project root, then `-> Run As/Debug As -> Bnd OSGi Test Launcher (Junit)`
- selecting either packages or classes which contain tests,  then `-> Run As/Debug As -> Bnd OSGi Test Launcher (Junit)`

either of those operations lead to some form of the following error:
```
Status ERROR: bndtools.core code=0 Error initialising bnd launcher java.lang.Exception: Cannot load Bnd project for directory <project path>: no Bnd workspace found
java.lang.Exception: Cannot load Bnd project for directory <project path>: no Bnd workspace found
	at bndtools.launch.util.LaunchUtils.createRun(LaunchUtils.java:115)
	at bndtools.launch.util.LaunchUtils.createRun(LaunchUtils.java:100)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:133)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:832)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
