### ISSUE TITLE
Fails building project

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2872]
I am currently getting the following error while building one of the workspace projects (even though the project is getting built successfully)

```
Errors occurred during the build.
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
Errors running builder 'Bndtools Builder' on project 'com.amitinside.sound.provider'.
Build Error!
java.lang.NullPointerException
Build Error!
java.lang.NullPointerException
```

**Comment by amitjoy** [comment]
```
java.lang.NullPointerException
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:107)
	at org.bndtools.builder.MarkerSupport.createMarkers(MarkerSupport.java:94)
	at org.bndtools.builder.MarkerSupport.setMarkers(MarkerSupport.java:78)
	at org.bndtools.builder.BndtoolsBuilder.report(BndtoolsBuilder.java:283)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:263)
	at bndtools.central.Central.bndCall(Central.java:665)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:124)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by amitjoy** [comment]
```
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:270)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:107)
	at org.bndtools.builder.MarkerSupport.createMarkers(MarkerSupport.java:94)
	at org.bndtools.builder.MarkerSupport.setMarkers(MarkerSupport.java:78)
	at org.bndtools.builder.BndtoolsBuilder.report(BndtoolsBuilder.java:283)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:263)
	at bndtools.central.Central.bndCall(Central.java:665)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:124)
	... 12 more
```
