### ISSUE TITLE
[bndtools] `Unhandled event loop exception` if you mouseover bnd repo download log report

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2916]

**Comment by rotty3000** [comment]
Here's an image where all I did was refresh the repos, then moused over the download log entries:

![screenshot from 2019-02-04 09-49-18](https://user-images.githubusercontent.com/146764/52215515-31dd3f00-2862-11e9-8f89-77b93014386c.png)

**Comment by rotty3000** [comment]
```
java.lang.NullPointerException
	at org.eclipse.ui.internal.views.log.LogView.onMouseMove(LogView.java:1420)
	at org.eclipse.ui.internal.views.log.LogView.lambda$9(LogView.java:1276)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by gamerson** [comment]
Its weird that there is no bndtools in the stacktrace.  

Here seems to be a relevant (linux specific) bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=535741

**Comment by seanbright** [comment]
Not a bndtools bug
