### ISSUE TITLE
[bndtools] java.util.concurrent.TimeoutException: Unable to acquire bndLock

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2918]
Here's the eclipse log (and automatic thread dump) that accompanied the exception:

```
!ENTRY bndtools.core 4 0 2019-02-04 10:04:03.290
!MESSAGE Error loading repositories: Unable to acquire bndLock[bndtools.central.Central$BndLock@7509ce54[Locked by thread Worker-473: Building workspace]]; has waiters: 0
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock[bndtools.central.Central$BndLock@7509ce54[Locked by thread Worker-473: Building workspace]]; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:687)
	at bndtools.central.Central.bndCall(Central.java:645)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:30)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:25)
	at bndtools.views.repository.RepositoriesView.getRepositories(RepositoriesView.java:1103)
	at bndtools.central.RepositoriesViewRefresher$1.runInWorkspace(RepositoriesViewRefresher.java:100)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.Throwable: Thread[Worker-473: Building workspace,5,main] owns the bndLock

Full thread dump:
"Worker-787" Id=2390 TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-786" Id=2365 TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-785: Compacting resource model" Id=2364 WAITING on java.lang.Object@e2c5a27
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@e2c5a27
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:316)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:297)
	at org.eclipse.core.internal.utils.StringPoolJob.run(StringPoolJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

"Worker-784" Id=2360 TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-748" Id=2241 TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.core.internal.jobs.WorkerPool@300b5e91
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-618: Download https://download.eclipse.org/webtools/downloads/drops/R3.9.5/R-3.9.5-20180409100740/repository/plugins/org.eclipse.wst.xml.ui.source_1.1.800.v201704102213.jar" Id=1884 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at bndtools.central.JobProgress$TaskJob.run(JobProgress.java:46)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

"Worker-496: Refresh repositories" Id=1560 BLOCKED on aQute.bnd.repository.p2.provider.P2Repository@71675354 owned by "Worker-473: Building workspace" Id=1461
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index(P2Repository.java:52)
	-  blocked on aQute.bnd.repository.p2.provider.P2Repository@71675354
	at aQute.bnd.repository.p2.provider.P2Repository.refresh(P2Repository.java:121)
	at bndtools.central.Central.refreshPlugins(Central.java:481)
	at bndtools.views.repository.RepositoriesView$11$1.runInWorkspace(RepositoriesView.java:616)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

"Bnd-Processor,pool-3-thread-229" Id=1542 RUNNABLE (in native)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	-  locked java.lang.Object@42211531
	...

	Number of locked synchronizers = 2
	- java.util.concurrent.ThreadPoolExecutor$Worker@48eca4c4
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@1ae6be76

"Worker-476: Updating repositories content" Id=1474 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at bndtools.central.Central$BndLock.dumpAllThreads(Central.java:627)
	at bndtools.central.Central$BndLock.getOwnerCause(Central.java:620)
	at bndtools.central.Central.bndCall(Central.java:687)
	at bndtools.central.Central.bndCall(Central.java:645)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:30)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:25)
	...

"remotews" Id=1473 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at aQute.lib.link.Link$3.run(Link.java:289)

"Worker-473: Building workspace" Id=1461 WAITING on java.util.concurrent.CountDownLatch$Sync@546a9d4b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CountDownLatch$Sync@546a9d4b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.osgi.util.promise.DeferredPromiseImpl.getValue(DeferredPromiseImpl.java:120)
	at aQute.bnd.repository.p2.provider.P2Indexer.readRepository(P2Indexer.java:206)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@2135f2e2

"org.eclipse.jface.text.reconciler.MonoReconciler" Id=1458 TIMED_WAITING on org.eclipse.jface.text.reconciler.DirtyRegionQueue@7b509cbe
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.jface.text.reconciler.DirtyRegionQueue@7b509cbe
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:183)

"Worker-471: Decoration Calculation" Id=1456 WAITING on java.lang.Object@e2c5a27
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@e2c5a27
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:316)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:297)
	at org.eclipse.ui.internal.ide.ContentTypeDecorator.decorate(ContentTypeDecorator.java:61)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:261)
	...

"Thread-9" Id=1428 RUNNABLE (in native)
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	-  locked java.net.PlainDatagramSocketImpl@801be2
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	-  locked java.net.PlainDatagramSocketImpl@801be2
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	-  locked java.net.DatagramPacket@805e7c
	-  locked java.net.DatagramSocket@7f4a97be
	at aQute.launcher.plugin.ProjectLauncherImpl$1.run(ProjectLauncherImpl.java:184)
	at java.lang.Thread.run(Thread.java:748)

"remotews" Id=137 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at aQute.lib.link.Link$3.run(Link.java:289)

"pool-2-thread-1" Id=130 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@13db1712
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@13db1712
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Thread-8" Id=129 RUNNABLE (in native)
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	-  locked java.net.PlainDatagramSocketImpl@13845180
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	-  locked java.net.PlainDatagramSocketImpl@13845180
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	-  locked java.net.DatagramPacket@11758e32
	-  locked java.net.DatagramSocket@3a291cc5
	at aQute.launcher.plugin.ProjectLauncherImpl$1.run(ProjectLauncherImpl.java:184)
	at java.lang.Thread.run(Thread.java:748)

"JavaScript indexing" Id=111 WAITING on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@7101ef15
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@7101ef15
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.wst.jsdt.internal.core.search.processing.JobManager.run(JobManager.java:370)
	at java.lang.Thread.run(Thread.java:748)

"Takari usage stats reporter" Id=86 TIMED_WAITING on java.util.TaskQueue@40b8a8e4
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@40b8a8e4
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)

"Bnd-Processor,pool-3-thread-5" Id=58 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Bnd-Processor,pool-3-thread-4" Id=57 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Bnd-Processor,pool-3-thread-3" Id=56 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Bnd-Processor,pool-3-thread-2" Id=55 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7d01badf
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"remotews" Id=50 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at aQute.lib.link.Link$3.run(Link.java:289)

"YJP-Plugin-RequestListener" Id=49 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.yourkit.c.l$1.run(a:37)
	at java.lang.Thread.run(Thread.java:748)

"EventAdmin Async Event Dispatcher Thread" Id=38 WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@f3c5e8e
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@f3c5e8e
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Java indexing" Id=37 WAITING on org.eclipse.jdt.internal.core.search.indexing.IndexManager@71bb613b
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.jdt.internal.core.search.indexing.IndexManager@71bb613b
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:378)
	at java.lang.Thread.run(Thread.java:748)

"EMF Reference Cleaner" Id=35 WAITING on java.lang.ref.ReferenceQueue$Lock@74c10860
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@74c10860
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

"Gogo shell" Id=31 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4e69365
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4e69365
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Worker-JM" Id=28 TIMED_WAITING on java.util.ArrayList@69c36559
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.ArrayList@69c36559
	at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:62)

"SCR Component Actor" Id=27 WAITING on java.util.LinkedList@435b63e3
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.LinkedList@435b63e3
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:81)
	at java.lang.Thread.run(Thread.java:748)

"Start Level: Equinox Container: ab59d176-89af-4166-9d05-88e727b35312" Id=26 WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@3fa5e1e0
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@3fa5e1e0
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Framework Event Dispatcher: Equinox Container: ab59d176-89af-4166-9d05-88e727b35312" Id=25 WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@f6820ca
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@f6820ca
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Active Thread: Equinox Container: ab59d176-89af-4166-9d05-88e727b35312" Id=23 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7df375d3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7df375d3
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Bundle File Closer" Id=13 WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@652f55f5
	at java.lang.Object.wait(Native Method)
	-  waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@652f55f5
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@75951251
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@75951251
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@3b350259
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@3b350259
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
	at org.eclipse.swt.internal.gtk.OS.Call(Native Method)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:5478)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopIdle(WorkbenchAdvisor.java:371)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.eventLoopIdle(IDEWorkbenchAdvisor.java:961)
	at org.eclipse.ui.internal.Workbench$1.eventLoopIdle(Workbench.java:482)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1178)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	...

Owner stacktrace:
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.osgi.util.promise.DeferredPromiseImpl.getValue(DeferredPromiseImpl.java:120)
	at aQute.bnd.repository.p2.provider.P2Indexer.readRepository(P2Indexer.java:206)
	at aQute.bnd.repository.p2.provider.P2Indexer.readRepository(P2Indexer.java:145)
	at aQute.bnd.repository.p2.provider.P2Indexer.<init>(P2Indexer.java:90)
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index0(P2Repository.java:72)
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index(P2Repository.java:55)
	at aQute.bnd.repository.p2.provider.P2Repository.versions(P2Repository.java:90)
	at aQute.bnd.build.Project.getBundle(Project.java:1268)
	at aQute.bnd.build.Project.getBundles(Project.java:648)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:553)
	at aQute.bnd.build.Project.prepare(Project.java:395)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:157)
	at org.bndtools.builder.BndtoolsBuilder$$Lambda$740/288840952.call(Unknown Source)
	at bndtools.central.Central.bndCall(Central.java:676)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:124)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	... 1 more
```

**Comment by bjhargrave** [comment]
This appears to be cause by a blocked download operation. We have seen downloads from Eclipse hang lately. See #2911 where I request support for timing out HttpClient downloads.

`Worker-473: Building workspace` is building the workspace. It gets the BndLock, then prepares the project to compute the build path. Prepare consults the configured repos, one of which is a p2 repo. The p2 repo code initiates downloads and block on Promise.getValue waiting for the download Promises to complete.

`Bnd-Processor,pool-3-thread-229` is blocked on the download.

`Worker-618: Download https://download.eclipse.org/webtools/downloads/drops/R3.9.5/R-3.9.5-20180409100740/repository/plugins/org.eclipse.wst.xml.ui.source_1.1.800.v201704102213.jar` is monitoring the download.

Finally, `Worker-476: Updating repositories content` tries to get the BndLock to update the viewer. This times out because the builder thread `Worker-473: Building workspace` owns the BndLock and is blocked by a download that never completes.

#2911 should mitigate this since it will allow us to timeout downloads.

**Comment by ViToni** [comment]
I have a similar (or the same) issue where bndLock could not be aquired. Happend with a flaky connection in a hotel. The main issue is not that it happened, but that it didn't cure itself after some time and finally led to an OOM .

**Comment by pkriens** [comment]
Is this still happening? Lately the downloads seem to go much better?

**Comment by bjhargrave** [comment]
> Lately the downloads seem to go much better?

For the Bnd build, yes. Since we don't download from Eclipse servers anymore. And we also have timeout support in HttpClient now which should prevent this in general.

I would be for closing this.
