### ISSUE TITLE
Multiple NPEs when opening/using bndrun file in Maven Project

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#3036]
Seen in 4.2.0.DEV-20190212-123646-gdeab1ca:

```
java.lang.NullPointerException
	at bndtools.m2e.MavenImplicitProjectRepository.versions(MavenImplicitProjectRepository.java:108)
	at bndtools.editor.project.OSGiFrameworkContentProvider.refreshProviders(OSGiFrameworkContentProvider.java:90)
	at bndtools.editor.project.OSGiFrameworkContentProvider.access$100(OSGiFrameworkContentProvider.java:36)
	at bndtools.editor.project.OSGiFrameworkContentProvider$2.run(OSGiFrameworkContentProvider.java:136)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

and 

```
java.lang.NullPointerException
	at bndtools.m2e.MavenImplicitProjectRepository.list(MavenImplicitProjectRepository.java:80)
	at bndtools.model.repo.RepositoryTreeContentProvider$1.run(RepositoryTreeContentProvider.java:294)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

Bndrun file:

```
-standalone: target/index.xml

-resolve.effective: active

-runfw: org.apache.felix.framework
-runee: JavaSE-1.8

-runvm: -ea,\
 -Dorg.slf4j.simpleLogger.defaultLogLevel=debug,\
 -Dlogback.configurationFile=${.}/src/test/resources/logback/logback-test.xml

-runproperties: \
    posh.home=${.}/src/test/resources/,\
    test.resources=${.}/src/test/resources/

-runsystempackages: sun.reflect

-runrequires: bnd.identity;id='com.paremus.ui.rest.net.test'
```

I will now try updating to the latest RC, but I wanted to capture the stack traces while I had them.

**Comment by timothyjward** [comment]
> I will now try updating to the latest RC, but I wanted to capture the stack traces while I had them.

Still seen in 4.2.0 RC3

**Comment by timothyjward** [comment]
Another similar NPE occurs when attempting to launch:

```
java.lang.NullPointerException
	at bndtools.m2e.MavenImplicitProjectRepository.versions(MavenImplicitProjectRepository.java:108)
	at aQute.bnd.build.Project.getBundle(Project.java:1268)
	at aQute.bnd.build.Project.getBundles(Project.java:648)
	at aQute.bnd.build.Project.getHandler(Project.java:2820)
	at aQute.bnd.build.Project.getProjectTester(Project.java:2808)
	at bndtools.launch.OSGiJUnitLaunchDelegate.initialiseBndLauncher(OSGiJUnitLaunchDelegate.java:55)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:137)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:829)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by bjhargrave** [comment]
Seem like we should fix this for 4.2. @rotty3000 Can you investigate as this seems in the areas you have recently worked on?

**Comment by rotty3000** [comment]
yeah, I'll check, what's a reproducer? I kind of need more than just the bndrun. Can you point me at a maven project that has the issue?

**Comment by bjhargrave** [comment]
Both NPEs are because `fileSetRepository` is null.

**Comment by bjhargrave** [comment]
My guess is that an exception occurs in `createRepo` before `fileSetRepository` is set and the exception is just logged allowing the `MavenImplicitProjectRepository` object to be constructed in an invalid state.

**Comment by rotty3000** [comment]
I setup a project here [1] using the information I could collect from @timothyjward but I cannot reproduce. I'd need Tim to validate that I have the project setup properly to reproduce the issue.

[1] https://github.com/rotty3000/com.github.rotty3000.examples/compare/bnd3036?expand=1

**Comment by rotty3000** [comment]
I had the wrong plugin version in that example (was: 4.3.-SNAPSHOT, changed to 4.2.0-SNAPSHOT) but still not reproduced.

**Comment by rotty3000** [comment]
@timothyjward to clarify, are you using Bndtools 4.2.0-RC3 along with the project using bnd maven plugins configured with 4.1.0? Maybe that's what I'm missing.

**Comment by rotty3000** [comment]
even this configuration doesn't give me any errors :(

**Comment by bjhargrave** [comment]
> My guess is that an exception occurs in `createRepo` before `fileSetRepository` is set and the exception is just logged allowing the `MavenImplicitProjectRepository` object to be constructed in an invalid state.

In any case, the `createRepo` method needs fixing since it can leave the `MavenImplicitProjectRepository` object in an invalid state.

**Comment by rotty3000** [comment]
I've made a small change in an attempt to do what you suggest @bjhargrave but I've still not been able to reproduce.

**Comment by timothyjward** [comment]
The latest snapshot now gives a more informative error log:

```
org.apache.maven.plugin.MojoExecutionException: Could not resolve dependencies for project com.paremus.ui:com.paremus.ui.rest.net.test:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.paremus.ui:com.paremus.ui.rest.test:jar:1.0.0-SNAPSHOT, com.paremus.ui:com.paremus.ui.rest.net:jar:1.0.0-SNAPSHOT: Failure to find com.paremus.ui:com.paremus.ui.rest.test:jar:1.0.0-SNAPSHOT in https://nexus2.paremus.com/content/repositories/product-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of product-snapshots has elapsed or updates are forced
at aQute.bnd.maven.lib.resolve.DependencyResolver.resolve(DependencyResolver.java:129)
at aQute.bnd.maven.lib.resolve.DependencyResolver.resolve(DependencyResolver.java:105)
at aQute.bnd.maven.lib.resolve.DependencyResolver.getFileSetRepository(DependencyResolver.java:150)
at aQute.bnd.maven.lib.resolve.BndrunContainer.getFileSetRepository(BndrunContainer.java:209)
at bndtools.m2e.MavenImplicitProjectRepository.createRepo(MavenImplicitProjectRepository.java:169)
at bndtools.m2e.MavenImplicitProjectRepository.<init>(MavenImplicitProjectRepository.java:54)
at bndtools.m2e.MavenImplicitProjectRunListener.create(MavenImplicitProjectRunListener.java:48)
at bndtools.launch.util.LaunchUtils.createRun(LaunchUtils.java:87)
at bndtools.editor.BndEditor.loadEditModel(BndEditor.java:592)
at bndtools.editor.BndEditor.init(BndEditor.java:540)
at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)
at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:342)
...
```

The root cause is:

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.paremus.ui:com.paremus.ui.rest.test:jar:1.0.0-SNAPSHOT in https://nexus2.paremus.com/content/repositories/product-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of product-snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:233)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:208)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:563)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:481)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
```

This appears to be a failure to find a peer of the current project in the eclipse workspace.

**Comment by timothyjward** [comment]
The dependency for the peer project is "normal" and explicit
```
		<dependency>
			<groupId>com.paremus.ui</groupId>
			<artifactId>com.paremus.ui.rest.test</artifactId>
			<version>${project.version}</version>
		</dependency>
```
