### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant aQute.bnd.cdi.Discover

### ISSUE THREAD

**Issue by rakeshk15** [bndtools/bnd#3061]
Hi @njbartlett 

My build fails with following error, however, this works with v4.1.0

```
[INFO] --- bnd-maven-plugin:4.2.0:bnd-process (default) @ adeptj-modules-jaxrs-resteasy ---
[ERROR] /Users/rakesh.kumar/code/adeptj/adeptj-modules/jaxrs/resteasy/bnd.bnd [0:0]: Exception: java.lang.IllegalArgumentException: No enum constant aQute.bnd.cdi.Discover.
	at java.lang.Enum.valueOf(Enum.java:238)
	at aQute.bnd.cdi.Discover.valueOf(Discover.java:5)
	at aQute.bnd.cdi.CDIAnnotations.findDiscoveryMode(CDIAnnotations.java:295)
	at aQute.bnd.cdi.CDIAnnotations.lambda$analyzeJar$3(CDIAnnotations.java:97)
	at aQute.lib.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at aQute.bnd.cdi.CDIAnnotations.analyzeJar(CDIAnnotations.java:92)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:879)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:239)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:408)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:909)
	at aQute.bnd.osgi.Builder.build(Builder.java:118)
	at aQute.bnd.maven.plugin.BndMavenPlugin.execute(BndMavenPlugin.java:429)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[ERROR] /Users/rakesh.kumar/code/adeptj/adeptj-modules/jaxrs/resteasy/bnd.bnd [0:0]: Analyzer Plugin CDIAnnotations failed No enum constant aQute.bnd.cdi.Discover.
```

**Comment by njbartlett** [comment]
@rotty3000 Any ideas?

**Comment by rakeshk15** [comment]
basically I am embedding the RESTEasy jars in my bundle using includeresource instruction

-includeresource: resteasy-*.jar;apache-mime4j-*.jar;lib:=true

the complete bnd file can be located here - https://github.com/AdeptJ/adeptj-modules/blob/master/jaxrs/resteasy/bnd.bnd

If I remove the includeresource instruction then it is working fine.

**Comment by rotty3000** [comment]
I'm testing a fix for this.
