### ISSUE TITLE
bnd build fails on launchpad tests

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3132]
After doing a `git clean -fdx` the launchpad tests are failing.

```
> Task :biz.aQute.launchpad:test
aQute.launchpad.BundleBuilderTest > testWorkspaceOrProjectAfterParent FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: specified file /home/rotty/projects/bnd/bnd.bnd as parent for build but no such file exist
        at aQute.lib.link.Link.waitForResult(Link.java:490)
        at aQute.lib.link.Link$1.invoke(Link.java:191)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.lib.aspects.Aspects$1.lambda$new$1(Aspects.java:173)
        at aQute.lib.aspects.Aspects$1.lambda$invoke$14(Aspects.java:314)
        at aQute.lib.aspects.Aspects$1.lambda$$0(Aspects.java:165)
        at aQute.lib.aspects.Aspects$1.invoke(Aspects.java:314)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at aQute.launchpad.BundleSpecBuilder.install(BundleSpecBuilder.java:920)
        at aQute.launchpad.BundleSpecBuilder.start(BundleSpecBuilder.java:929)
        at aQute.launchpad.BundleBuilderTest.testWorkspaceOrProjectAfterParent(BundleBuilderTest.java:161)
aQute.launchpad.BundleBuilderTest > testOrder FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: specified file /home/rotty/projects/bnd/testresources/inherit.bnd as parent for build but no such file exist
        at aQute.lib.link.Link.waitForResult(Link.java:490)
        at aQute.lib.link.Link$1.invoke(Link.java:191)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.lib.aspects.Aspects$1.lambda$new$1(Aspects.java:173)
        at aQute.lib.aspects.Aspects$1.lambda$invoke$14(Aspects.java:314)
        at aQute.lib.aspects.Aspects$1.lambda$$0(Aspects.java:165)
        at aQute.lib.aspects.Aspects$1.invoke(Aspects.java:314)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at aQute.launchpad.BundleSpecBuilder.install(BundleSpecBuilder.java:920)
        at aQute.launchpad.BundleSpecBuilder.start(BundleSpecBuilder.java:929)
        at aQute.launchpad.BundleBuilderTest.testOrder(BundleBuilderTest.java:174)
aQute.launchpad.BundleBuilderTest > testInherit FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: specified file /home/rotty/projects/bnd/testresources/inherit.bnd as parent for build but no such file exist
        at aQute.lib.link.Link.waitForResult(Link.java:490)
        at aQute.lib.link.Link$1.invoke(Link.java:191)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.lib.aspects.Aspects$1.lambda$new$1(Aspects.java:173)
        at aQute.lib.aspects.Aspects$1.lambda$invoke$14(Aspects.java:314)
        at aQute.lib.aspects.Aspects$1.lambda$$0(Aspects.java:165)
        at aQute.lib.aspects.Aspects$1.invoke(Aspects.java:314)
        at com.sun.proxy.$Proxy12.build(Unknown Source)
        at aQute.launchpad.BundleSpecBuilder.install(BundleSpecBuilder.java:920)
        at aQute.launchpad.BundleSpecBuilder.start(BundleSpecBuilder.java:929)
        at aQute.launchpad.BundleBuilderTest.testInherit(BundleBuilderTest.java:73)
33 tests completed, 3 failed
```
And in Eclipse
![Screenshot from 2019-04-04 13-00-56](https://user-images.githubusercontent.com/146764/55580708-2931a980-56e9-11e9-9175-54f9ff44a926.png)

**Comment by bjhargrave** [comment]
This is also causing the Azure builds to fail: https://dev.azure.com/bndtools/bnd/_build/results?buildId=873&view=logs&jobId=7bc79c07-43ba-5b2f-8dc3-f11cef7b787f&taskId=4397a364-9dde-5fe9-7a85-184c19b47fd9&lineStart=695&lineEnd=713&colStart=1&colEnd=1

**Comment by rotty3000** [comment]
For the time being in my PRs I simple added a commit which `@Ignore` the tests.
