### ISSUE TITLE
NPE in "bnd resolve resolve"

### ISSUE THREAD

**Issue by io7m** [bndtools/bnd#3197]
Hello.

```
$ cat main.bndrun
-runfw: \
  org.apache.felix.framework

-runee: JavaSE-11

-resolve.effective: active

-runrequires: \
  osgi.identity;filter:='(osgi.identity=org.apache.felix.scr)' \

$ bnd version -x
Version                                  4.2.0.201903051501
License                                  Apache License, Version 2.0
Copyright                                Copyright (c) aQute SARL (2000, 2019) and others. All Rights Reserved.
Git-SHA                                  7028683045bf0d6e4c3794958af2b179f754c96b
Git-Descriptor                           4.2.0.REL
Sources                                  url=https://github.com/bndtools/bnd, connection=scm:git:https://github.com/bndtools/bnd.git, developerConnection=scm:git:git@github.com:bndtools/bnd.git, tag=4.2.0.REL

$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

$ bnd resolve resolve
-----------------
Errors
000: Exception: java.lang.NullPointerException
	at aQute.bnd.main.bnd.handleOptions(bnd.java:4372)
	at aQute.bnd.main.ResolveCommand._resolve(ResolveCommand.java:263)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.lib.getopt.CommandLine.subCmd(CommandLine.java:636)
	at aQute.bnd.main.bnd._resolve(bnd.java:4253)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd._bnd(bnd.java:447)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd.start(bnd.java:295)
	at aQute.bnd.main.bnd.main(bnd.java:272)

001: null

$ bnd resolve resolve -b main.bndrun 
-----------------
Errors
000: Exception: java.lang.NullPointerException
	at aQute.bnd.main.bnd.handleOptions(bnd.java:4372)
	at aQute.bnd.main.ResolveCommand._resolve(ResolveCommand.java:263)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.lib.getopt.CommandLine.subCmd(CommandLine.java:636)
	at aQute.bnd.main.bnd._resolve(bnd.java:4253)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd._bnd(bnd.java:447)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd.start(bnd.java:295)
	at aQute.bnd.main.bnd.main(bnd.java:272)

001: null
```

**Comment by rotty3000** [comment]
@io7m the bnd cli resolver only works when the bndrun is in a bnd workspace project. When the bndrun is in a maven project or a non-workspace gradle project then the cli doesn't work.

To resolve in maven project either:
a) `mvn bnd-resolver:resolve` the project
b) add the `bnd-resolver-maven-plugin` to the `prepare-package` phase

**Comment by io7m** [comment]
Yep, got it, thanks.

I was reporting this mainly because an uncaught null pointer exception is generally not a good thing keep around. :smile:
