### ISSUE TITLE
bnd-testing-maven-plugin: UnknownHostException

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3230]
While porting projects to use the bnd maven plugins and adding integration tests I realized that on some CI build machines the tests are not executed:

```
227565 [INFO] --- bnd-testing-maven-plugin:4.2.0:testing (default) @ replaced ---
227568 [INFO] Matching glob *
exiting java.net.UnknownHostException: noisynuc: noisynuc: Name or service not known
java.net.UnknownHostException: noisynuc: noisynuc: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at aQute.junit.JunitXmlReport.<init>(JunitXmlReport.java:35)
	at aQute.junit.Activator.test(Activator.java:323)
	at aQute.junit.Activator.automatic(Activator.java:236)
	at aQute.junit.Activator.run(Activator.java:177)
	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
	at aQute.launcher.Launcher.run(Launcher.java:352)
	at aQute.launcher.Launcher.main(Launcher.java:152)
Caused by: java.net.UnknownHostException: noisynuc: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 7 more
Tests run  : 0
Passed     : 0
Errors     : 0
Failures   : 0
```

The hostname of the machine is `noisynuc`.

The same (except hostname) stacktrace is shown for another CI machine (another hostname), too.

I assume the problem will be gone if I add an entry to the hosts file to resolve the local hostname to the loopback address.
But why is this necessary at all?

**Comment by pkriens** [comment]
It is stored in the XML test report in the <testsuite hostname="...."> tag.

I assume this report now does not get written. I'll add a try/catch clause to ignore the exception
