### ISSUE TITLE
Cannot rename package in Eclipse

### ISSUE THREAD

**Issue by paul-ecan** [bndtools/bnd#3294]
Eclipse Modeling Tools
Version: Photon Release (4.8.0)
Build id: 20180619-1200
Bndtools 4.2.0.REL-20190305-163318-g7028683

Actions:
1. Select package in model explorer
2. Rename hot-key {Alt-Shift-R}
3. Type new name
4. <OK>
5. Some actions notified in progress bar, then returns to "Rename Package" panel.
6. Rename has not succeeded

Error log:
Plugin: bntools.core
Severity: Error
Message: Could not read file bnd4010553418044312411.bnd
Exception Stack Trace:
```
org.eclipse.core.internal.resources.ResourceException(/hazze.core.app/build/tmp/bundle_event_service/bnd4010553418044312411.bnd)[368]: java.lang.Exception: File not found: C:\Users\paul\eclipse.home\hazze-workspace\hazze.core.app\build\tmp\bundle_event_service\bnd4010553418044312411.bnd.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:39)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:35)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:830)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at org.bndtools.utils.workspace.FileUtils.readFully(FileUtils.java:37)
	at bndtools.refactor.PkgRenameParticipant$1.visit(PkgRenameParticipant.java:120)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:132)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:91)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at bndtools.refactor.PkgRenameParticipant.createChange(PkgRenameParticipant.java:233)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:306)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:207)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by bjhargrave** [comment]
This seems to be an interaction between the Gradle plugin for non-workspace builds and the PkgRenameParticipant. The latter has https://github.com/bndtools/bnd/blob/7207e9f4d12f5ee78ca5291ab6a5642b9d4e9d10/bndtools.core/src/bndtools/refactor/PkgRenameParticipant.java#L105-L109

which assumes all files with a `.bnd` extension in the project's folder are source files which may need refactoring.

But BundleTaskConvention writes a temporary bnd file in the output folder https://github.com/bndtools/bnd/blob/7207e9f4d12f5ee78ca5291ab6a5642b9d4e9d10/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy#L201-L202

and this file is picked up by the above code.

The best solution would be for PkgRenameParticipant to ignore bnd files which are in output folders. But I not sure how to teach it that as I am not familiar enough with the Eclipse side of the house.

**Comment by kriegfrj** [comment]
Saw this one pop up in stalebot. Surely  this should be an easy fix. If the Eclipse part is the hard part, I'm happy to take that on.

If we can come up with a definitive description as to which directories should be excluded from the search for `.bnd` files (or alternatively, which directories are to be included), then it's easy. Or do I simply need to start with `bnd.bnd` and traverse the `-include` hierarchy to find them all, and then ignore all others? That is harder. but doable.
