### ISSUE TITLE
Launcher should not start fragments after update

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3366]
! Unexpected error in the run body: Fragment bundles can not be stopped: com.qivicon.binding.bitronvideo.cgi.camera [16]
org.osgi.framework.BundleException: Fragment bundles can not be stopped: com.qivicon.binding.bitronvideo.cgi.camera [16]
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2753)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1038)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1024)
        at aQute.launcher.Launcher.installEmbedded(Launcher.java:800)
        at aQute.launcher.Launcher.update(Launcher.java:505)
        at aQute.launcher.Launcher.activate(Launcher.java:422)
        at aQute.launcher.Launcher.launch(Launcher.java:333)
        at aQute.launcher.Launcher.run(Launcher.java:143)
        at aQute.launcher.Launcher.main(Launcher.java:121)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:154)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:106)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:51)
org.osgi.framework.BundleException: Fragment bundles can not be stopped: com.qivicon.binding.bitronvideo.cgi.camera [16]
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2753)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1038)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1024)
        at aQute.launcher.Launcher.installEmbedded(Launcher.java:800)
        at aQute.launcher.Launcher.update(Launcher.java:505)
        at aQute.launcher.Launcher.activate(Launcher.java:422)
        at aQute.launcher.Launcher.launch(Launcher.java:333)
        at aQute.launcher.Launcher.run(Launcher.java:143)
        at aQute.launcher.Launcher.main(Launcher.java:121)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:154)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:106)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:51)

**Comment by pkriens** [comment]
Should be fixed #3367
