### ISSUE TITLE
Gradle build fails with heap space

### ISSUE THREAD

**Issue by dejvu** [bndtools/bnd#3400]
Hi we are using Gradle to build OSGi project and trying to migrate from Gradle's deprecated osgi plugin to bnd builder.
Project is big (around 80 subprojects) and it work fine with Gradle's osgi plugin.
After switching to biz.aQute.bnd.builder we are facing following problem:

Expiring Daemon because JVM heap space is exhausted
Java heap space

```
Caused by: java.lang.OutOfMemoryError: Java heap space
        at aQute.lib.io.ByteBufferOutputStream.<init>(ByteBufferOutputStream.java:16)
        at aQute.bnd.osgi.Jar.buildFromInputStream(Jar.java:245)
        at aQute.bnd.osgi.Jar.buildFromResource(Jar.java:235)
        at aQute.bnd.osgi.Jar.fromResource(Jar.java:140)
        at aQute.bnd.cdi.CDIAnnotations.lambda$analyzeJar$3(CDIAnnotations.java:94)
        at aQute.bnd.cdi.CDIAnnotations$$Lambda$241/914568184.apply(Unknown Source)
        at aQute.lib.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
        at aQute.lib.exceptions.FunctionWithException$$Lambda$242/1740292918.apply(Unknown Source)
        at aQute.bnd.cdi.CDIAnnotations.analyzeJar(CDIAnnotations.java:92)
        at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:879)
        at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:239)
        at aQute.bnd.osgi.Builder.analyze(Builder.java:408)
        at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:909)
        at aQute.bnd.osgi.Builder.build(Builder.java:118)
        at aQute.bnd.osgi.Builder$build$3.call(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5$_closure6.doCall(BundleTaskConvention.groovy:28
```

With Gradle's osgi plugin project builds fine with just as little as -Xmx256m but with biz.aQute.bnd.builder it fails even with -Xmx4g.
It might be related to this one https://github.com/bndtools/bndtools/issues/1877 which uses bnd workspace plugin.

Gradle: 5.6
Bnd plugin: 4.2.0
IntelliJ IDEA 2019.2

**Comment by pkriens** [comment]
Is there a gigabyte file in your bundle you build? The code that crashes is analyzing  a JAR file for CDI annotations. Since JAR files are supposed to be loaded by the VM we assume we can read them in memory for performance. However, if you have a 4Gb datafile in your bundle that might be cumbersome. 

I doubt the number of projects are an issue. 80 is a small workspace in my world :-)

**Comment by pkriens** [comment]
Looking a bit deeper it seems a JAR that is on your Bundle-Classpath?

**Comment by dejvu** [comment]
Hi @pkriens ,
yes we use Bundle-Classpath in some of subprojects but none of jar there cross size of 8MB. There are no gigabyte datafiles. Biggest bundle build which use Bundle-Classpath is of 38MB size (several jars on Bundle-Classpath). As noted with Gradle's OSGi plugin -Xmx256m is enough to build it without any errors.

**Comment by pkriens** [comment]
The code running in problems is the CDI annotations which is probably not supported by the old plugin.
Is there a way you can make a heap dump? There might be a leak

**Comment by dejvu** [comment]
Sure, here is heap dump
https://drive.google.com/file/d/1b33u5FgPsZmGC7cOIC5e7785kHZCMKAH/view?usp=sharing

**Comment by pkriens** [comment]
First, set the following in the bnd file (assuming you don't use cdi):

      -cdiannotations: 

This will make sure the OutOfMemoryError does not happen.

There is clearly enough memory looking at the dump. I think one of the JARs ZipEntry on the Bundle-ClassPath (BCP) is somehow corrupt. When we open that jar on the BCP it contains an entry that has a size that is positive and too large. Can you share those bundles that are on the Bundle-ClassPath with me? You can send them to me personally if you want: Peter.Kriens@aQute.biz

**Comment by dejvu** [comment]
Hi we are not using bnd file, instead our builds are fully gradle driven
```
jar {
    bnd("-cdiannotations": "", ...)
}
```
fixes problem. Thanks

**Comment by pkriens** [comment]
still would be interesting to know why that BCP entry has such a large size ...

**Comment by pkriens** [comment]
I will put a diagnostic bnd for this case. If you could then run the latest gradle plugin in debug we might see what is going on.
