### ISSUE TITLE
ArrayIndexOutOfBoundsException when installing a bundle wrap using Apache Servicemix

### ISSUE THREAD

**Issue by slux83** [bndtools/bnd#3405]
Hi,
I'm using Apache Servicemix 5.4.0 (same with the last version 7.0.1) and when I install the following bundle (wrapped) I receive the ArrayIndexOutOfBoundException.

**Command:**
`install -s wrap:mvn:org.jruby.joni/joni/2.1.29`

**Exception**
```
java.lang.ArrayIndexOutOfBoundsException: 19
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:576)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
	at org.ops4j.pax.swissbox.bnd.BndUtils.createBundle(BndUtils.java:161)
	at org.ops4j.pax.url.wrap.internal.Connection.getInputStream(Connection.java:83)
	at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:524)
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166)
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2874)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)
	at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:43)
	at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:38)
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:195)
	at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:79)
```

**Comment by bjhargrave** [comment]
That stack trace indicates that a very old version of Bndlib is being used here. It appears to be version 2.3.0! 

https://github.com/bndtools/bnd/blob/fa5ff5a48ac36333fd27ec53693f832d4120fa26/biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java#L576

is where the exception occurs. 19 is the constant pool entry tag CONSTANT_Module which was added for Java 9. Bnd 2.3.0 was made in May 2014, long before Java 9, and does not know about CONSTANT_Module tags:

https://github.com/bndtools/bnd/blob/fa5ff5a48ac36333fd27ec53693f832d4120fa26/biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java#L407-L428

The current version of Bndlib uses a completely new class file parser and, of course, handles Java 9.

You need to get the PAX wrap URL support to update the version of Bndlib they use.
