### ISSUE TITLE
NPE in BndPomRepository if pom file not found

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3439]
I had a `BndPomRepository` configured in my `build.bnd` but the POM file was missing. Ended up with the following NPE. It would be nice if it were a little more gracious about handling it, and a little more helpful in reporting what is wrong.

eclipse.buildId=4.12.0.I20190605-1800
java.version=12.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU
Framework arguments:  -product org.eclipse.epp.package.java.product

bndtools.core
Error
Sun Sep 22 01:04:50 ACST 2019
Init of workspace

java.lang.NullPointerException
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.versions(BndPomRepository.java:270)
	at aQute.bnd.build.Project.getBundle(Project.java:1276)
	at aQute.bnd.build.Project.getBundles(Project.java:656)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:558)
	at aQute.bnd.build.Project.prepare(Project.java:400)
	at aQute.bnd.build.Project.getDependson(Project.java:865)
	at aQute.bnd.build.Workspace.getBuildOrder(Workspace.java:571)
	at bndtools.central.Central.getWorkspace(Central.java:253)
	at bndtools.central.Central.getProject(Central.java:575)
	at bndtools.central.Central.getProject(Central.java:579)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:230)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:87)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3195)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3079)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3141)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2111)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3691)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3157)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3321)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2398)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:479)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:268)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:267)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:2274)
	at org.eclipse.jdt.internal.ui.workingsets.DynamicSourcesWorkingSetUpdater.updateElements(DynamicSourcesWorkingSetUpdater.java:211)
	at org.eclipse.jdt.internal.ui.workingsets.DynamicSourcesWorkingSetUpdater.updateElements(DynamicSourcesWorkingSetUpdater.java:192)
	at org.eclipse.jdt.internal.ui.workingsets.DynamicSourcesWorkingSetUpdater$1.run(DynamicSourcesWorkingSetUpdater.java:160)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by bjhargrave** [comment]
Adding @juergen-albert  since it he working on this code.
