### ISSUE TITLE
Deprecations wit Gradle  6.0

### ISSUE THREAD

**Issue by cdietrich** [bndtools/bnd#3494]
With Gradle 6.0 i get this deprecation warning

> The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.

```
> Task :org.eclipse.xtext.web:jar
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.getBaseName(AbstractArchiveTask.java:220)
        at org.gradle.api.tasks.bundling.Jar_Decorated.getBaseName(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at groovy.lang.Closure.getProperty(Closure.java:292)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:313)
        at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:307)
        at groovy.lang.Closure.getProperty(Closure.java:296)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5$_closure6.doCall(BundleTaskConvention.groovy:277)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5.doCall(BundleTaskConvention.groovy:199)

```

**Comment by cdietrich** [comment]
stacktrace with 4.3.0

```
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.getBaseName(AbstractArchiveTask.java:220)
        at org.gradle.api.tasks.bundling.Jar_Decorated.getBaseName(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at groovy.lang.Closure.getProperty(Closure.java:292)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:313)
        at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:307)
        at groovy.lang.Closure.getProperty(Closure.java:296)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5$_closure6.doCall(BundleTaskConvention.groovy:282)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5.doCall(BundleTaskConvention.groovy:199)

```

**Comment by cdietrich** [comment]
thx. i can confirm the problem is gone with 4.4.0-SNAPSHOT
