### ISSUE TITLE
bnd 4.3.0 incompatible with SpotBugs

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#3501]
I have upgraded the workspace on one of my projects to bnd 4.3.0.

The project is located at ```https://gitlab.com/fhuberts/musicTreePrograms```

However, all of a sudden SpotBugs no longer works in the build.
I've checked that SpotBugs is still on the classpath, and I've also checked that it's not Gradle itself; all Gradle versions from 5.4 through to 5.6.3 exhibit this problem.

Literally the only things that changed are the bnd jars.

The problem is demonstrated on the branches:
```
  bnd-430-full
  bnd-430-minimal
```

The master branch has bnd 4.2.0 and works normally.

The command to reproduce the problem:
```
./gradlew  build export release jacocoTestReport spotbugs javadoc
```

```
$ ./gradlew  build export release jacocoTestReport spotbugs javadoc
> Task :nl.pelagic.audio.conversion.flac2mp3:spotbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nl.pelagic.audio.conversion.flac2mp3:spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.
      > com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
48 actionable tasks: 48 executed
```

**Comment by fhuberts** [comment]
Also, it's not a memory thing.
Adding
```
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=2048m
```
to gradle.properties changes nothing.

**Comment by bjhargrave** [comment]
> * Try:
> Run with --stacktrace option

Perhaps you can provide the stacktrace of the failure?

**Comment by fhuberts** [comment]
Obviously already tried that and saw nothing that stands out.
I prepared the branches on the repo so you can do that yourself as well, way more efficient I think.


```
$ ./gradlew --stacktrace  build export release jacocoTestReport spotbugs javadoc
Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details
> Task :nl.pelagic.audio.conversion.flac2mp3:spotbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nl.pelagic.audio.conversion.flac2mp3:spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.
      > com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':nl.pelagic.audio.conversion.flac2mp3:spotbugsMain'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.worker.WorkerProcessException: Failed to run Gradle SpotBugs Worker
        at org.gradle.process.internal.worker.WorkerProcessException.runFailed(WorkerProcessException.java:29)
        at org.gradle.process.internal.worker.request.Receiver.infrastructureFailed(Receiver.java:88)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        ... 3 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:54)
        at org.gradle.process.internal.worker.request.WorkerAction.execute(WorkerAction.java:68)
        at org.gradle.process.internal.worker.request.WorkerAction.execute(WorkerAction.java:40)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:91)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:70)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:68)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;
        at org.gradle.internal.instantiation.AbstractClassGenerator$AbstractInjectedPropertyHandler.getInjectedServices(AbstractClassGenerator.java:1123)
        at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:237)
        at org.gradle.internal.instantiation.AbstractClassGenerator.access$000(AbstractClassGenerator.java:93)
        at org.gradle.internal.instantiation.AbstractClassGenerator$1.transform(AbstractClassGenerator.java:111)
        at org.gradle.internal.instantiation.AbstractClassGenerator$1.transform(AbstractClassGenerator.java:108)
        at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:124)
        at org.gradle.internal.instantiation.AbstractClassGenerator.generate(AbstractClassGenerator.java:150)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.generate(AsmBackedClassGenerator.java:109)
        at org.gradle.internal.instantiation.Jsr330ConstructorSelector$1.transform(Jsr330ConstructorSelector.java:59)
        at org.gradle.internal.instantiation.Jsr330ConstructorSelector$1.transform(Jsr330ConstructorSelector.java:54)
        at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:124)
        at org.gradle.internal.instantiation.Jsr330ConstructorSelector.forType(Jsr330ConstructorSelector.java:54)
        at org.gradle.internal.instantiation.Jsr330ConstructorSelector.forParams(Jsr330ConstructorSelector.java:49)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:46)
        ... 8 more


* Get more help at https://help.gradle.org

BUILD FAILED in 17s
48 actionable tasks: 48 executed
```

**Comment by bjhargrave** [comment]
> Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;

This seems to be the culprit. Perhaps there are somehow multiple versions of the Google Collections jar on the classpath of the Gradle Plugins? And the first version is older than SpotBugs requires?

What is the output of the following task?

```groovy
tasks.register('buildscriptDependencies') {
  doLast {
    println buildscript.configurations.classpath.asPath
  }
}
```

The Bnd build shows

```
> Task :buildscriptDependencies
/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bnd.gradle/4.4.0-SNAPSHOT/6ff3c0b4a80599224051e49cd05d12255ec7d222/biz.aQute.bnd.gradle-4.4.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.resolve/4.4.0-SNAPSHOT/1eabbcbe3ec8d5113911e6178639a10e73ca9579/biz.aQute.resolve-4.4.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.repository/4.4.0-SNAPSHOT/196fe0b0c26ad1dd6231ba20bd3e0d4ada81e61/biz.aQute.repository-4.4.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bndlib/4.4.0-SNAPSHOT/62ae8d1c11a80f23e1150d833d57d00aa2ca345d/biz.aQute.bndlib-4.4.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bnd.embedded-repo/4.4.0-SNAPSHOT/c9af0de1f7c950c37884525559ff268424e8a45a/biz.aQute.bnd.embedded-repo-4.4.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar
```

which shows the Bnd does not use the Google Collections jars.

**Comment by bjhargrave** [comment]
If you have `biz.aQute.bnd` in your gradle plugin classpath, then you may have an issue since the bnd jar does include a copy of some Guava packages for the new reporter support. But you should not be using the `biz.aQute.bnd` artifact in Gradle or Maven.

**Comment by fhuberts** [comment]
Yes, bnd is new there.
I had to do that because otherwise I get an error that the embedded-repo.jar could not be found. Seems you moved that between the 4.2.0 and 4.3.0 versions. It was not enough to just upgrade the 4.2.0 versions I had to 4.3.0 versions.

Try the bnd-430-full branch, remove the bnd jar from cnf/gradle/dependencies, and run the build.
The build you run then is the situation of above, just upgraded versions - with the embedded-repo.jar failure.

If I should add a different jar, them please let me know.

**Comment by fhuberts** [comment]
If I extract the embedded-repo.jar from the bnd jar, and place it on the classpath, then it also doesn't work.
If I hack the bnd gradle jar and add the embedded-repo.jar to its root, then it works again.
Which is basically 'the 'same' as 4.2.0, which has the embedded-repo-.jar in the bnd gradle jar.

So either removing that jar there was a mistake or I should include an additional bnd jar but not bnd itself?

**Comment by fhuberts** [comment]
Ok, I found bnd commit dffa2aa30436ee1a32745a7be9b6e73063719864.
Explains a lot.

Downloaded the embedded-repo jar and added it to the classpath and that works.

Seems this was forgotten in the backwards compatibility section of the release notes.
