### ISSUE TITLE
Gradle Index task should fail when unable to process provided jars

### ISSUE THREAD

**Issue by Fiouz** [bndtools/bnd#3550]
As seen at #3549, the Gradle indexer task incorrectly reports success to Gradle even when it cannot process some `File` entries, resulting in an incomplete index file creation without obvious feedback that there is something wrong.

bnd: 4.3.0
Gradle: 5.6.4

```
java.lang.IllegalArgumentException: Illegal character in path at index 9: ../../foo bar/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar
        at java.base/java.net.URI.create(URI.java:883)
        at aQute.bnd.osgi.repository.SimpleIndexer.relativize(SimpleIndexer.java:212)
        at aQute.bnd.osgi.repository.SimpleIndexer.indexFile(SimpleIndexer.java:191)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at aQute.bnd.osgi.repository.SimpleIndexer.getResources(SimpleIndexer.java:162)
        at aQute.bnd.osgi.repository.SimpleIndexer.repository(SimpleIndexer.java:173)
        at aQute.bnd.osgi.repository.SimpleIndexer.index(SimpleIndexer.java:149)
        at aQute.bnd.osgi.repository.SimpleIndexer$index$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at aQute.bnd.gradle.Index.indexer(Index.groovy:206)
[...]
BUILD SUCCESSFUL in 1m 9s
```

The same example as #3549 can be used to reproduce the issue: https://github.com/Fiouz/bnd-uri-handling/blob/master/Dockerfile

**Comment by Fiouz** [comment]
Exception is swallowed at https://github.com/bndtools/bnd/blob/4.3.0.REL/biz.aQute.bndlib/src/aQute/bnd/osgi/repository/SimpleIndexer.java#L198

**Comment by bjhargrave** [comment]
> Exception is swallowed

It is not swallowed. It is logged as an exception to a logger which is not the task's logger. I will fix this to make it log to the task's logger.
