### ISSUE TITLE
Intermittent CI failures in biz.aQute.launcher.AlsoLauncherTest > testReporting_notUsingReferences

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3558]
I am seeing intermitted failures in the CI builds for the test
`biz.aQute.launcher.AlsoLauncherTest > testReporting_notUsingReferences`

See <https://dev.azure.com/bndtools/bnd/_build/results?buildId=1943&view=logs&jobId=b3291d64-658e-5a5d-b1f7-4a519b56de6f&taskId=153cd695-8bff-5d34-e695-1771a4c66312&lineStart=761&lineEnd=963&colStart=1&colEnd=29> for example.

```
> Task :biz.aQute.bndall.tests:test

biz.aQute.launcher.AlsoLauncherTest > testReporting_notUsingReferences FAILED
    org.assertj.core.error.AssertJMultipleFailuresError: 
    Multiple Failures (1 failure)
    -- failure 1 --
    [System Bundle] 
    Expecting:
      "Id    Levl State Modified      Location
    0     java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    ! org.osgi.framework.FrameworkEvent[source=org.apache.felix.framework [0]]
    java.lang.NullPointerException: bsn must be specified
    	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:15)
    	at aQute.lib.bundles.BundleIdentity.<init>(BundleIdentity.java:21)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at aQute.lib.startlevel.StartLevelRuntimeHandler$1$1.bundleChanged(StartLevelRuntimeHandler.java:201)
    	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
    	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
    	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
    	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    0   ACTIV <>            System Bundle
    1     10  ACTIV 201810132223  file:/home/vsts/work/1/s/maven/target/m2/org/apache/felix/org.apache.felix.scr/2.1.12/org.apache.felix.scr-2.1.12.jar
    2     11  ACTIV 201810132026  file:/home/vsts/work/1/s/maven/target/m2/org/apache/felix/org.apache.felix.configadmin/1.9.10/org.apache.felix.configadmin-1.9.10.jar
    3     12  ACTIV 201909081833  file:/home/vsts/work/1/s/maven/target/m2/org/junit/platform/junit-platform-commons/1.5.2/junit-platform-commons-1.5.2.jar
    4     12  ACTIV 201909081833  file:/home/vsts/work/1/s/maven/target/m2/org/junit/platform/junit-platform-engine/1.5.2/junit-platform-engine-1.5.2.jar
    5     12  ACTIV 201908040444  file:/home/vsts/work/1/s/maven/target/m2/org/assertj/assertj-core/3.13.2/assertj-core-3.13.2.jar
    6     12  ACTIV 201906061924  file:/home/vsts/work/1/s/maven/target/m2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
    7     12  ACTIV 201906061907  file:/home/vsts/work/1/s/maven/target/m2/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar
    8     12  ACTIV 201909081833  file:/home/vsts/work/1/s/maven/target/m2/org/junit/jupiter/junit-jupiter-api/5.5.2/junit-jupiter-api-5.5.2.jar
    9     12  ACTIV 201909081834  file:/home/vsts/work/1/s/maven/target/m2/org/junit/jupiter/junit-jupiter-engine/5.5.2/junit-jupiter-engine-5.5.2.jar
    10    12  ACTIV 201909081834  file:/home/vsts/work/1/s/maven/target/m2/org/junit/jupiter/junit-jupiter-params/5.5.2/junit-jupiter-params-5.5.2.jar
    11    12  ACTIV 201502041348  file:/home/vsts/work/1/s/maven/target/m2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.junit/4.12_1/org.apache.servicemix.bundles.junit-4.12_1.jar
    12    12  ACTIV 201909081834  file:/home/vsts/work/1/s/maven/target/m2/org/junit/vintage/junit-vintage-engine/5.5.2/junit-vintage-engine-5.5.2.jar
    13    12  ACTIV 201911122252  file:/home/vsts/work/1/s/biz.aQute.bndall.tests/generated/tmp/test/testReporting_notUsingReferences/test%20ws/demo/generated/demo.jar
    "
    to contain pattern:
      "\n0\s+\d+\s*ACTIV\s+[<][>]\s+System Bundle"
    at AlsoLauncherTest.doTestReporting(AlsoLauncherTest.java:573)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at biz.aQute.launcher.AlsoLauncherTest.doTestReporting(AlsoLauncherTest.java:587)
        at biz.aQute.launcher.AlsoLauncherTest.testReporting_notUsingReferences(AlsoLauncherTest.java:533)

40 tests completed, 1 failed
```

**Comment by bjhargrave** [comment]
@kriegfrj I suspect this test may have been one you were involved with. Can you shed any light on the situation here?

**Comment by kriegfrj** [comment]
Yes, I wrote that test. I'll have a look at it.

**Comment by kriegfrj** [comment]
On inspection, I don't think that this is directly related to my test or the feature that it is testing.

I sampled a few of the other tests in `AlsoLauncherTest` (specifically: `testAgent()`, `testEnv()`, as well as `testReporting_notUsingReferences()`). The stack traces were appearing in all of them. I strongly suspect they are appearing in the stderr output of every test in `AlsoLauncherTest`.

The only thing different about `testReporting_notUsingReferences()` and `testReporting_usingReferences()` is that these tests are actually checking and asserting on the output to stderr. Because the stack traces are generated in a different thread to the main thread, the position that they appear in the output varies. Depending on the timing they can appear in the output in the middle of the report block that the `testReporting_xxx()` methods are asserting on, which causes the assertions to fail.

So the root cause seems to have something to do with the startlevel handling in the test project launcher. This isn't an area that I'm familiar with and I don't have time to familiarise myself with it, so I'll have to pass this one on to someone else.
