### ISSUE TITLE
maven.provider.POM: version ranges unsupported

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3621]
If a pom file is using a version range for its parent pom an error is logged:

Message:

```
Failed to parse pom org.openhab.addons:org.openhab.addons.reactor:2.5.0-SNAPSHOT from file /home/rathgeb/.m2/repository/org/openhab/addons/org.openhab.addons.reactor/2.5.0-SNAPSHOT/org.openhab.addons.reactor-2.5.0-SNAPSHOT.
```

Exception Stack Trace:

```
java.lang.IllegalArgumentException: Invalid version for parent pom org.openhab:openhab-super-pom:null
	at aQute.maven.provider.POM.<init>(POM.java:179)
	at aQute.maven.provider.POM.<init>(POM.java:142)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:308)
	at aQute.maven.provider.MavenRepository.lambda$getPomPromise$1(MavenRepository.java:335)
	at org.osgi.util.promise.DeferredPromiseImpl$Map.run(DeferredPromiseImpl.java:430)
	at org.osgi.util.promise.PromiseImpl.onResolve(PromiseImpl.java:106)
	at org.osgi.util.promise.PromiseImpl.map(PromiseImpl.java:290)
	at aQute.maven.provider.MavenRepository.getPomPromise(MavenRepository.java:330)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:316)
	at aQute.maven.provider.POM.<init>(POM.java:189)
	at aQute.maven.provider.POM.<init>(POM.java:142)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:308)
	at aQute.maven.provider.MavenRepository.lambda$getPomPromise$1(MavenRepository.java:335)
	at org.osgi.util.promise.DeferredPromiseImpl$Map.run(DeferredPromiseImpl.java:430)
	at org.osgi.util.promise.PromiseImpl.onResolve(PromiseImpl.java:106)
	at org.osgi.util.promise.PromiseImpl.map(PromiseImpl.java:290)
	at aQute.maven.provider.MavenRepository.getPomPromise(MavenRepository.java:330)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:316)
	at aQute.maven.provider.POM.<init>(POM.java:189)
	at aQute.maven.provider.POM.<init>(POM.java:142)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:308)
	at aQute.maven.provider.MavenRepository.lambda$getPomPromise$1(MavenRepository.java:335)
	at org.osgi.util.promise.DeferredPromiseImpl$Map.run(DeferredPromiseImpl.java:430)
	at org.osgi.util.promise.PromiseImpl.onResolve(PromiseImpl.java:106)
	at org.osgi.util.promise.PromiseImpl.map(PromiseImpl.java:290)
	at aQute.maven.provider.MavenRepository.getPomPromise(MavenRepository.java:330)
	at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:316)
	at aQute.bnd.repository.maven.pom.provider.Traverser.parseArchive(Traverser.java:162)
	at aQute.bnd.repository.maven.pom.provider.Traverser.lambda$parse$0(Traverser.java:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

See parent is defined this way: https://github.com/openhab/openhab2-addons/blob/489e40346fd4cbadfe87d13ab7899fbb1ab9a639/pom.xml

**Comment by bjhargrave** [comment]
Maven recommends strongly against using version ranges. So I can see why Bnd does not support them in POMs. I would recommend you get openhab to stop using version ranges.

**Comment by maggu2810** [comment]
> Maven recommends strongly against using version ranges.

Me, too.

> I would recommend you get openhab to stop using version ranges.

I tried it a long time but I gave up:
https://github.com/openhab/openhab-core/pull/555#issuecomment-462115668

**Comment by maggu2810** [comment]
Okay for me to close this as "won't fix". Up to you.

**Comment by bjhargrave** [comment]
Wont fix.
