### ISSUE TITLE
Problem with upgrading from 4.2 to 4.3.1

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#3672]
problem similar to #3467 , also Gradle 6.0.1

```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.

    	at org.gradle.api.internal.provider.AbstractReadOnlyProvider.get(AbstractReadOnlyProvider.java:29)

    	at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:60)

    	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:50)

    	at org.gradle.api.internal.provider.DefaultProperty.get(DefaultProperty.java:151)

    	at org.gradle.api.provider.Provider$get.call(Unknown Source)

    	at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure5$_closure6.doCall(BundleTaskConvention.groovy:236)

    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


```

https://dev.azure.com/gradle-aem/gradle-aem-plugin/_build/results?buildId=82&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ea098990-53e4-52aa-5a84-5ead7c5f17f2

![image](https://user-images.githubusercontent.com/10673561/71098423-fc0f2380-21b1-11ea-9169-ded8924cec31.png)

corresponding line is about `temporaryDir`? strange

usage https://github.com/Cognifide/gradle-aem-plugin/blob/develop/src/main/kotlin/com/cognifide/gradle/aem/bundle/tasks/BundleCompose.kt#L27

just changed version and boom :/

**Comment by bjhargrave** [comment]
FYI, `BundleTaskConvention.groovy:236` in 4.3.1 is the following line.

https://github.com/bndtools/bnd/blob/4.3.1.REL/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy#L236

So it is the same issue as #3467 which is fixed in Bnd 5.0. See

https://github.com/bndtools/bnd/blob/a116b9446ff64fa3d90e7c7880b5832c70bb96d2/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy#L251

and 

https://github.com/bndtools/bnd/blob/a116b9446ff64fa3d90e7c7880b5832c70bb96d2/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy#L56-L64

The workaround is to make sure the either that project.version is set or that the JarTask.archiveVersion is set.

Unfortunately, the original fix did not make it in to 4.3.1. We are driving to release 5.0 in early January.

**Comment by bjhargrave** [comment]
I added this issue to the 4.3.1 changes Known Issues section: https://github.com/bndtools/bnd/wiki/Changes-in-4.3.1#known-issues

**Comment by pun-ky** [comment]
ok thanks for quick response. so waiting for 5.0 then :)

**Comment by bjhargrave** [comment]
> so waiting for 5.0

Don't wait to test in case there is some other issue for you. You should try the snapshot builds of 5.0.

https://github.com/bndtools/bnd#using-the-latest-development-snapshot-build-of-bndbndtools

**Comment by pun-ky** [comment]
@bjhargrave ; confirmed, works with 5.0.0-SNAPSHOT :)
thanks for suggestion
