### ISSUE TITLE
New JarFile viewer has performance and hang issues

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3722]
When opening a jar file in a project's generated folder (biz.aQute.bnd project's jar). It was taking minutes to read the zip file. I could see `Reading zip file: 10%`, `Reading zip file: 11%`, etc. slowing ticking by in the lower right corner of the Eclipse window.

When I went to close the jar viewer window, I got the beach ball and had to force quit Eclipse. 

However, when I restarted, Eclipse failed to complete initialization. Using `jstack`, I dumped the threads and found this Eclipse job which was blocking the progress of all other Eclipse jobs:

```
"Worker-2: Refreshing workspace" #43 prio=5 os_prio=31 cpu=220862.48ms elapsed=279.29s tid=0x00007fdd05aec000 nid=0x17b0b runnable  [0x000070000c1e3000]
   java.lang.Thread.State: RUNNABLE
	at java.nio.HeapByteBuffer.<init>(java.base@11.0.6/HeapByteBuffer.java:61)
	at java.nio.ByteBuffer.allocate(java.base@11.0.6/ByteBuffer.java:348)
	at aQute.lib.io.ByteBufferOutputStream.<init>(ByteBufferOutputStream.java:16)
	at aQute.bnd.osgi.Jar.buildFromInputStream(Jar.java:297)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:220)
	at bndtools.jareditor.internal.JarFileSystem.lambda$getStore$1(JarFileSystem.java:217)
	at bndtools.jareditor.internal.JarFileSystem$$Lambda$826/0x0000000100e62040.apply(Unknown Source)
	at aQute.bnd.service.result.Ok.flatMap(Ok.java:153)
	at bndtools.jareditor.internal.JarFileSystem.getStore(JarFileSystem.java:209)
	at org.eclipse.core.internal.filesystem.InternalFileSystemCore.getStore(InternalFileSystemCore.java:110)
	at org.eclipse.core.filesystem.EFS.getStore(EFS.java:479)
	at org.eclipse.core.internal.localstore.FileStoreRoot.createStore(FileStoreRoot.java:134)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.getStore(FileSystemResourceManager.java:534)
	at org.eclipse.core.internal.resources.Resource.getStore(Resource.java:1188)
	at org.eclipse.core.internal.localstore.UnifiedTreeNode.getStore(UnifiedTreeNode.java:96)
	at org.eclipse.core.internal.localstore.RefreshLocalAliasVisitor.createResource(RefreshLocalAliasVisitor.java:35)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.synchronizeExistence(RefreshLocalVisitor.java:210)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:287)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:118)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:977)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:960)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1557)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:673)
	at org.eclipse.core.internal.resources.Project.reconcileLinksAndGroups(Project.java:1184)
	at org.eclipse.core.internal.resources.Project.updateDescription(Project.java:1350)
	at org.eclipse.core.internal.resources.File.updateMetadataFiles(File.java:376)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:306)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:118)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:977)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:960)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshRoot(FileSystemResourceManager.java:1002)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:953)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1557)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:166)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

   Locked ownable synchronizers:
	- None
```

I was able to finally get Eclipse to start by manually deleting the `BndtoolsJAREditorTempFiles` folder in the Eclipse workspace.

My guess is that after the force quit because of the slow loading zip file in the jar viewer, Eclipse refreshed the hidden project which again got stuck. So this hidden project is somewhat dangerous upon restart of Eclipse.

**Comment by pkriens** [comment]
It does not hold any locks, any idea why it did not make progress?

**Comment by bjhargrave** [comment]
Not yet. I am working on a change to test.
