### ISSUE TITLE
java.lang.IllegalArgumentException: No Workspace found from: ....

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3769]
When trying to import all project from this repo (git@github.com:bndtools/bnd.git) in Eclipse 2019-12 (with bndtools 5.0.0 installed) I run into the following error
```
ENTRY bndtools.builder 1 0 2020-02-08 13:52:28.121
!MESSAGE Unable to get bnd project for project aQute.libg
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: /Users/konradwindszus/git
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:231)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:184)
	at bndtools.central.Central.getWorkspace(Central.java:241)
	at bndtools.central.Central.getProject(Central.java:575)
	at bndtools.central.Central.getProject(Central.java:579)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:230)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:116)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:165)
	at org.bndtools.builder.classpath.BndContainerCompilationParticipant.aboutToBuild(BndContainerCompilationParticipant.java:19)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:638)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:181)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
...
!ENTRY bndtools.core 4 0 2020-02-08 13:52:10.908
!MESSAGE Init of workspace
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: /Users/konradwindszus/git
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:231)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:184)
	at bndtools.central.Central.getWorkspace(Central.java:241)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:41)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The Eclipse workspace folder is at `/Users/konradwindszus/workspaces/bnd` while the git working tree is at `/Users/konradwindszus/git/bnd`. 

I import via View `Git Repositories`, Right-Click on Working Tree, `Import Projects...`. All projects are correctly selected in the dialog but once I click on OK, I get error messages like above and the projects are not correctly set up.

**Comment by kwin** [comment]
Video from the Project Import: https://dropmefiles.com/UoPTv
Eclipse workspace.log: 
[bndworkspace.log](https://github.com/bndtools/bnd/files/4174211/bndworkspace.log)

**Comment by bjhargrave** [comment]
I am not sure what you were doing in the video. I don't use EGit/JGit. I use command line git.

But once you have a git checkout of the Bnd repo, you need to use the Eclipse's "Import existing projects into Workspace" operation to import the Bnd repo's projects into Eclipse. Since the git repo already includes Eclipse metadata, using "Import existing projects into Workspace" will properly import the projects.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/277682/74347266-d56b0480-4d7e-11ea-80ed-9334a76d3636.png">

**Comment by kwin** [comment]
Well, for me this is not obvious. EGit does not copy over projects to the workspace directory. IMHO this limitation should be lifted, so that projects living outside of the workspace folder are supported as well!

**Comment by bjhargrave** [comment]
You don't need to copy the projects into the Eclipse workspace folder. Import existing projects into Workspace does not do this by default. In fact, it is generally recommended that the git workspace and the Eclipse workspace be disjoint folders. I was not suggesting that you need to copy the projects into the Eclipse workspace folder.

**Comment by kwin** [comment]
You should be able to reproduce the issue by cloning with CLI and afterwards selecting "Import -> Git -> Projects from Git". Don't know how internally this is different from "Import -> General -> Existing Projects into Workspace". IMHO both ways should work, but in fact only your way works for some reason.

**Comment by bjhargrave** [comment]
> "Import -> Git -> Projects from Git"

I just did this into a new Eclipse workspace and it worked fine. All the projects are successfully built. You do need to uncheck "Search for nested projects" as we have test projects inside of our projects for testing purposes and they wont work if imported into the Eclipse workspace.

**Comment by bjhargrave** [comment]
In looking at your movie again, you seem to have a `.project` file in the root of the Bnd git repo which is not actually in our git repo. This is likely the main source of your problem. 

<img width="600" alt="Screen Shot 2020-02-12 at 13 47 24" src="https://user-images.githubusercontent.com/277682/74366576-453cb780-4d9e-11ea-8a1e-1a04e94b85b1.png">


Also I see you did not unselect Search for nested projects.

<img width="600" alt="Screen Shot 2020-02-12 at 13 48 34" src="https://user-images.githubusercontent.com/277682/74366680-72896580-4d9e-11ea-90c8-a6142dbe533e.png">
