### ISSUE TITLE
Gradle task using BND bundle task convention causing a fail when running dependencies task

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#3827]
an error occurred while running`sh gradlew :core:dependencies` (Gradle OOTB task, Bundle compose task impl - https://github.com/Cognifide/gradle-aem-plugin/blob/master/src/main/kotlin/com/cognifide/gradle/aem/bundle/tasks/BundleCompose.kt#L27 )

```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'BundleCompose'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:79)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:66)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:425)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:196)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:66)
        at org.gradle.api.internal.project.taskfactory.PropertyAssociationTaskFactory.create(PropertyAssociationTaskFactory.java:49)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:48)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:326)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:77)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:702)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:658)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:939)
        ... 162 more
Caused by: java.lang.IllegalArgumentException: Cannot change attributes of dependency configuration ':core:compileClasspath' after it has been resolved
        at org.gradle.api.internal.attributes.ImmutableAttributeContainerWithErrorMessage.attribute(ImmutableAttributeContainerWithErrorMessage.java:51)
        at org.gradle.api.attributes.AttributeContainer$attribute.call(Unknown Source)
        at aQute.bnd.gradle.BndUtils.jarLibraryElements(BndUtils.groovy:68)
        at aQute.bnd.gradle.BndUtils$jarLibraryElements.callStatic(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention.setSourceSet(BundleTaskConvention.groovy:197)
        at aQute.bnd.gradle.BundleTaskConvention$setSourceSet.callCurrent(Unknown Source)
        at aQute.bnd.gradle.BundleTaskConvention.<init>(BundleTaskConvention.groovy:83)
        at com.cognifide.gradle.aem.bundle.tasks.BundleCompose.<init>(BundleCompose.kt:27)
        at com.cognifide.gradle.aem.bundle.tasks.BundleCompose_Decorated.<init>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1858)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:430)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:55)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:72)
        ... 173 more


* Get more help at https://help.gradle.org

```

Gradle 6.2.2 (recent)

**Comment by bjhargrave** [comment]
Dup of #3780.
