### ISSUE TITLE
ConcurrentModificationException: aQute.bnd.osgi.Jar.putResource(Jar.java:337)

### ISSUE THREAD

**Issue by akarnokd** [bndtools/bnd#3908]
Hi! I'm frequently testing RxJava with various JDKs and I've just run into a Gradle failure with JDK 15-ea+18-776.

Gradle 6.3
Bnd: 5.0.1
Travis CI: https://travis-ci.org/github/akarnokd/RxJava3_BuildMatrix/jobs/673904619#L652
Repository: https://github.com/akarnokd/RxJava3_BuildMatrix

```
Caused by: java.util.ConcurrentModificationException
	at aQute.bnd.osgi.Jar.putResource(Jar.java:337)
	at aQute.bnd.osgi.Jar.buildFromZip(Jar.java:266)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:131)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:222)
```

The same Bnd version worked fine with JDK 15-ea+15-619 ([example](https://travis-ci.org/github/akarnokd/RxJava3_BuildMatrix/jobs/666637106#L553)).

Is this a problem with Bnd or the JDK?

**Comment by akarnokd** [comment]
Duplicate of #3903
Should have used different search terms, sorry about it.
