### ISSUE TITLE
When "refresh on access" is enabled, its easy to deadlock bndtools threads

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#4100]
I have "refresh on access" preference turned on in my Eclipse instances, which means I very often run into deadlock where there are 3 jobs that never finish.  However, it isn't locking the UI thread, it still prevents any workspace access so the first time you try to do an operation that requires workspace access (like editing a java file) then it will show the deadlock in the UI progress window.

Here is a stack outputs of the 3 stuck bnd threads:

```
"Worker-10: Building" #50 prio=5 os_prio=31 tid=0x00007facd107e000 nid=0x16c03 waiting for monitor entry [0x0000700012665000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at bndtools.central.Central.getWorkspace(Central.java:218)
        - waiting to lock <0x00000006c0e00000> (a org.osgi.util.promise.Deferred)
        at bndtools.central.Central.getProject(Central.java:579)
        at bndtools.central.Central$$Lambda$627/905283481.apply(Unknown Source)
        at aQute.lib.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
        at aQute.lib.exceptions.FunctionWithException$$Lambda$628/1932888002.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
        at bndtools.central.Central.getProject(Central.java:585)
        at org.bndtools.builder.BndSourceGenerateCompilationParticipant.isActive(BndSourceGenerateCompilationParticipant.java:24)
        at org.eclipse.jdt.internal.core.JavaModelManager$CompilationParticipants.getCompilationParticipants(JavaModelManager.java:473)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:635)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:181)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
```
```
"Worker-6: Updating repositories content" #45 prio=5 os_prio=31 tid=0x00007fac83817800 nid=0x1ea03 waiting for monitor entry [0x0000700012157000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at bndtools.central.Central.getWorkspace(Central.java:218)
        - waiting to lock <0x00000006c0e00000> (a org.osgi.util.promise.Deferred)
        at bndtools.central.Central.getWorkspaceRepository(Central.java:198)
        - locked <0x00000006c66d5c08> (a java.lang.Class for bndtools.central.Central)
        at bndtools.central.RepositoriesViewRefresher.ensureLoaded(RepositoriesViewRefresher.java:143)
        at bndtools.central.RepositoriesViewRefresher.access$100(RepositoriesViewRefresher.java:35)
        at bndtools.central.RepositoriesViewRefresher$1.runInWorkspace(RepositoriesViewRefresher.java:92)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
```
"org.eclipse.jdt.internal.ui.text.JavaReconciler" #34 daemon prio=1 os_prio=31 tid=0x00007fad111d0800 nid=0xd40b in Object.wait() [0x000070000e15e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:316)
        - locked <0x00000006c2e40f48> (a java.lang.Object)
        at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
        at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
        at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:298)
        at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
        at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2242)
        at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1549)
        at bndtools.central.Central.refreshFile(Central.java:552)
        at bndtools.central.WorkspaceListener.changed(WorkspaceListener.java:32)
        at aQute.bnd.build.Workspace.changedFile(Workspace.java:458)
        at aQute.bnd.build.Project.getSrcOutput0(Project.java:466)
        at aQute.bnd.build.Project.prepare(Project.java:379)
        - locked <0x00000006c948a2c8> (a java.util.concurrent.atomic.AtomicBoolean)
        at aQute.bnd.build.Project.getTestDependencies(Project.java:913)
        at aQute.bnd.build.Project.traverse(Project.java:516)
        at aQute.bnd.build.Project.prepare(Project.java:439)
        - locked <0x00000006c4af1f28> (a java.util.concurrent.atomic.AtomicBoolean)
        at aQute.bnd.build.Project.getDependson(Project.java:888)
        at aQute.bnd.build.Workspace.getBuildOrder(Workspace.java:605)
        at bndtools.central.Central.getWorkspace(Central.java:257)
        - locked <0x00000006c0e00000> (a org.osgi.util.promise.Deferred)
        at bndtools.central.Central.getProject(Central.java:579)
        at bndtools.central.Central$$Lambda$627/905283481.apply(Unknown Source)
        at aQute.lib.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
        at aQute.lib.exceptions.FunctionWithException$$Lambda$628/1932888002.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
        at bndtools.central.Central.getProject(Central.java:585)
        at org.bndtools.builder.BndSourceGenerateCompilationParticipant.isActive(BndSourceGenerateCompilationParticipant.java:24)
        at org.eclipse.jdt.internal.core.JavaModelManager$CompilationParticipants.getCompilationParticipants(JavaModelManager.java:473)
```

**Comment by gamerson** [comment]
From my basic understanding of what is going on.

1) the java reconciler thread grabs the central workspace lock and then does a refresh on a IResource which needs to be able to run a job in eclipse job manager.  However, it can't get its job scheduled because some other thread is already running a "workspace job"
2) the "repositories view refresher" thread has scheduled a workspace job and its workspace job is currently executing, and then it asked for the Central Bnd Workspace lock and is Blocked because that lock is already held by the 'java reconciler' thread.

**Comment by gamerson** [comment]
My proposed solution would be the "repositories view refresher" should not block on the central bnd workspace.  Instead it should check to see if it can grab the workspace lock without blocking first, and then continue.  If it can't get a lock, it should just re-schedule its workspace job to run at a later time.  Because updating the UI repositories view shouldn't have to be a "synchronous" blocking operation.  It should be fine to simply "update" the UI a little later, after a couple of tries.

**Comment by rotty3000** [comment]
This issue should be considered in relation to https://github.com/bndtools/bnd/issues/4108

**Comment by rotty3000** [comment]
This caused the Repositories designed for use with M2E to stop appearing in the Bndtools Repository view. The issue is with how Central deals with the different states of the workspace and the work queue associated with it.
