### ISSUE TITLE
[debug m2e] Bnd Dependencies Container doesn't find bundles under m2e

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4130]
Under m2e, the new debug source lookup mechanism (see #3993) doesn't seem to work. It only includes the ~~`-runvm`~~ `-runee` property and that imperfectly.

**Comment by bjhargrave** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/277682/87172836-dc9d2c80-c2a2-11ea-892a-6e958cbca813.png">

**Comment by kriegfrj** [comment]
I started having a look at this one. When running in the debugger I found this:

```
2020-08-04 11:52:53,497 [main] ERROR org.eclipse.equinox.logger - Error in run listener
java.lang.NullPointerException: null
	at bndtools.m2e.MavenRunProvider.create(MavenRunProvider.java:49)
	at bndtools.m2e.MavenRunProvider.create(MavenRunProvider.java:1)
	at bndtools.launch.util.LaunchUtils.createRun(LaunchUtils.java:72)
	at bndtools.launch.util.LaunchUtils.createRun(LaunchUtils.java:65)
	at bndtools.launch.sourcelookup.containers.BndDependencySourceContainer.createSourceContainers(BndDependencySourceContainer.java:76)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.getSourceContainers(CompositeSourceContainer.java:127)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceContainerViewer$ContentProvider.getChildren(SourceContainerViewer.java:64)
...
```

So after a bit of digging, I found the problem: 
https://github.com/bndtools/bnd/blob/d5385489bb29598df80d804bc0a08c442bec0b24/bndtools.core/src/bndtools/launch/sourcelookup/containers/BndDependencySourceContainer.java#L76
This uses `RunMode.SOURCES`. However, `MavenRunProvider.create0()` doesn't handle the case where `RunMode` is set to `SOURCES` and returns `null`.

Attempted fix to come.

**Comment by kriegfrj** [comment]
My PR should fix this issue but I've hit the next issue: #4249
