### ISSUE TITLE
[bndtools] Bndtools should mark error for projects outside of the Bnd workspace

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4203]
I usually have my Eclipse workspace (containing the workspace metadata) in a different directory to my Bnd workspace. I'm happy to take advice if people feel that this is not the best approach, but it has some advantages. One drawback of this approach, however, is that when you copy a project in your Eclipse workspace, by default it copies it into the Eclipse workspace and not the Bnd workspace. 

Things don't work properly when you do this - in particular, the Bndtools builder won't generate the artifacts. But there is no direct mention of the fact that this is an issue.

In my case I did have a few errors come up like this one:
```
Error in Bnd resolution analysis.
java.lang.IllegalArgumentException: A Jar can only accept a file or directory that exists: C:\workspace\idempiere-test-workspace\org.idempiere.test.assertj\generated\org.idempiere.test.jar
	at aQute.bnd.osgi.Jar.<init>(Jar.java:138)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:202)
	at bndtools.tasks.JarFileCapReqLoader.getBuilder(JarFileCapReqLoader.java:21)
	at bndtools.tasks.BndBuilderCapReqLoader.load(BndBuilderCapReqLoader.java:56)
	at bndtools.tasks.BndBuilderCapReqLoader.loadCapabilities(BndBuilderCapReqLoader.java:92)
	at bndtools.tasks.AnalyseBundleResolutionJob.run(AnalyseBundleResolutionJob.java:61)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
However, this error does not directly mention the root cause of the problem. Because my eyes are normally drawn to the end of the path (which also had an issue), it was a while before I noticed that it was in the `C:\workspace\idempiere-test-workspace` directory when it should have been in the `C:\workspace\idempiere-test` directory (where the Bnd workspace is). 

It should be a fairly simple matter for Bndtools to place some kind of error marker on a project when it finds that it is not in the Bnd workspace - that would have saved me a good hour or so trying to track down the cause of this issue.

**Comment by kriegfrj** [comment]
This bit me again today...
