### ISSUE TITLE
eclipse bndtools - Resolve throws NPE

### ISSUE THREAD

**Issue by jafferh** [bndtools/bnd#4269]
When you click Resolve you get the following NPE:

'Display Resolution Results' has encountered a problem
An internal error has occurred.
java.lang.NullPointerException

Any quick remedy?

Details below:

eclipse version 2020.03
bndtools version 5.1.2.REL
OS LINUX (UBUNTU 20.4)
![image](https://user-images.githubusercontent.com/11848646/90229247-8d728a80-de52-11ea-910f-e3475d783e7a.png)

**Comment by bjhargrave** [comment]
Please see if this issue occurs with the current development snapshot. See <https://github.com/bndtools/bnd#using-the-latest-development-snapshot-build-of-bndbndtools> for how to get the development snapshot builds.

**Comment by scottslewis** [comment]
I have retried and now get the expected UI

![image](https://user-images.githubusercontent.com/159988/90285398-ac5c2700-de28-11ea-8c0b-dbe12a8ff73c.png)

Question:   When 'Keep Resolver log file after Cancel' is selected, where does the file go?  (doesn't appear to be in working dir/workspace

**Comment by scottslewis** [comment]
FWIW:

For the resolution hanging described above...it turns out that third-party bundle (fasterxml)...included in the ECF jaxrs distribution provider...is importing javax.ws.rs.core package.   Apache aries exposes javax.ws.rs.core, but apparently of an older version.  The distribution provider also includes a newer version of javax.ws.rs.core.

What I don't understand:  why is this a problem for the bndtools resolve?  The more recent version of javax.ws.rs.core is the one that should be resolved to, and is without any trouble when (equinox) framework is started.    

I can easily work-around this problem by adding the following to my bndrun templates:

-runblacklist: bnd.identity;id='org.apache.aries.javax.jax.rs-api'

this prevents the aries version of javax.ws.rs.core from being considered by the resolve...and everything resolves properly.   Thought you might want to know.

Chain 1:
  com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider [com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider version=2.10.1]
    import: (&(osgi.wiring.package=javax.ws.rs.core)(version>=2.0.0)(!(version>=2.2.0)))
     |
    export: osgi.wiring.package: javax.ws.rs.core
  org.apache.aries.javax.jax.rs-api [org.apache.aries.javax.jax.rs-api version=1.0.0]

Chain 2:
  com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider [com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider version=2.10.1]
    import: (&(osgi.wiring.package=javax.ws.rs.ext)(version>=2.0.0)(!(version>=2.2.0)))
     |
    export: osgi.wiring.package=javax.ws.rs.ext; uses:=javax.ws.rs.core
  org.apache.aries.javax.jax.rs-api [org.apache.aries.javax.jax.rs-api version=1.0.1]
    import: (&(osgi.wiring.package=javax.ws.rs.core)(version>=2.1.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package: javax.ws.rs.core
  org.apache.aries.javax.jax.rs-api [org.apache.aries.javax.jax.rs-api version=1.0.1])

**Comment by jafferh** [comment]
@bjhargrave and @scottslewis Thanks for quickly into this matter.

I removed bndtools version 5.1.2 REL and as @bjhargrave suggested, I added the current development snapshot (5.2.0.DEV-20200814...) but still the NPE persists when I press the Resolve button. Instead of displaying resolution results dialogue-box the system displays the message
'Display Resolution Results' has encountered a problem, the error details show a NPE. 

As @scottslewis suggested, I also added the line "-runblacklist: bnd.identity;id='org.apache.aries.javax.jax.rs-api': to my BND template. 
Still no joy and the NPE persists.

Not sure if it's relevant but just mentioning:
* I also see the following messages on the console. 

log4j:WARN No appenders could be found for logger (org.eclipse.jgit.internal.storage.file.FileSnapshot).
log4j:WARN Please initialize the log4j system properly.
SWT Webkit: Warning, You are using an old version of webkitgtk. (pre 2.4) BrowserFunction functionality will not be avaliable
SWT WebKit: error initializing DBus server, dBusServer == 0
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

log4j:WARN No appenders could be found for logger (org.eclipse.jgit.internal.storage.file.FileSnapshot).
log4j:WARN Please initialize the log4j system properly.
SWT Webkit: Warning, You are using an old version of webkitgtk. (pre 2.4) BrowserFunction functionality will not be avaliable
SWT WebKit: error initializing DBus server, dBusServer == 0
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(Eclipse:2138): Gtk-WARNING **: 14:03:58.775: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:2138): Gtk-CRITICAL **: 14:04:11.101: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Eclipse:2138): Gtk-CRITICAL **: 14:04:27.600: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Eclipse:2138): Gtk-CRITICAL **: 14:11:17.889: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Eclipse:2138): Gtk-CRITICAL **: 14:11:17.890: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
log4j:WARN No appenders could be found for logger (org.eclipse.jgit.internal.storage.file.FileSnapshot).
log4j:WARN Please initialize the log4j system properly.

(Eclipse:2835): Gtk-WARNING **: 14:28:58.439: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

**Comment by jafferh** [comment]
@scottslewis and @bjhargrave 
Eclipse error log from my last session:
!SESSION 2020-08-15 14:20:19.373 -----------------------------------------------
eclipse.buildId=4.15.0.I20200305-0155
java.version=1.8.0_265
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  -product org.eclipse.epp.package.javascript.product
Command-line arguments:  -data file:/home/jafferh/sws-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.javascript.product

!ENTRY org.eclipse.jface 2 0 2020-08-15 14:20:24.970
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2020-08-15 14:20:24.970
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@553fbe94,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6abe62bb,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY bndtools.core 1 0 2020-08-15 14:20:33.292
!MESSAGE Download https://repo.maven.apache.org/maven2/net/sourceforge/htmlunit/htmlunit-osgi/2.35.0/htmlunit-osgi-2.35.0.jar

!ENTRY org.eclipse.ui 4 4 2020-08-15 14:21:07.354
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.NullPointerException
	at org.bndtools.core.resolve.ResolutionResult.getResolutionException(ResolutionResult.java:48)
	at org.bndtools.core.resolve.ui.ResolutionFailurePanel.setInput(ResolutionFailurePanel.java:115)
	at org.bndtools.core.resolve.ui.ResolutionResultsWizardPage.updateUi(ResolutionResultsWizardPage.java:120)
	at org.bndtools.core.resolve.ui.ResolutionResultsWizardPage.createControl(ResolutionResultsWizardPage.java:69)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:635)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at bndtools.editor.BndEditor$2$1.runInUIThread(BndEditor.java:387)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4930)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4451)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
