### ISSUE TITLE
Getting some exception in thread issue in Eclipse. How do I fix?

### ISSUE THREAD

**Issue by DarkA189** [bndtools/bnd#4344]
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Ref
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.adobe.pe.notify.VValuePurgeable.<init>(VValuePurgeable.java:92)
	at com.adobe.acrobat.gui.VOrnamentList.<init>(VOrnamentList.java:16)
	at com.adobe.acrobat.gui.PageView$VGalleyOrnaments.<init>(PageView.java:1083)
	at com.adobe.acrobat.gui.PageView.<init>(PageView.java:1081)
	at com.adobe.acrobat.gui.AcroViewContext.commonInit(AcroViewContext.java:166)
	at com.adobe.acrobat.gui.AcroViewContext.<init>(AcroViewContext.java:99)
	at com.adobe.acrobat.Viewer.createViewer(Viewer.java:243)
	at com.adobe.acrobat.Viewer.<init>(Viewer.java:211)
	at Test.<init>(Test.java:17)
	at Test.main(Test.java:48)
Caused by: java.lang.ClassNotFoundException: sun.misc.Ref
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more

**Comment by bjhargrave** [comment]
I am not sure what this question has to do with Bnd or Bndtools, but usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.
