### ISSUE TITLE
[resolver] NPE during resolve

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4416]
Caused by: java.lang.NullPointerException
	at biz.aQute.resolve.AbstractResolveContext.findProviders(AbstractResolveContext.java:291)
	at biz.aQute.resolve.AbstractResolveContext.getResources(AbstractResolveContext.java:652)
	at biz.aQute.resolve.AbstractResolveContext.getResources(AbstractResolveContext.java:644)
	at biz.aQute.resolve.AbstractResolveContext.getHighestResource(AbstractResolveContext.java:627)
	at biz.aQute.resolve.BndrunResolveContext.loadFramework(BndrunResolveContext.java:274)
	at biz.aQute.resolve.BndrunResolveContext.init(BndrunResolveContext.java:210)
	... 14 more

I had one bundle in my `-runrequires`. Seems repeatable.

**Comment by kriegfrj** [comment]
I've tried it on a different .bndrun (same workspace) - same error.

**Comment by bjhargrave** [comment]
Mmmm. Looks like a Repository implementation is not following the spec and is returning null instead of an empty map. I had removed some pointless null checks since the spec does not allow a null return.

Can you please provide a small github repo which demonstrates the problem? Then I can investigate. Thanks.

**Comment by bjhargrave** [comment]
From looking at the code, I can see both BndPomRepository and MavenBndRepository can return an invalid empty map when called before init() is complete. I will fix.

**Comment by kriegfrj** [comment]
Just confirming that #4417 seems to have resolved this issue (pun intended).
