### ISSUE TITLE
[launcher] When launching a test in Bndtools properties is empty

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4549]
I updated to the latest Bndtools snapshot, tried to run `bndtools.core.test/test.win32_x86_64.bndrun` using the Bnd OSGi Test Launcher, and I got the following error on the console:

```
! Unexpected error in the run body: null
java.lang.NullPointerException
	at java.util.StringTokenizer.<init>(StringTokenizer.java:199)
	at java.util.StringTokenizer.<init>(StringTokenizer.java:221)
	at aQute.launcher.constants.LauncherConstants.split(LauncherConstants.java:159)
	at aQute.launcher.constants.LauncherConstants.<init>(LauncherConstants.java:137)
	at aQute.launcher.Launcher.launch(Launcher.java:392)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
java.lang.NullPointerException
	at aQute.launcher.Launcher.trace(Launcher.java:1562)
	at aQute.launcher.Launcher.launch(Launcher.java:460)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

I have traced this through and it seems that the launch.properties file is completely empty. It is like the properties are not loaded before `ProjectLauncherImpl.writeProperties()` is called. Makes it hard to do testing.

It also seems that this error doesn't happen if I launch the same .bndrun file with the regular Bnd OSGi Launcher (not the test launcher).

I suspect this has something to do with #4470 or #4480 (or both). It isn't happening when I run from https://github.com/bjhargrave/bnd/tree/enable-test.

**Comment by bjhargrave** [comment]
@rotty3000 It seems your changes to the launcher to fix the remote agent has led to a regression. Should we back out your PR while you investigate?

**Comment by rotty3000** [comment]
Sure 👍

**Comment by rotty3000** [comment]
@kriegfrj when you get an opportunity could you just confirm that the revert did indeed solve this for you? Thx.

**Comment by kriegfrj** [comment]
For posterity (as I reported this on Slack but forgot to report it here): I did check out @rotty3000 's revert and it did solve this issue for me. Thank you @rotty3000 for fixing this swiftly (all the best for the permanent fix!)
