### ISSUE TITLE
LaunchPad not working with OSGi R8 Felix

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4550]
The recent version (`7.0.0`) of Felix framework bundle doesn't work with LaunchPad `5.2.0`. It always encounters the following NPE.

```
java.lang.NullPointerException
	at org.apache.felix.framework.Felix$SystemBundleActivator.stop(Felix.java:5284)
	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:847)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2822)
	at org.apache.felix.framework.Felix.init(Felix.java:969)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at aQute.launchpad.Launchpad.<init>(Launchpad.java:134)
	at aQute.launchpad.LaunchpadBuilder.create(LaunchpadBuilder.java:287)
	at aQute.launchpad.LaunchpadBuilder.create(LaunchpadBuilder.java:248)
```

**Comment by amitjoy** [comment]
Ignore at as the problem underlies somewhere else. The problem was that the classpath contained OSGi R7 instead of R8.
