### ISSUE TITLE
Command Junit with Launchpad

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#4634]
i tried to run `bnd.jar junit` on this https://github.com/bndtools/bnd/tree/master/biz.aQute.launchpad.tests

this results in:
```
Errors
000: Exception: java.lang.NullPointerException
	at aQute.bnd.build.JUnitLauncher.launch(JUnitLauncher.java:66)
	at aQute.bnd.build.Project.junit(Project.java:2541)
	at aQute.bnd.main.bnd.lambda$_junit$4(bnd.java:1057)
	at aQute.bnd.main.bnd.perProject(bnd.java:937)
	at aQute.bnd.main.bnd.perProject(bnd.java:917)
	at aQute.bnd.main.bnd._junit(bnd.java:1057)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd._bnd(bnd.java:444)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:157)
	at aQute.bnd.main.bnd.start(bnd.java:292)
	at aQute.bnd.main.bnd.main(bnd.java:269)

001: NullPointerException
```

**Comment by bjhargrave** [comment]
To run those tests, run `./gradlew :biz.aQute.launchpad.tests:test`. 

I don't know anything about the bnd junit command or if it is tested or even works. Looking at JUnitLauncher, it seems somewhat incorrect in multiple ways. I think it is basically dead code.

**Comment by stbischof** [comment]
There are some people that like bnd command's more than grade. They came up with the question about this command. So i though easiest way to test is project.. just to have something to reproduce the problem.

But i think we should either fix this or remove the command.

Afaik they use the paralle build and run command quiet often.

**Comment by bjhargrave** [comment]
If the command is broken, then it can certainly be fixed and some tests added to make sure it stays fixed.

As for the Bnd build itself, you must use the gradle build to build and test Bnd.
