### ISSUE TITLE
[quickfix test] AssertJ 3.20.2 causes issues with tests

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4766]
If you resolve the test bndruns in `bndtools.core.test`, they swap the 3.19.0 version (currently in the committed version of -runbundles) with 3.20.2.

The tests fail spectacularly as a result:

```
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder.runnerForClass(DefensiveAllDefaultPossibilitiesBuilder.java:58)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolveTestClass(ClassSelectorResolver.java:66)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:47)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:44)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:63)
	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.lambda$64(BundleSelectorResolver.java:588)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.computeChildren(BundleSelectorResolver.java:585)
	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.lambda$35(BundleSelectorResolver.java:276)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.resolve(BundleSelectorResolver.java:270)
	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.resolve(BundleSelectorResolver.java:103)
	at aQute.tester.bundle.engine.BundleEngine.discover(BundleEngine.java:63)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at aQute.tester.junit.platform.Activator.test(Activator.java:438)
	at aQute.tester.junit.platform.Activator.automatic(Activator.java:344)
	at aQute.tester.junit.platform.Activator.run(Activator.java:216)
	at java.lang.Thread.run(Thread.java:748)
```

This exception is thrown by the Vintage engine. The Vintage engine doesn't actually need to be loaded for this test, and the problem goes away if I set the AssertJ version back to 3.19.0. Nevertheless there are a few questions that are worth investigating here:

1. Why does AssertJ 3.20.2 cause the test to fail? I suspect because there is a use conflict.
2. Why is the Jupiter engine seemingly not running at all? Could also be due to the same use conflict.
3. Is there anything the tester could do to improve the user experience by making the root cause of this problem more obvious?

**Comment by bjhargrave** [comment]
>     1. Why does AssertJ 3.20.2 cause the test to fail?

This version of assertj requires a later version of JUnit (5.7) than is used in the version of Eclipse we are running (5.6). It uses something not present in 5.6. When I updated the build to use the later version of assertj, I ran into this issue. This led me to keep assertj at 3.19 in the bndruns.

See https://github.com/bndtools/bnd/commit/0c2202d5892bf7ea6fed866e665d51dec22e4ca7

**Comment by kriegfrj** [comment]
> This version of assertj requires a later version of JUnit (5.7) than is used in the version of Eclipse we are running (5.6). It uses something not present in 5.6. When I updated the build to use the later version of assertj, I ran into this issue. This led me to keep assertj at 3.19 in the bndruns.
> 

Yes, that is the root cause. Also, because AssertJ allows the JUnit-platform imports to be optional, it still happily loads and runs.

The error is triggering when the engine tries to resolve the test class' annotations. The ArrayStoreException is caused because of a `ClassNotFoundException` when trying to load `@TestInstancePostProcessor`, which is one of the annotations on `SoftAssertionsExtension`.

It seems that `JupiterEngine` silently swallows this exception and skips the class in question. The `VintageEngine` is not so silent, but the root cause is the same.

We already attempt to fully resolve the test class before handing off to the sub-engines here:
https://github.com/bndtools/bnd/blob/a0959d3a67af9a200d39ac48c993fbfef86c9447/biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java#L374-L391

The user experience in this case could be improved by resolving the annotations before handing off to the test engine.
