### ISSUE TITLE
Bndtools: java.lang.Error: SWT Resource was not properly disposed

### ISSUE THREAD

**Issue by ideas-into-software** [bndtools/bnd#4870]
A lot of these errors, on both Ubuntu 20.04 and Fedora 32/34. Partial stack trace:

```
!ENTRY org.eclipse.ui.ide 4 4 2021-10-01 00:57:31.019
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:653)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:274)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:287)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:265)
	at bndtools.utils.JavaContentProposalLabelProvider.<init>(JavaContentProposalLabelProvider.java:11)
	at bndtools.editor.contents.GeneralInfoPart.createSection(GeneralInfoPart.java:124)
	at bndtools.editor.contents.GeneralInfoPart.<init>(GeneralInfoPart.java:85)
	at bndtools.editor.pages.BundleContentPage.createLeftPanel(BundleContentPage.java:100)
	at bndtools.editor.pages.BundleContentPage.createFormContent(BundleContentPage.java:83)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at bndtools.editor.BndEditor.showHighestPriorityPage(BndEditor.java:487)
	at bndtools.editor.BndEditor.addPages(BndEditor.java:450)
```
### Setup summary

**Eclipse IDE**: 
 * Version 2021-06 (4.20.0)
 * Build id: 20210612-2011 )

**Bndtools**: 6.0.0.DEV-202108100544-g3260ebd

**OS**: 
 * Ubuntu 20.04 LTS – running as VM via KVM
 * Fedora 32, Fedora 34 – host systems

**Hardware**: 
 * Fedora 34: Dell Precision 7560, Intel® Xeon(R) W-11855M CPU, 32 GB RAM, M.2 SSD disks
 * Fedora 32: Dell Precision 7520, Intel® Core™ i7-7820HQ CPU, 32 GB RAM, M.2 SSD disks 

Hardware is definitely not the bottleneck. It may be that OS / driver issues are causing some of these, but then again, those issues can be seen on both host systems (Fedora 34, Fedora 32) as well as when running on Ubuntu 20.04 LTS (guest VM, via KVM).

In case more details are needed, I’m attaching Eclipse IDE configuration details ("Help" -> "About Eclipse IDE" -> "Installation Details" -> "Configuration" tab).

### Background

I combed through Eclipse logs (workspace .metadata/.log), looking for causes of issues I’m experiencing, and I identified 5 different errors which repeatedly are seen in those logs.

Those may or may not be related, for some there are may be already separate issues created, so in that case simply mark this as duplicate and use the info attached as needed.

Also attached are screenshots that I periodically take when some of these Eclipse IDE / Bndtools issues manifest themselves as tremendous slow down / hanging of entire Eclipse IDE or, in worst cases, as crashing of `gnome-shell`.

Some of the errors happen in rapid succession – i.e. same error being seen in logs repeatedly at micro-second intervals.
These errors often damage entire workspace – i.e. despite no errors in code, project suddenly stops working, refreshing / cleaning / rebuilding / reloading does not help and only when new workspace is created and projects re-imported everything works again.

Again, these issues can be seen regardless if running directly on host systems (Fedora 34, Fedora 32) or on Ubuntu 20.04 LTS (guest VM, via KVM).

For each of the errors mentioned, samples of stack traces are included. 

As per @juergen-albert request, filling this, hoping this may help with improving Bnd/Bndtools even further.

[Bndtools_SWT-Resource-was-not-properly-disposed_log-samples.txt](https://github.com/bndtools/bnd/files/7267494/Bndtools_SWT-Resource-was-not-properly-disposed_log-samples.txt)
[eclipse-20210612-2011_bndtools-6.0.0.DEV_configuration.txt](https://github.com/bndtools/bnd/files/7267500/eclipse-20210612-2011_bndtools-6.0.0.DEV_configuration.txt)
[eclipse_bndtools_issues.screenshots.zip](https://github.com/bndtools/bnd/files/7267506/eclipse_bndtools_issues.screenshots.zip)

**Comment by ideas-into-software** [comment]
BTW: In case these issues may be related somehow, here are all 5 filed today: 
 * Bndtools: java.lang.Error: SWT Resource was not properly disposed #4870 (https://github.com/bndtools/bnd/issues/4870)
 * Bndtools: java.lang.IllegalStateException: Already closed MavenBndRepository (https://github.com/bndtools/bnd/issues/4871)
 * Bndtools: Error querying Bnd dependency source containers #4872 (https://github.com/bndtools/bnd/issues/4872)
 * Bndtools: Error stopping startup participant #4873 (https://github.com/bndtools/bnd/issues/4873)
 * Bndtools: Unhandled event loop exception #4874 (https://github.com/bndtools/bnd/issues/4874)

**Comment by pkriens** [comment]
The PR #4926 is supposed to fix this. However, it is a big change so we should keep our eyes open

**Comment by chrisrueger** [comment]
I noticed this on recent bndtools 6.1. Should I open a new issues?

**Eclipse:** 
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

**Bndtools**	
6.1.0.REL-202111221555-g6b7087b

There are few bndtools refs in the stacktrace.

```
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:771)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:274)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:287)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:265)
	at org.bndtools.core.ui.icons.Icons.image(Icons.java:134)
	at bndtools.model.resolution.RequirementWrapperLabelProvider.update(RequirementWrapperLabelProvider.java:31)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:957)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:126)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1035)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2109)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:851)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:829)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:777)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1597)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:780)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1582)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:363)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1576)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at bndtools.editor.contents.BundleCalculatedImportsPart$5.lambda$done$0(BundleCalculatedImportsPart.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4262)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3885)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```
