### ISSUE TITLE
Bndtools: Error querying Bnd dependency source containers

### ISSUE THREAD

**Issue by ideas-into-software** [bndtools/bnd#4872]
A lot of these errors, on both Ubuntu 20.04 and Fedora 32/34. Partial stack trace:

```
!ENTRY bndtools.core 4 0 2021-09-30 00:14:58.466
!MESSAGE Error querying Bnd dependency source containers.
!STACK 0
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, org.eclipse.debug.core.sourcelookup.ISourceContainer
	at java.base/java.util.stream.SpinedBuffer.copyInto(SpinedBuffer.java:198)
	at java.base/java.util.stream.Nodes$SpinedNodeBuilder.copyInto(Nodes.java:1298)
	at java.base/java.util.stream.SpinedBuffer.asArray(SpinedBuffer.java:215)
	at java.base/java.util.stream.Nodes$SpinedNodeBuilder.asArray(Nodes.java:1304)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:518)
	at bndtools.launch.sourcelookup.containers.BndrunDirectiveSourceContainer.createSourceContainers(BndrunDirectiveSourceContainer.java:126)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.getSourceContainers(CompositeSourceContainer.java:125)
	at bndtools.launch.sourcelookup.containers.BndDependencySourceContainer.hasChildren(BndDependencySourceContainer.java:58)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at bndtools.launch.sourcelookup.containers.BndDependencySourceContainer.createSourceContainers(BndDependencySourceContainer.java:82)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.getSourceContainers(CompositeSourceContainer.java:125)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.findSourceElements(CompositeSourceContainer.java:46)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupParticipant.findSourceElements(AbstractSourceLookupParticipant.java:65)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:138)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:473)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:714)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:336)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:703)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
### Setup summary

**Eclipse IDE**: 
 * Version 2021-06 (4.20.0)
 * Build id: 20210612-2011 )

**Bndtools**: 6.0.0.DEV-202108100544-g3260ebd

**OS**: 
 * Ubuntu 20.04 LTS – running as VM via KVM
 * Fedora 32, Fedora 34 – host systems

**Hardware**: 
 * Fedora 34: Dell Precision 7560, Intel® Xeon(R) W-11855M CPU, 32 GB RAM, M.2 SSD disks
 * Fedora 32: Dell Precision 7520, Intel® Core™ i7-7820HQ CPU, 32 GB RAM, M.2 SSD disks 

Hardware is definitely not the bottleneck. It may be that OS / driver issues are causing some of these, but then again, those issues can be seen on both host systems (Fedora 34, Fedora 32) as well as when running on Ubuntu 20.04 LTS (guest VM, via KVM).

In case more details are needed, I’m attaching Eclipse IDE configuration details ("Help" -> "About Eclipse IDE" -> "Installation Details" -> "Configuration" tab).

### Background

I combed through Eclipse logs (workspace .metadata/.log), looking for causes of issues I’m experiencing, and I identified 5 different errors which repeatedly are seen in those logs.

Those may or may not be related, for some there are may be already separate issues created, so in that case simply mark this as duplicate and use the info attached as needed.

Also attached are screenshots that I periodically take when some of these Eclipse IDE / Bndtools issues manifest themselves as tremendous slow down / hanging of entire Eclipse IDE or, in worst cases, as crashing of `gnome-shell`.

Some of the errors happen in rapid succession – i.e. same error being seen in logs repeatedly at micro-second intervals.
These errors often damage entire workspace – i.e. despite no errors in code, project suddenly stops working, refreshing / cleaning / rebuilding / reloading does not help and only when new workspace is created and projects re-imported everything works again.

Again, these issues can be seen regardless if running directly on host systems (Fedora 34, Fedora 32) or on Ubuntu 20.04 LTS (guest VM, via KVM).

For each of the errors mentioned, samples of stack traces are included. 

As per @juergen-albert request, filling this, hoping this may help with improving Bnd/Bndtools even further.

[Bndtools_Error-querying-Bnd-dependency-source-containers_log-samples.txt](https://github.com/bndtools/bnd/files/7267555/Bndtools_Error-querying-Bnd-dependency-source-containers_log-samples.txt)
[eclipse-20210612-2011_bndtools-6.0.0.DEV_configuration.txt](https://github.com/bndtools/bnd/files/7267556/eclipse-20210612-2011_bndtools-6.0.0.DEV_configuration.txt)
[eclipse_bndtools_issues.screenshots.zip](https://github.com/bndtools/bnd/files/7267557/eclipse_bndtools_issues.screenshots.zip)

**Comment by kriegfrj** [comment]
Thanks for the report.

What sort of workspace are you working with? Bnd workspace, or a Maven workspace using Bndtoos/m2e?

**Comment by ideas-into-software** [comment]
Hi. It is a BND workspace. Regards

**Comment by ideas-into-software** [comment]
BTW: In case these issues may be related somehow, here are all 5 filed today: 
 * Bndtools: java.lang.Error: SWT Resource was not properly disposed #4870 (https://github.com/bndtools/bnd/issues/4870)
 * Bndtools: java.lang.IllegalStateException: Already closed MavenBndRepository (https://github.com/bndtools/bnd/issues/4871)
 * Bndtools: Error querying Bnd dependency source containers #4872 (https://github.com/bndtools/bnd/issues/4872)
 * Bndtools: Error stopping startup participant #4873 (https://github.com/bndtools/bnd/issues/4873)
 * Bndtools: Unhandled event loop exception #4874 (https://github.com/bndtools/bnd/issues/4874)
