### ISSUE TITLE
NullPointerException when attempting to resolve a bndrun file

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#5055]
I have a maven workspace with a bndrun file (used for testing) which I can't resolve due to an NPE inside Bndtools. I'm using `6.1.0.REL-202111221555-g6b7087b`

```
Exception during resolution.
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because the return value of "java.util.Map.get(Object)" is null
	at biz.aQute.resolve.BndrunResolveContext.init(BndrunResolveContext.java:237)
	at biz.aQute.resolve.AbstractResolveContext.initAndReport(AbstractResolveContext.java:130)
	at biz.aQute.resolve.AbstractResolveContext.getMandatoryResources(AbstractResolveContext.java:149)
	at org.apache.felix.resolver.ResolverImpl$ResolveSession.initMandatoryAndOptionalResources(ResolverImpl.java:125)
	at org.apache.felix.resolver.ResolverImpl$ResolveSession.createSession(ResolverImpl.java:102)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:32)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:82)
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:101)
	at org.bndtools.core.resolve.ResolveOperation.lambda$run$0(ResolveOperation.java:57)
	at org.bndtools.core.resolve.ResolveOperation.coordinate(ResolveOperation.java:96)
	at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:51)
	at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because the return value of "java.util.Map.get(Object)" is null
	at aQute.bnd.osgi.repository.AugmentRepository.findProviders(AugmentRepository.java:43)
	at biz.aQute.resolve.AbstractResolveContext.findProviders(AbstractResolveContext.java:290)
	at biz.aQute.resolve.AbstractResolveContext.getResources(AbstractResolveContext.java:653)
	at biz.aQute.resolve.AbstractResolveContext.getResources(AbstractResolveContext.java:645)
	at biz.aQute.resolve.AbstractResolveContext.getHighestResource(AbstractResolveContext.java:628)
	at biz.aQute.resolve.BndrunResolveContext.loadFramework(BndrunResolveContext.java:278)
	at biz.aQute.resolve.BndrunResolveContext.init(BndrunResolveContext.java:214)
	... 14 more
```

**Comment by timothyjward** [comment]
I managed to stop the error by excluding two unused transitive dependencies that couldn't be located in any repository. After this the resolve succeeded.
