### ISSUE TITLE
bnd-maven-plugin: Allow resolving -includeresource instructions referencing jars built from other Eclipse Workspace projects

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5081]
If you have multiple projects inside Eclipse and project B has a dependency towards project A via the instruction 

```
@<JAR name of project A.jar>!/<some class name in A>
```

this leads to the following m2e error when the JAR file has not yet been built:

```
Can not find JAR file '<JAR name of project A.jar>' (biz.aQute.bnd:bnd-maven-plugin:6.1.0:bnd-process:generate-osgi-metadata:process-classes)

org.apache.maven.plugin.MojoFailureException: Can not find JAR file '<JAR name of project A.jar>'
	at aQute.bnd.maven.plugin.AbstractBndMavenPlugin.reportErrorsAndWarnings(AbstractBndMavenPlugin.java:661)
	at aQute.bnd.maven.plugin.AbstractBndMavenPlugin.execute(AbstractBndMavenPlugin.java:483)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:336)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1423)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1422)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:55)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:156)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:103)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:198)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Although the error is correct it would be nice if the bnd-maven-plugin could somehow detect that this belongs to another Eclipse project in the same workspace and use its target folder instead of the jar.

You can reproduce e.g. with https://github.com/apache/jackrabbit-filevault and its https://github.com/apache/jackrabbit-filevault/blob/1bd9f9fa825e86133eaae222544e8c39ba7970ee/vault-validation/bnd.bnd#L20

**Comment by rotty3000** [comment]
Just add a project dependency of type `provided` and that should work :)

**Comment by kwin** [comment]
I have already a dependency at https://github.com/apache/jackrabbit-filevault/blob/1bd9f9fa825e86133eaae222544e8c39ba7970ee/vault-validation/pom.xml#L103-L107, but with default scope `compile`. Any reason why only `provided` works?

**Comment by rotty3000** [comment]
ah no, `compile` is fine, I just assumed that since you are embedding it only needed to be provided :) so... it should work.
Ok the issue is with the format of your regex :| this changed between versions of bnd way in the 4.x.y days.

Change it to something like `org.apache.jackrabbit.vault-[0-9.]*(-SNAPSHOT)?.jar` please and try again.

**Comment by kwin** [comment]
Still not working:

```
Can not find JAR file 'org.apache.jackrabbit.vault-[0-9.]*(-SNAPSHOT)?.jar' (biz.aQute.bnd:bnd-maven-plugin:6.1.0:bnd-process:generate-osgi-metadata:process-classes)
```

**Comment by rotty3000** [comment]
hmm, @kwin is that the real file name of the artifact in question? though it looks like it is :( not sure why this isn't working for you. We have test cases that specifically do this link of operation: 

Usage: https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-wrapper-bundle/bnd/wrapper.bnd
Verification: https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-wrapper-bundle/verify.groovy#L39

**Comment by kwin** [comment]
Notice that I am only relying on bnd-maven-plugin but not bndtools. Which Eclipse plugin/feature is necessary for this workspace resolution?

**Comment by bjhargrave** [comment]
In command line maven, maven always supplies artifact files which are
the built jar. Either in m2 or in a project's target folder.

However, in m2e, probably since the jar goal is not normally executed,
the artifact file for another project in the reactor is for the project's
target/classes folder. This causes jar name matching in
-includeresource to fail since it matched on the file name and all the
file names for these project's artifact is "classes".

**Comment by kriegfrj** [comment]
There might be some overlap with what I'm trying to do here in #3175.

**Comment by bjhargrave** [comment]
> There might be some overlap with what I'm trying to do here in #3175.

I don't think so. This is about finding a jar on the classpath when the classpath does not hold the jar because m2e put the classes folder there.

**Comment by kriegfrj** [comment]
> > There might be some overlap with what I'm trying to do here in #3175.
> 
> I don't think so. This is about finding a jar on the classpath when the classpath does not hold the jar because m2e put the classes folder there.

I just re-read what you wrote and I agree, this is a separate problem.
