### ISSUE TITLE
Building bnd project never ends

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#5112]
I have bnd on Windows Eclipse:
Version: 2021-12 (4.22.0)
Build id: 20211202-163
with AdoptJDK 11
Bndtools 6.1.0.REL-202111221555-g6b7087b

I use a bnd 6.1 workspace from the template. During building a project the build stucks at 75%

I attached JMC and found that the Thread "Worker-52: Building" waits for Lock "0x000000070ab21100", as well as some other bnd thread: Bnd-Executor,pool-3-thread-1510, Bnd-Executor,pool-3-thread-1512

You'll find a threaddump attached. 

It is not reproducable, but I experienced such situation several times

**Comment by maho7791** [comment]
[bndbuild-threaddump.txt](https://github.com/bndtools/bnd/files/8081167/bndbuild-threaddump.txt)

**Comment by bjhargrave** [comment]
Locking has changed a _lot_ in Bnd/Bndtools 6.2. I would suggest you start using the 6.2.0 RC builds and see if you still have issues.

**Comment by maho7791** [comment]
I will install 6.2 RC

**Comment by kriegfrj** [comment]
A quick look at the thread dump suggests that it has to do with the PomRepository. A lot of threads are blocked in aQute.bnd.repository.maven.pom.provider.PomRepository.save(PomRepository.java:92), there are a few blocked at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:330), and the build thread itself is blocked:

```
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.init(BndPomRepository.java:91)
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.versions(BndPomRepository.java:323)
	at aQute.bnd.build.Project.getBundle(Project.java:1299)
	at aQute.bnd.build.Project.getBundles(Project.java:679)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:578)
	at aQute.bnd.build.Project.prepare(Project.java:420)
	- locked <0x0000000702979038> (a java.util.concurrent.atomic.AtomicBoolean)
	at aQute.bnd.build.Project.getBuildpath(Project.java:937)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateProjectClasspath(BndContainerInitializer.java:308)
```

So it appears to be unrelated to #5110. Hopefully it has already been fixed in 6.2 with @bjhargrave 's changes.

**Comment by bjhargrave** [comment]
This looks like a networking problem. There are multiple (4) threads waiting on network requests;

```
	at org.osgi.util.promise.DeferredPromiseImpl.getFailure(DeferredPromiseImpl.java:137)
	at aQute.maven.provider.MavenRemoteRepository.fetch(MavenRemoteRepository.java:56)
	at aQute.maven.provider.MavenBackingRepository.fetch(MavenBackingRepository.java:61)
	at aQute.maven.provider.MavenRepository.fetch(MavenRepository.java:197)
	at aQute.maven.provider.MavenRepository.getFile(MavenRepository.java:175)
```

```java
	public TaggedData fetch(String path, File file, boolean force) throws Exception {
		Promise<TaggedData> promise = fetch(path, file, 3, 1000L, force);
		Throwable failure = promise.getFailure(); // wait for completion
		if (failure != null) {
			throw Exceptions.duck(failure);
		}
		return promise.getValue();
	}
```

All the other threads are backed up waiting for the network fetches to complete so they can parse poms and then assemble the resources and complete the initialization of the BndPomRepository. 

However, I don't see any of the network threads (thread names would start with "HttpClient") in the dump!

So I am not sure what happened to the network threads. It is possible the thread pool is too small and they are in the executor queue awaiting dispatch. The default size is 256 and I don't see that many threads in the dump. Perhaps you have configured it to some smaller value?

```java
		final int maximumPoolSize = Integer.getInteger("bnd.executor.maximumPoolSize", 256)
			.intValue();
```

But even if those threads don't "exist", eventually the promises will timeout.

```java
	private <T> Promise<T> sendAsync(HttpRequest<T> request, int retries, long delay) {
		HttpConnection<T> connection = new HttpConnection<>(request);
		return promiseFactory().submit(connection)
			.timeout(Math.max((retries < 1) ? FINAL_TIMEOUT : INITIAL_TIMEOUT, request.timeout * 10L))

```

**Comment by bjhargrave** [comment]
It is possible that the timeouts are not happening because the ScheduledThreadPoolExecutor is also jammed up. It is configured to have only 2 threads and, in the thread dump, both threads are waiting in the polling logic of BndPomRepository which is waiting on reading. So this means any timeout operations are queued waiting for a scheduled thread pool thread.

I am thinking we want to have the promise factory use a separate ScheduledThreadPoolExecutor than other parts of Bnd.

You may also want to consider configuring your BndPomRepository(s) with `poll_time=-1` to disable polling.

**Comment by juergen-albert** [comment]
This topic bothers the hell out of me. I now have a couple of workspaces that die frequently during build/reload and one that will not even initialize anymore. 
![image](https://user-images.githubusercontent.com/8199490/154667689-834f5e05-2344-49da-9631-2113f76914e8.png)

The whole thing is usually a bit random and thus hard to get a threaddump when it happens. This is an issue we carry around since I started using bndtools. With some Versions it gotten better and then it digressed even if I did not update the bnd version. This brings me to the suspicion that it is a concurrency issue that might improve or get worse when the system around us changes. 

I found a few things that might be separate problems that lead to such issues:

One of the culprits is usually the BndPomRepository. The init method can take quite long to return (e.g. 23 seconds for the org.osgi.enroute:impl-index:7.0.0). It is quite often that somebody waits on the initialization Promise and this never returns. 

It usually looks like this: 
```
at jdk.internal.misc.Unsafe.park(java.base@17.0.1/Native Method)
	- parking to wait for  <0x000000009bdd1268> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.1/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.1/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.1/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.1/CountDownLatch.java:230)
	at org.osgi.util.promise.DeferredPromiseImpl.getValue(DeferredPromiseImpl.java:124)
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.init(BndPomRepository.java:91)
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.findProviders(BndPomRepository.java:254)
	at aQute.bnd.osgi.repository.AggregateRepository.lambda$findProviders$0(AggregateRepository.java:34)
	at aQute.bnd.osgi.repository.AggregateRepository$$Lambda$991/0x0000000100a2cf70.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(java.base@17.0.1/ReferencePipeline.java:273)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@17.0.1/ArrayList.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.1/AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.1/AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@17.0.1/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.1/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java.base@17.0.1/ReferencePipeline.java:682)
	at aQute.bnd.stream.EntryPipeline.collect(EntryPipeline.java:328)
	at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:37)
	at aQute.bnd.build.Workspace.findProviders(Workspace.java:1748)
	at aQute.bnd.build.LibraryHandler.getLibrary(LibraryHandler.java:243)
	at aQute.bnd.build.LibraryHandler.update(LibraryHandler.java:216)
	at aQute.bnd.build.Workspace.doExtend(Workspace.java:1836)
	at aQute.bnd.build.Project.propertiesChanged(Project.java:2271)
	at aQute.bnd.build.Workspace.forceInitialization(Workspace.java:529)
	at aQute.bnd.build.Workspace.open(Workspace.java:364)
	at aQute.bnd.build.Workspace.<init>(Workspace.java:310)
	at bndtools.central.Central.createWorkspace(Central.java:297)
	at bndtools.central.Central$$Lambda$592/0x00000001007b35c8.get(Unknown Source)
	at aQute.bnd.memoize.MemoizingSupplier.get(MemoizingSupplier.java:36)
	- locked <0x00000000823acbe0> (a aQute.bnd.memoize.MemoizingSupplier)
	at bndtools.central.Central.getWorkspace(Central.java:236)
	- locked <0x00000000823acbe0> (a aQute.bnd.memoize.MemoizingSupplier)
	at bndtools.central.Central.refreshPlugins(Central.java:580)
	at bndtools.views.repository.RepositoriesView$6.runInWorkspace(RepositoriesView.java:456)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

In this case it is the new library mechanism kicks it of.  Sometimes it is somebody else who wants a bundle from a repository at a different time. I believe to have seen this for the `MavenBndRepository` as well in the past, but I might mistake this with the `MavenRepository` the `BndPomRepository` uses internally.

Long story short: The picture always the same (Meaning in the case I can currently reproduce and the other issues in the past). We are waiting for a Promise but I can't find anybody actually working to resolve it. I'd expected to find some kind of `TimeoutException` or something, but I didn't.

I looked through the stack above to see if anybody eats the Exception and found https://github.com/bndtools/bnd/blob/b979cd8c7b6dd27a12633cbb7a1db5fd9da7eb54/biz.aQute.bndlib/src/aQute/bnd/build/LibraryHandler.java#L226

I hoped to see something in the eclipse console but didn't but stumbled upon another interesting stacktrace instead:

```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.compute(HashMap.java:1317)
        at aQute.bnd.build.ProjectTracker.update(ProjectTracker.java:86)
        at aQute.bnd.build.ProjectTracker.getAllProjects(ProjectTracker.java:54)
        at aQute.bnd.build.Workspace.getAllProjects(Workspace.java:556)
        at aQute.bnd.build.WorkspaceRepositoryDynamic.findProviders(WorkspaceRepositoryDynamic.java:29)
        at aQute.bnd.osgi.repository.AggregateRepository.lambda$findProviders$0(AggregateRepository.java:39)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
        at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:41)
        at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1667)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at aQute.bnd.osgi.resource.ResourceUtils.findProviders(ResourceUtils.java:796)
        at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:31)
        at aQute.bnd.build.Workspace.findProviders(Workspace.java:1763)
        at aQute.bnd.build.LibraryHandler.getLibrary(LibraryHandler.java:243)
        at aQute.bnd.build.LibraryHandler.update(LibraryHandler.java:216)
        at aQute.bnd.build.Workspace.doExtend(Workspace.java:1851)
        at aQute.bnd.build.Workspace.lambda$propertiesChanged$3(Workspace.java:508)
        at aQute.bnd.build.WorkspaceLock.locked(WorkspaceLock.java:128)
        at aQute.bnd.build.Workspace.writeLocked(Workspace.java:1525)
        at aQute.bnd.build.Workspace.propertiesChanged(Workspace.java:495)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:833)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:825)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:1054)
        at aQute.bnd.build.Workspace.setFileSystem(Workspace.java:421)
        at aQute.bnd.build.Workspace.<init>(Workspace.java:338)
        at aQute.bnd.build.Workspace.<init>(Workspace.java:313)
        at bndtools.central.Central.createWorkspace(Central.java:297)
        at aQute.bnd.memoize.MemoizingSupplier.lambda$new$1(MemoizingSupplier.java:31)
        at aQute.bnd.memoize.MemoizingSupplier.get(MemoizingSupplier.java:51)
        at bndtools.central.Central.getWorkspace(Central.java:230)
        at bndtools.central.Central.refreshPlugins(Central.java:526)
        at bndtools.views.repository.RepositoriesView$6.runInWorkspace(RepositoriesView.java:456)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This does not seem to be related to the poms that do not resolve, but might explain my not finishing Workspace initialization. 

@bjhargrave I did all this with the latest Version that should have your latest Changes included.

Here is the Threaddump where the first Stacktrace is from.  
[Threadump.txt](https://github.com/bndtools/bnd/files/8096725/Threadump.txt)

**Comment by juergen-albert** [comment]
Here is the flight record of the whole thing
[demorecording.zip](https://github.com/bndtools/bnd/files/8096736/demorecording.zip)
e

**Comment by bjhargrave** [comment]
I added support for `${project.parent.version}`  in #5116.

There is still an issue with bad checksum on Maven Central.

```
2022-02-18 14:04:15,498 [Bnd-Executor,pool-5-thread-41] INFO  a.m.provider.MavenRemoteRepository - Retrying invalid download: Invalid content checksum DDC682A2B219FCB896732E8FF3546415D708E12E for /Users/hargrave/.m2/repository/org/multiverse/multiverse-beta/0.7-RC-1/multiverse-beta-0.7-RC-1.pom; expected 7c798b9edd7a744e042def51c31eef256556eee6. delay=4000, retries=1
```

```zsh
➜  Downloads shasum -a 1 multiverse-beta-0.7-RC-1.pom
ddc682a2b219fcb896732e8ff3546415d708e12e  multiverse-beta-0.7-RC-1.pom
➜  Downloads cat multiverse-beta-0.7-RC-1.pom.sha1 
7c798b9edd7a744e042def51c31eef256556eee6
```

There is no fixing this in Bnd. Sonatype needs to fix on Maven Central.
