### ISSUE TITLE
Workspace failing to initialize

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5121]
@bjhargrave As discussed in our meeting today and [here](https://github.com/bndtools/bnd/issues/5112#issuecomment-1044375152), I uploaded the offending workspace. 

The Eclipse I used around it, is a Version: 2021-06 (4.20.0) with the latest build from bndtools (6.3.0.202202180739-SNAPSHOT at the time).

https://github.com/DataInMotion/failingWorkspace

The Stacktrace I talked about is:

```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.compute(HashMap.java:1317)
        at aQute.bnd.build.ProjectTracker.update(ProjectTracker.java:86)
        at aQute.bnd.build.ProjectTracker.getAllProjects(ProjectTracker.java:54)
        at aQute.bnd.build.Workspace.getAllProjects(Workspace.java:552)
        at aQute.bnd.build.WorkspaceRepositoryDynamic.findProviders(WorkspaceRepositoryDynamic.java:31)
        at aQute.bnd.osgi.repository.AggregateRepository.lambda$findProviders$0(AggregateRepository.java:34)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at aQute.bnd.stream.EntryPipeline.collect(EntryPipeline.java:328)
        at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:37)
        at aQute.bnd.build.Workspace.findProviders(Workspace.java:1748)
        at aQute.bnd.build.LibraryHandler.getLibrary(LibraryHandler.java:243)
        at aQute.bnd.build.LibraryHandler.update(LibraryHandler.java:216)
        at aQute.bnd.build.Workspace.doExtend(Workspace.java:1836)
        at aQute.bnd.build.Workspace.propertiesChanged(Workspace.java:509)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:830)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:822)
        at aQute.bnd.osgi.Processor.setProperties(Processor.java:1052)
        at aQute.bnd.build.Workspace.setFileSystem(Workspace.java:417)
        at aQute.bnd.build.Workspace.<init>(Workspace.java:334)
        at aQute.bnd.build.Workspace.<init>(Workspace.java:309)
        at bndtools.central.Central.createWorkspace(Central.java:297)
        at aQute.bnd.memoize.MemoizingSupplier.get(MemoizingSupplier.java:36)
        at bndtools.central.Central.getWorkspace(Central.java:236)
        at bndtools.central.Central.refreshPlugins(Central.java:580)
        at bndtools.views.repository.RepositoriesView$6.runInWorkspace(RepositoriesView.java:456)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
		
```

**Comment by bjhargrave** [comment]
```
java.lang.Error: ProjectTracker update reentered
	at aQute.bnd.build.ProjectTracker.update(ProjectTracker.java:78)
	at aQute.bnd.build.ProjectTracker.getAllProjects(ProjectTracker.java:54)
	at aQute.bnd.build.Workspace.getAllProjects(Workspace.java:556)
	at aQute.bnd.build.WorkspaceRepositoryDynamic.findProviders(WorkspaceRepositoryDynamic.java:29)
	at aQute.bnd.osgi.repository.AggregateRepository.lambda$1(AggregateRepository.java:39)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:541)
	at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:41)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Collections$2.tryAdvance(Collections.java:4719)
	at java.util.Collections$2.forEachRemaining(Collections.java:4727)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at aQute.bnd.osgi.resource.ResourceUtils.findProviders(ResourceUtils.java:796)
	at aQute.bnd.osgi.repository.AggregateRepository.findProviders(AggregateRepository.java:31)
	at aQute.bnd.build.Workspace.findProviders(Workspace.java:1763)
	at aQute.bnd.build.LibraryHandler.getLibrary(LibraryHandler.java:243)
	at aQute.bnd.build.LibraryHandler.update(LibraryHandler.java:216)
	at aQute.bnd.build.Workspace.doExtend(Workspace.java:1851)
	at aQute.bnd.build.Project.propertiesChanged(Project.java:2267)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:745)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:737)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:966)
	at aQute.bnd.osgi.Processor.setProperties(Processor.java:955)
	at aQute.bnd.build.Project.<init>(Project.java:195)
	at aQute.bnd.build.Project.<init>(Project.java:202)
	at aQute.bnd.build.ProjectTracker.lambda$2(ProjectTracker.java:105)
	at java.util.HashMap.compute(HashMap.java:1198)
	at aQute.bnd.build.ProjectTracker.update(ProjectTracker.java:94)
	at aQute.bnd.build.ProjectTracker.getAllProjects(ProjectTracker.java:54)
	at aQute.bnd.build.Workspace.open(Workspace.java:369)
	at aQute.bnd.build.Workspace.<init>(Workspace.java:314)
	at test.LibraryTest.testIncludeDirAndFileLibrary(LibraryTest.java:79)
```

**Comment by bjhargrave** [comment]
I have no problems loading the failingWorking with all my fixes in #5116. So I think I have hammered all the issues down. Once #5116 gets merged into 6.3, you will need to try it out.

**Comment by juergen-albert** [comment]
Thanks Heaps @bjhargrave! The Workspace is loading for me as well and the Exceptions are gone.
