### ISSUE TITLE
bndlib throws java.io.IOException: Pipe closed

### ISSUE THREAD

**Issue by dragank** [bndtools/bnd#532]
Using karaf 3.0.1 we are copying our kar archives into the karaf/deploy directory.
When the karaf installer tries installing a wrapped bundle the above exception is thrown by bndlib.

Our applications continue to work fine, only issue is that the stacktrace could throw false positives for DevOps team.

Had a quick look at the code and in this case, writeResource() is being called consecutively since there are more files under META-INF for some wrapped bundles, maybe this is causing the issue?

[https://github.com/bndtools/bnd/blob/2.2.0.REL/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java]

e.g. Example here where commons-logging-1.1.1.jar is being installed,

```
2014-06-28 00:40:41,418 | WARN  | Thread-42        | BndUtils                         | 3 - org.ops4j.pax.swissbox.bnd - 1.7.0 | Bundle cannot be generated
java.lang.Exception: Problem writing resource LICENSE.txt
    at aQute.bnd.osgi.Jar.writeResource(Jar.java:530)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    at aQute.bnd.osgi.Jar.write(Jar.java:307)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:194)[3:org.ops4j.pax.swissbox.bnd:1.7.0]
Caused by: java.io.IOException: Pipe closed
    at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:261)[:1.7.0_45]
    at java.io.PipedInputStream.receive(PipedInputStream.java:227)[:1.7.0_45]
    at java.io.PipedOutputStream.write(PipedOutputStream.java:149)[:1.7.0_45]
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)[:1.7.0_45]
    at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)[:1.7.0_45]
    at aQute.bnd.osgi.Jar.writeResource(Jar.java:527)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    ... 2 more
2014-06-28 00:40:41,949 | WARN  | Thread-43        | BndUtils                         | 3 - org.ops4j.pax.swissbox.bnd - 1.7.0 | Bundle cannot be generated
java.lang.Exception: Problem writing resource META-INF/LICENSE
    at aQute.bnd.osgi.Jar.writeResource(Jar.java:530)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    at aQute.bnd.osgi.Jar.write(Jar.java:307)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:194)[3:org.ops4j.pax.swissbox.bnd:1.7.0]
Caused by: java.io.IOException: Pipe closed
    at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:261)[:1.7.0_45]
    at java.io.PipedInputStream.receive(PipedInputStream.java:227)[:1.7.0_45]
    at java.io.PipedOutputStream.write(PipedOutputStream.java:149)[:1.7.0_45]
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)[:1.7.0_45]
    at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)[:1.7.0_45]
    at aQute.bnd.osgi.Jar.writeResource(Jar.java:527)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
    ... 2 more
```

**Comment by rakeshnayakg** [comment]
I see this exception often .
java.lang.Exception: Problem writing resource META-INF/maven/org.iq80.leveldb/leveldb/pom.xml
        at aQute.bnd.osgi.Jar.writeResource(Jar.java:530)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
        at aQute.bnd.osgi.Jar.write(Jar.java:307)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
        at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:194)[3:org.ops4j.pax.swissbox.bnd:1.7.0]
Caused by: java.io.IOException: Pipe closed
        at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:261)[:1.7.0_75]
        at java.io.PipedInputStream.receive(PipedInputStream.java:227)[:1.7.0_75]
        at java.io.PipedOutputStream.write(PipedOutputStream.java:149)[:1.7.0_75]
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)[:1.7.0_75]
        at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)[:1.7.0_75]
        at aQute.bnd.osgi.Jar.writeResource(Jar.java:527)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
        ... 2 more
2015-03-09 21:47:40,188 | WARN  | Thread-51        | BndUtils                         | Bundle cannot be generated
java.lang.Exception: Problem writing resource META-INF/maven/com.google.protobuf/protobuf-java/pom.xml
        at aQute.bnd.osgi.Jar.writeResource(Jar.java:530)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
        at aQute.bnd.osgi.Jar.write(Jar.java:307)[2:biz.aQute.bndlib:2.2.0.20130927-173417]
        at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:194)[3:org.ops4j.pax.swissbox.bnd:1.7.0]
Caused by: java.io.IOException: Pipe closed
        at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:261)[:1.7.0_75]
        at java.io.PipedInputStream.receive(PipedInputStream.java:227)[:1.7.0_75]
        at java.io.PipedOutputStream.write(PipedOutputStream.java:149)[:1.7.0_75]
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)[:1.7.0_75]
        at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)[:1.7.0_75]
        at aQute.bnd.osgi.Jar.writeResource(Jar.java:527)[2:biz.aQute.bndlib:2.2.0.20130927-173417]

**Comment by pkriens** [comment]
You're running this not from bndtools, gradle, or ant but in org.ops4j.pax.swissbox.bnd.BndUtils. I vaguely recall long time ago they had such a problem in their code (3-4 years?).

Since this is not a problem in all these other environments I am afraid I have to point you to the Ops4j guys :-(

Kind regards,

	Peter Kriens
