### ISSUE TITLE
SWT Invalid thread access

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#5428]
Spotted in the error log for 6.4.0.DEV . I can't see a specific issue, but we should make sure that cleanup happens on the right thread.

    org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1164)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:915)
	at org.eclipse.swt.widgets.Display.create(Display.java:899)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:132)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:753)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:744)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1498)
	at bndtools.editor.pages.RunAction.lambda$new$1(RunAction.java:21)
	at org.bndtools.facade.ExtensionServiceTracker.lambda$removedService$1(ExtensionServiceTracker.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.bndtools.facade.ExtensionServiceTracker.removedService(ExtensionServiceTracker.java:93)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:969)

**Comment by juergen-albert** [comment]
@timothyjward does this happen on shutdown?

**Comment by pkriens** [comment]
From OpenAI::

I apologize for the misunderstanding. If Display.getDefault() is still throwing a "Invalid Thread Access" error even when you are using syncExec or asyncExec, it could be because the display has not been created yet.

In Eclipse, the display is typically created when the workbench starts up. If you are trying to access the display before the workbench has started, Display.getDefault() will throw a "Invalid Thread Access" error.

To fix this, you can try delaying the execution of your code until the workbench has started. One way to do this is to use the IWorkbench.addWorkbenchListener method to add a workbench listener that will be notified when the workbench has started.

**Comment by laeubi** [comment]
`org.eclipse.ui.PlatformUI.isWorkbenchRunning()` might be more appropriate in the context of Eclipse Plugin...
