### ISSUE TITLE
IllegalStateException when validating prior to launching unit tests

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5719]
Sometimes when trying to launch JUnit tests using the Bndtools Eclipse Plugins 6.4.0, I get this error:

```
Status ERROR: org.bndtools.launch code=0 Error initialising bnd launcher java.lang.IllegalStateException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at org.apache.felix.resolver.util.ShadowList.replace(ShadowList.java:74)
	at org.apache.felix.resolver.Candidates.prepare(Candidates.java:939)
	at org.apache.felix.resolver.ResolverImpl.getInitialCandidates(ResolverImpl.java:547)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:432)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:421)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:32)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:187)
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:101)
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:76)
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:128)
	at biz.aQute.resolve.Bndrun.cache(Bndrun.java:245)
	at biz.aQute.resolve.Bndrun.getRunbundles(Bndrun.java:182)
	at aQute.bnd.build.ProjectLauncher.updateFromProject(ProjectLauncher.java:153)
	at aQute.launcher.plugin.ProjectLauncherImpl.updateFromProject(ProjectLauncherImpl.java:99)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2961)
	at aQute.bnd.build.ProjectTester.<init>(ProjectTester.java:27)
	at aQute.tester.junit.platform.plugin.ProjectTesterImpl.<init>(ProjectTesterImpl.java:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at aQute.bnd.build.Project.getHandler(Project.java:3007)
	at aQute.bnd.build.Project.getProjectTester(Project.java:2969)
	at bndtools.launch.OSGiJUnitLaunchDelegate.initialiseBndLauncher(OSGiJUnitLaunchDelegate.java:88)
	at bndtools.launch.AbstractOSGiLaunchDelegate.finalLaunchCheck(AbstractOSGiLaunchDelegate.java:177)
	at bndtools.launch.OSGiJUnitLaunchDelegate.finalLaunchCheck(OSGiJUnitLaunchDelegate.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.bndtools.facade.ExtensionFacade.invoke(ExtensionFacade.java:171)
	at jdk.proxy31/jdk.proxy31.$Proxy126.finalLaunchCheck(Unknown Source)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:792)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1040)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Sometimes the error goes away when closing some projects, refreshing the workspace or rebuilding some projects. However, it is not really clear which projects would need to be closed/refreshed/rebuilt - it is a game of luck and guess.

**Comment by pkriens** [comment]
This might be a particular setup on your site. We will need you to create an exact scenario where this happens with preferably a small repo. 

You could put on [`-resolvedebug`](https://bnd.bndtools.org/releases/6.1.0/instructions/resolvedebug.html). This could maybe provide some more diagnostic information.

**Comment by reckart** [comment]
I'll try the option next time I encounter the problem.

**Comment by pkriens** [comment]
Is it ok to close this abeyance? Without further information there is not much I can do.

**Comment by reckart** [comment]
Sure. If I reencounter the issue, I'll comment or open a new one ;)
