### ISSUE TITLE
-XstartOnFirstThread recognized as invalid vm-argument?

### ISSUE THREAD

**Issue by AlBundy33** [bndtools/bnd#5723]
To try bndtools I've cloned this repository: https://github.com/klibio/example.bnd.rcp

In this repo I had to make a change in /cnf/shared/macosx.cocoa.x86-64.bndrun
from
```
-runvm.macos:
	-XstartOnFirstThread,\
	-Dorg.eclipse.swt.internal.carbon.smallFonts
```
to
```
-runvm.macos:
	-XstartOnFirstThread, \
	-Dorg.eclipse.swt.internal.carbon.smallFonts
```

now if I try to run the demo-application from /example.rcp.app.ui/app.ui_macosx.cocoa.x86-64.bndrun I get an error that `-XstartOnFirstThread` is an invalid property key.
If I continue to launch the application I get the exception
```
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
Juli 18, 2023 5:16:50 NACHM. bndtools.runtime.applaunch.eclipse4.EclipseApplicationLauncher$1 run
SCHWERWIEGEND: Error executing application
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4875)
	at org.eclipse.swt.SWT.error(SWT.java:4790)
	at org.eclipse.swt.SWT.error(SWT.java:4761)
	at org.eclipse.swt.widgets.Display.error(Display.java:1103)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:851)
	at org.eclipse.swt.widgets.Display.create(Display.java:835)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:130)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:734)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:725)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1437)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.getApplicationDisplay(E4Application.java:135)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at bndtools.runtime.applaunch.eclipse4.EclipseApplicationLauncher$1.run(EclipseApplicationLauncher.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at aQute.launcher.Launcher.handleMainCallable(Launcher.java:465)
	at aQute.launcher.Launcher.launch(Launcher.java:438)
	at aQute.launcher.Launcher.run(Launcher.java:186)
	at aQute.launcher.Launcher.main(Launcher.java:162)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```
so it seems the vmarg is removed from the commandline.

Tested with https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-06/R/eclipse-rcp-2023-06-R-macosx-cocoa-x86_64.dmg
installed bndtools from markeplace
imported existing bnd project from the cloned repo mentioned above.

Is this an issue of bndtools or maybe the demo-project?

**Comment by pkriens** [comment]
you're missing the \ after the instruction.
```
-runvm.macos: \
	-XstartOnFirstThread, \
	-Dorg.eclipse.swt.internal.carbon.smallFonts
```

**Comment by AlBundy33** [comment]
Ohh da... - I could have seen that. 😄 
Thanks for the hint
