### ISSUE TITLE
Deprecation Warning with Gradle 8.1

### ISSUE THREAD

**Issue by Ao-senXiong** [bndtools/bnd#5747]
**Description**
When using the plugin with Gradle version 8.1, I've noticed a deprecation warning related to the use of conventions, which are scheduled to be removed in Gradle 9.0.

**Steps to Reproduce**
Upgrade to Gradle 8.1.
Apply the plugin to a project.
Run a Gradle build (./gradlew build).

**Expected Behavior**
The build should run without any deprecation warnings.

**Actual Behavior**
Received the following deprecation warning:

The AbstractTask.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
...

** Stack trace **
	at org.gradle.api.internal.AbstractTask.getConvention(AbstractTask.java:593)
	at aQute.bnd.gradle.BndBuilderPlugin.lambda$apply$0(BndBuilderPlugin.java:75)
	at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
	at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ExistingNamedDomainObjectProvider.configure(DefaultNamedDomainObjectCollection.java:853)
	at org.gradle.api.internal.tasks.DefaultTaskCollection$ExistingTaskProvider.configure(DefaultTaskCollection.java:200)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:391)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:127)
	at aQute.bnd.gradle.BndBuilderPlugin.apply(BndBuilderPlugin.java:71)
	at aQute.bnd.gradle.BndBuilderPlugin.apply(BndBuilderPlugin.java:41)

Upon inspecting the source code, the usage of conventions seems to be in BndBuilderPlugin.java:75-76:

extension.getBndfile().convention(defaultBndfile);

**Comment by pkriens** [comment]
Thanks! You seem to be deep in there, would it be possible to make a PR?

**Comment by bjhargrave** [comment]
The latest 7.0 snapshot plugins have already been fixed by https://github.com/bndtools/bnd/pull/5453 to no longer use Conventions.

> extension.getBndfile().convention(defaultBndfile);

This code is not using the deprecated Convention. It is using the properties API which supports the `convention` method. https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html#convention-T-
