### ISSUE TITLE
Error executing <project> Bndtools decoration in M2E integration

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#5752]
bndtools 6.4

I receive this exception, when I have imported a maven project into bndtools. The Maven project with bnd-maven si configured in the parent, but the affected module is no java project.

Java Model Exception: Error in Java Model (code 969): org.eclipse.osgitech.rest.archetype does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:574)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2503)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2443)
	at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2486)
	at org.bndtools.builder.decorator.ui.PackageDecorator.updateDecoration(PackageDecorator.java:81)
	at org.bndtools.builder.decorator.ui.ProjectDecoratorImpl.updateDecoration(ProjectDecoratorImpl.java:16)
	at bndtools.m2e.BndConfigurator$2.runInWorkspace(BndConfigurator.java:345)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by maho7791** [comment]
Provided https://github.com/bndtools/bnd/pull/5753
