### ISSUE TITLE
When I use jdk 8 to compile, it throw this execption. The bnd lib version is 5.3.0

### ISSUE THREAD

**Issue by simonjhy** [bndtools/bnd#5820]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at aQute.bnd.osgi.ZipResource.getBuffer(ZipResource.java:65)
	at aQute.bnd.osgi.ZipResource.buffer(ZipResource.java:54)
	at aQute.bnd.osgi.ZipResource.openInputStream(ZipResource.java:71)
	at aQute.bnd.osgi.Analyzer.parsePackageinfo(Analyzer.java:740)
	at aQute.bnd.osgi.Analyzer.learnPackage(Analyzer.java:693)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2647)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2573)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:213)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:442)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:1001)
	at aQute.bnd.osgi.Builder.build(Builder.java:126)
	at aQute.bnd.osgi.Builder$build$1.call(Unknown Source)
	at aQute.bnd.gradle.BundleTaskConvention$_buildBundle_closure3$_closure4.doCall(BundleTaskConvention.groovy:333)

**Comment by pkriens** [comment]
I think you somehow got a bndlib 7.0.0 on your class path ...

In java 1.8, flip was defined on Buffer, the super class of ByteBuffer. In 17, they moved it to ByteBuffer. The reference in bndlib 5.3.0 is:
```
  68  astore_1 [bb]
    69  aload_1 [bb]
    70  invokevirtual java.nio.ByteBuffer.flip() : java.nio.Buffer [39]
    73  pop
    74  aload_0 [this]
```
I.e. the reference is to Buffer.

**Comment by pkriens** [comment]
I am going to close this issue, feel free to reopen it when you have solid proof that it is 5.3.0 on your build path.
