### ISSUE TITLE
[bndtools] Suprious dependency warning at launch

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5824]
I'm not sure if this is two separate issues or two manifestations of the same issue.

I am working on the Bndtools workspace with Bndtools 7.1.0.DEV and Eclipse 2023-09.

I have an extra project in my workspace called `test`, which is not checked in. It currently has build errors.

I have another new project in the workspace `biz.aQute.bnd.pde` which has a `bnd.bnd` file with a fully resolved launch configuration in it. At the moment this is a simple project with a single `Runnable` component. This project does not depend on `test` either compile time or in the launch configuration.

If I launch `biz.aQute.bnd.pde`, it warns me of errors in "required projects" and lists the `test` project as the culprit.

If I close the `test` project, then the launcher fails with an exception:

```
Status ERROR: org.bndtools.launch code=0 Error initialising bnd launcher org.eclipse.core.internal.resources.ResourceException: Project 'test' is not open.
org.eclipse.core.internal.resources.ResourceException(/test)[372]: java.lang.Exception: Project 'test' is not open.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:186)
	at org.eclipse.core.internal.resources.Resource.findMarkers(Resource.java:1031)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.existsProblems(LaunchConfigurationDelegate.java:361)
	at bndtools.launch.AbstractOSGiLaunchDelegate.checkProjectErrors(AbstractOSGiLaunchDelegate.java:285)
	at bndtools.launch.AbstractOSGiLaunchDelegate.lambda$finalLaunchCheck$0(AbstractOSGiLaunchDelegate.java:194)
	at aQute.bnd.build.WorkspaceLock.locked(WorkspaceLock.java:168)
	at aQute.bnd.build.Workspace.readLocked(Workspace.java:1500)
	at bndtools.launch.AbstractOSGiLaunchDelegate.finalLaunchCheck(AbstractOSGiLaunchDelegate.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.bndtools.facade.ExtensionFacade.invoke(ExtensionFacade.java:171)
	at jdk.proxy16/jdk.proxy16.$Proxy66.finalLaunchCheck(Unknown Source)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:791)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I believe that this is a regression. It is possibly a manifestation of a couple of different issues - 1. the bnd launcher shouldn't throw an exception if it encounters a project that is not open, and 2. why is it even lookup up `test` when it is in no way related to the current launch.

**Comment by pkriens** [comment]
The related projects of a bndrun are all the projects in the workspace. See https://github.com/bndtools/bnd/blob/84e1bab7e8b2fcd6b09ef85a3ae2a7060eaf237c/org.bndtools.launch/src/bndtools/launch/AbstractOSGiLaunchDelegate.java#L307-L309

I agree we should fix the fact that the project is not closed but I am not clear on the action? For bnd, the project still exists in the workspace, we cannot close projects. So the fact that you close it in Eclipse is an odd state.

In this case we could ignore the search for markers I guess?

**Comment by pkriens** [comment]
I've added a check if the project is open in #5840

**Comment by kriegfrj** [comment]
> The related projects of a bndrun are all the projects in the workspace. See
> 
> https://github.com/bndtools/bnd/blob/84e1bab7e8b2fcd6b09ef85a3ae2a7060eaf237c/org.bndtools.launch/src/bndtools/launch/AbstractOSGiLaunchDelegate.java#L307-L309
>

I feel that this definition of "related" is too loose. From a `.bndrun` launch's perspective, I believe that the "related projects" should be those that are in `-runbundles`. When I'm launching I don't really care if there are errors in another project that's not part of my launch. Does this seem fair? This would be a different case to the open project - if you agree I can create a new issue and maybe a PR for it (leave this issue/PR to handle the closed project issue).

**Comment by gireeshpunathil** [comment]
sorry if this is a naive question. As per the docs, a workspace (not project) is managed by `bnd` under the cover, and all the projects that are created in that workspace come under the purview of `automatic management`, and thereby subject of error checks? or is there an additional qualification that I am not aware of, whereby projects are grouped `manually` to be managed?

**Comment by kriegfrj** [comment]
@gireeshpunathil , thanks for your question!

You are correct - every project in the workspace is supposed to be managed by bnd, and bnd will generate error markers for them. However, this particular issue deals with launching applications (defined by .bndrun files). Currently, the launcher will warn you if any projects have errors. However, I am arguing that we should only warn if the project that are relevant to the current `.bndrun` file have errors.
