### ISSUE TITLE
org.eclipse.swt.SWTException: Invalid thread access

### ISSUE THREAD

**Issue by simonjhy** [bndtools/bnd#5901]
I got this error on mac os with eclipse 202309 + BNDTools 7.0.0

!ENTRY org.eclipse.core.jobs 4 2 2023-11-23 19:35:27.018
!MESSAGE An internal error occurred during: "Updating repositories content".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1209)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:960)
	at org.eclipse.swt.widgets.Display.create(Display.java:944)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:132)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:798)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:789)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1543)
	at bndtools.central.RepositoriesViewRefresher.getDisplay(RepositoriesViewRefresher.java:203)
	at bndtools.central.RepositoriesViewRefresher$1.runInWorkspace(RepositoriesViewRefresher.java:106)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by pkriens** [comment]
This should be fixed by # #5910
