### ISSUE TITLE
Got an issue when use bnd 7.1.0 Dev and it cause m2e can not update project

### ISSUE THREAD

**Issue by simonjhy** [bndtools/bnd#5933]
```
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6c43fe6b wants to load class org.apache.maven.project.MavenProject. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @7eeda24e. (org.apache.maven.project.MavenProject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7eeda24e, parent loader 'platform')
	at bndtools.m2e.MavenBndrunContainer.getBndrunContainer(MavenBndrunContainer.java:99)
	at bndtools.m2e.MavenDependenciesRepository.collect(MavenDependenciesRepository.java:61)
	at bndtools.m2e.MavenWorkspaceRepository.process(MavenWorkspaceRepository.java:379)
	at bndtools.m2e.MavenWorkspaceRepository.mavenProjectChanged(MavenWorkspaceRepository.java:262)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:888)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:1040)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:320)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:387)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1097)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



Bndtools	7.1.0.DEV-202312011634-geca3fb7
Eclipse            4.30
M2e                2.4.30

**Comment by pkriens** [comment]
@tjwatson do you see anything you immediately recognize?

**Comment by pkriens** [comment]
Ok, to get further info, could you get me a list of all the installed features in Eclipse and their version?

**Comment by pkriens** [comment]
And please also add the same for the installed bundles

**Comment by simonjhy** [comment]
![Screenshot from 2023-12-27 12-16-06](https://github.com/bndtools/bnd/assets/5745444/48859ecc-d26c-4c9f-9871-9beddfcf3f4a)
![Screenshot from 2023-12-27 12-16-17](https://github.com/bndtools/bnd/assets/5745444/bf7b2d04-b0f1-4889-9b3d-5b20dff7bb4c)
![Screenshot from 2023-12-27 12-16-29](https://github.com/bndtools/bnd/assets/5745444/a3d4b7d0-2c84-4018-ab0e-6c327ee9cbd0)

**Comment by pkriens** [comment]
I also need the actually installed bundles ...  (or plugins in Eclipse parlay). Sorry for the delay, was on vacation

**Comment by pkriens** [comment]
Closing for no activity
