### ISSUE TITLE
Argument not valid in Outline view of bnd editor (Image disposed too early)

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#6322]
I am not a 100% how I managed to get this exception, but currently I get it a lot. 
I am doing lots of stuff with tweaking optional Import-Packages.
Looks like the icons / images in the outline are somehow related to the Import-Packages.

I will dig into but maybe try to just catch the error.

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/a2f3658d-dd48-4729-9f43-3e9770735119">

```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:853)
	at org.eclipse.swt.widgets.TreeItem.setImage(TreeItem.java:1357)
	at org.eclipse.jface.viewers.TreeViewerRow.setImage(TreeViewerRow.java:110)
	at org.eclipse.jface.viewers.ViewerCell.setImage(ViewerCell.java:171)
	at bndtools.editor.BndEditorContentOutlineLabelProvider.update(BndEditorContentOutlineLabelProvider.java:45)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:149)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1000)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:158)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1073)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:426)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2111)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:3007)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:2031)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:2004)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1961)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1947)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$2(StructuredViewer.java:1463)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1392)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:367)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1353)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1463)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:521)
	at bndtools.editor.BndEditorContentOutlineProvider.propertyChange(BndEditorContentOutlineProvider.java:147)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at aQute.bnd.build.model.BndEditModel.loadFrom(BndEditModel.java:449)
	at aQute.bnd.build.model.BndEditModel.loadFrom(BndEditModel.java:408)
	at bndtools.editor.BndEditor.lambda$loadEditModel$2(BndEditor.java:635)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)

```

**Comment by pkriens** [comment]
Weird. Looks like an invalid image.

**Comment by chrisrueger** [comment]
Strange, now I cannot reproduce it. 

The code seems to be this. 
Image disposed? What could cause  this?

<img width="824" alt="image" src="https://github.com/user-attachments/assets/e4f1564d-a21a-4816-8de2-a35b06ecee86">

Here I only have my laptop. 
In the office where I had the error I have a large monitor. 
I found this https://bugs.eclipse.org/bugs/show_bug.cgi?id=575707 "IllegalArgumentException when resolving overlay image on HighRes screen" which sounds like it could be resolution dependend. I will try to reproduce it and hopefully be able to debug.

**Comment by kriegfrj** [comment]
> Strange, now I cannot reproduce it.
> 
> The code seems to be this. Image disposed? What could cause this?
> 

Does this happen when you are working on the Eclipse/Bndtools dev instance, launched from the bnd workspace? Or does it happen when you're working on a standalone Eclipse instance?

It's been a while, but I remember that @pkriens put some centralised image resource management into one of our bundles. If that bundle is restarted (which can happen eg if you change some of the code and you've got automatic building turned on), it can cause the image handle to be disposed, and because lots of the Eclipse UI implementation does not handle dynamics well it can still hang on to the stale handles.

**Comment by chrisrueger** [comment]
> Does this happen when you are working on the Eclipse/Bndtools dev instance, launched from the bnd workspace? Or does it happen when you're working on a standalone Eclipse instance?

No, that happens when I am working with a normal Eclipse (2024-09) with a recent bndtools 7.1.0 SNAPSHOT installed. It basically happened during normal daily work (not bndtools development). 
I will keep an eye on it.

**Comment by pkriens** [comment]
It tends to happen when bundles get updated. In Icons i tried to handle this but not all code uses Icons.

**Comment by chrisrueger** [comment]
I will close it for now and reopen when it happens again.

**Comment by chrisrueger** [comment]
I get this error more and more now.
I found this article :

https://www.eclipse.org/articles/Article-Using%20Images%20In%20Eclipse/Using%20Images%20In%20Eclipse.html

There are two interesting sentences in the beginnen about disposing of shared images. I believe the issue we see in bndtools is realated. We are disposing shared Images which are used by multiple widgets.

> An interesting characteristic of Images is that one Image instance can be placed in multiple widgets, a technique called image sharing.  A major challenge of image management is to take advantage of this sharing as much as possible, but to still know when it is safe to dispose the image.

> As a general rule of thumb, ImageDescriptors should be used wherever possible in your UI code.  However, in places where you are creating real widgets, such as subclasses of org.eclipse.swt.widgets.Widget, or org.eclipse.jface.window.Window, you need to be manipulating SWT images.  Generally, the code that creates the widget should also create the Images to go in it, and the code that disposes the widget should also dispose of its images.  An exception to this rule is if you are using Images that are shared between multiple widgets.  Image sharing should be approached with caution, because as we discussed earlier, sharing makes it difficult to figure out when to dispose of the images.  org.eclipse.jface.viewers.ILabelProvider (described later), and org.eclipse.jface.resource.ImageRegistry, are two mechanisms provided by JFace that help to achieve image sharing in a controlled manner.

**Comment by chrisrueger** [comment]
I think I found a way to reproduce it and a potential root cause:

- Open Repositories View Advanced Search
- Do one search e.g. search for a package `*apache*`

<img width="262" alt="Image" src="https://github.com/user-attachments/assets/22cb5ccd-2d56-4e6c-b24b-23da456c0414" />

During this search when closing the AdvancedSearch panel, the images are disposed, which contains an image reference to the shared `Icons.image("package")`:

<img width="1414" alt="Image" src="https://github.com/user-attachments/assets/c0cbde2c-adbe-4629-9d09-ee4e717241d5" />

Now make sure you have the Outline View open in Eclipse and open a .bnd file which contains Import-Packages or something with "package" references.

<img width="1013" alt="Image" src="https://github.com/user-attachments/assets/8bb30ced-a6d9-4e8f-ad37-310b269afd2b" />

Boom. Error. 
It is because the Outline View also tries to display a package-icon, which was disposed above. 

<img width="1638" alt="Image" src="https://github.com/user-attachments/assets/0190eedd-a213-4d9e-918d-794f0ab2efe3" />


I think the reason is that the icons like `bndtools.editor.BndEditorContentOutlineLabelProvider.packageImg` are static variables, they are not refreshed after they got disposed elsewhere.

<img width="867" alt="Image" src="https://github.com/user-attachments/assets/2bd10f97-0741-4057-ad94-c44ad6958587" />


I will try to come up with a fix. Maybe Image variables should not be static variables. 
Instead we might always get them directly via `Icons.image()` as mentioned by @pkriens , since `Icons.image()` already does caching too.

**Comment by kriegfrj** [comment]
A longer term solution idea - what if the icon instances were singleton DS components or OSGi services? That way the SCR will automatically take care of instantiating, teaching references, and disposing of them when there are no more references held.

**Comment by chrisrueger** [comment]
> A longer term solution idea - what if the icon instances were singleton DS components or OSGi services? That way the SCR will automatically take care of instantiating, teaching references, and disposing of them when there are no more references held.

The problem here was that a (managed/shared/cached) Image instance passed out by Icons.image() was .dipose()d by the consumer.  

So to prevent this, i think no consumer code should ever call image.dispose if the instance was coming from Icons. 

How would your suggestion address this?

**Comment by kriegfrj** [comment]
I guess it wouldn't address it directly.

**Comment by chrisrueger** [comment]
> I guess it wouldn't address it directly.

I thought about subclassing or proxying the Image class to overwrite the dispose method so we could prevent other code from calling it and maybe we could add our own dispose method which only "Icons" knows about and call it. 

unfortunatelly `Image` class is final, so this is not possible (at least I don't know).
