### ISSUE TITLE
Can't launch any bndrun file

### ISSUE THREAD

**Issue by gravelld** [bndtools/bnd#672]
I can't run any bndrun file. This is bndtools v2.3.0:

When I run a bndrun file as an "OSGi Framework" run configuration I get:

```
An internal error occurred during: "Launching bliss.bndrun".
aQute.lib.utf8properties.UTF8Properties not found, parent:  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader@64a6a3fd[biz.aQute.bndlib:2.3.0.201405100607(id=3)] urls:[file:/home/gravelld/.bnd/cache/https%253A%252F%252Fgithub.com%252Fbndtools%252Fbundle-hub%252Fraw%252Fmaster%252Fbiz.aQute.launcher/biz.aQute.launcher-1.4.0.jar] exception:java.lang.ClassNotFoundException: aQute.lib.utf8properties.UTF8Properties
```
In the error log there's:
```
java.lang.NoClassDefFoundError: aQute.lib.utf8properties.UTF8Properties not found, parent:  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader@64a6a3fd[biz.aQute.bndlib:2.3.0.201405100607(id=3)] urls:[file:/home/gravelld/.bnd/cache/https%253A%252F%252Fgithub.com%252Fbndtools%252Fbundle-hub%252Fraw%252Fmaster%252Fbiz.aQute.launcher/biz.aQute.launcher-1.4.0.jar] exception:java.lang.ClassNotFoundException: aQute.lib.utf8properties.UTF8Properties
	at aQute.bnd.osgi.Processor$CL.loadClass(Processor.java:1546)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
	at java.lang.Class.getConstructor0(Class.java:2803)
	at java.lang.Class.getConstructor(Class.java:1718)
	at aQute.bnd.build.Project.getHandler(Project.java:2118)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2087)
	at bndtools.launch.OSGiRunLaunchDelegate.initialiseBndLauncher(OSGiRunLaunchDelegate.java:47)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:50)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:823)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:704)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1047)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1251)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```
As I said this occurs with all bndrun files but here's the main one I'm trying to run anyway, just in case something really wacky is going on:
```
-runfw: org.apache.felix.framework;version='[4.4.0,4.4.0]'
-runee: JavaSE-1.6
-runrequires:  \
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.ui)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.web.debug)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.updater)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.logging)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.osgi.system)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.bundle)',\
	osgi.identity;filter:='(&(osgi.identity=org.apache.felix.scr)(version>=1.6.0))',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.ui.systemtray)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.untagged.onemusicapi)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.osgi.system.osx)',\
	osgi.identity;filter:='(osgi.identity=net.contentobjects.jnotify.linux.amd64)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.configuration.file)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.policy.tag.auto.linux.amd64)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.policy.tag.auto.linux.x86)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.policy.tag.auto.osx)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.policy.tag.auto.win.x86)',\
	osgi.identity;filter:='(osgi.identity=net.contentobjects.jnotify.linux.x86)',\
	osgi.identity;filter:='(osgi.identity=net.contentobjects.jnotify.osx)',\
	osgi.identity;filter:='(osgi.identity=net.contentobjects.jnotify.win.amd64)',\
	osgi.identity;filter:='(osgi.identity=net.contentobjects.jnotify.win.x86)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.analytics)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.licence)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.music.info.onemusicapi)',\
	osgi.identity;filter:='(osgi.identity=com.onemusicapi.client)',\
	osgi.identity;filter:='(osgi.identity=com.onemusicapi.common)',\
	osgi.identity;filter:='(osgi.identity=com.elsten.bliss.api)',\
	osgi.identity;filter:='(&(osgi.identity=slf4j.log4j12)(version>=1.6.4))'
-runbundles:  \
	JGoogleAnalytics_0.3;version='[0.0.0,0.0.1)',\
	com.elsten.bliss.analytics;version=latest,\
	com.elsten.bliss.api;version=latest,\
	com.elsten.bliss.bundle;version=latest,\
	com.elsten.bliss.charge.api;version=latest,\
	com.elsten.bliss.configuration.file;version=latest,\
	com.elsten.bliss.licence;version=latest,\
	com.elsten.bliss.logging;version=latest,\
	com.elsten.bliss.model;version=latest,\
	com.elsten.bliss.model.api;version=latest,\
	com.elsten.bliss.music.info.api;version=latest,\
	com.elsten.bliss.music.info.common;version=latest,\
	com.elsten.bliss.music.info.dto;version=latest,\
	com.elsten.bliss.music.info.onemusicapi;version=latest,\
	com.elsten.bliss.music.info.tagsource.api;version=latest,\
	com.elsten.bliss.music.info.tagsource.impl;version=latest,\
	com.elsten.bliss.osgi.system;version=latest,\
	com.elsten.bliss.osgi.system.osx;version=latest,\
	com.elsten.bliss.platform;version=latest,\
	com.elsten.bliss.policy.coverart.lookup.api;version=latest,\
	com.elsten.bliss.policy.coverart.lookup.common;version=latest,\
	com.elsten.bliss.policy.parsed;version=latest,\
	com.elsten.bliss.policy.tag.auto;version=latest,\
	com.elsten.bliss.policy.tag.auto.linux.amd64;version=latest,\
	com.elsten.bliss.policy.tag.auto.linux.x86;version=latest,\
	com.elsten.bliss.policy.tag.auto.osx;version=latest,\
	com.elsten.bliss.policy.tag.auto.win.x86;version=latest,\
	com.elsten.bliss.policy.tag.tagtype;version=latest,\
	com.elsten.bliss.ui;version=latest,\
	com.elsten.bliss.ui.systemtray;version=latest,\
	com.elsten.bliss.untagged.onemusicapi;version=latest,\
	com.elsten.bliss.updater;version=latest,\
	com.elsten.bliss.web.debug;version=latest,\
	com.elsten.musicbrainz;version=latest,\
	com.elsten.util;version=latest,\
	com.google.gson;version='[1.6.0,1.6.1)',\
	com.google.guava;version='[12.0.1,12.0.2)',\
	com.google.guava;version='[18.0.0,18.0.1)',\
	com.onemusicapi.client;version=latest,\
	com.onemusicapi.common;version=latest,\
	com.springsource.javax.media.jai.codec;version='[1.1.3,1.1.4)',\
	com.springsource.javax.media.jai.core;version='[1.1.3,1.1.4)',\
	com.stripe;version='[1.0.0,1.0.1)',\
	com.sun.jna;version='[3.2.1,3.2.2)',\
	javax.servlet;version='[2.5.0,2.5.1)',\
	jdbm-trunk-patched;version='[0.0.0,0.0.1)',\
	log4j;version='[1.2.17,1.2.18)',\
	net.contentobjects.jnotify;version=latest,\
	net.contentobjects.jnotify.linux.amd64;version='latest',\
	net.contentobjects.jnotify.linux.x86;version=latest,\
	net.contentobjects.jnotify.osx;version=latest,\
	net.contentobjects.jnotify.win.amd64;version=latest,\
	net.contentobjects.jnotify.win.x86;version=latest,\
	org.apache.commons.codec;version='[1.4.0,1.4.1)',\
	org.apache.commons.collections;version='[3.2.1,3.2.2)',\
	org.apache.commons.httpclient;version='[3.1.0,3.1.1)',\
	org.apache.commons.io;version='[1.4.0,1.4.1)',\
	org.apache.commons.lang;version='[2.6.0,2.6.1)',\
	org.apache.commons.logging;version='[1.0.4,1.0.5)',\
	org.apache.felix.bundlerepository;version='[1.6.7,1.6.8)',\
	org.apache.felix.configadmin;version='[1.8.0,1.8.1)',\
	org.apache.felix.http.jetty;version='[2.2.2,2.2.3)',\
	org.apache.felix.scr;version='[1.8.2,1.8.3)',\
	org.eclipse.jetty.continuation;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.deploy;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.http;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.io;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.osgi.boot;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.security;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.server;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.servlet;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.util;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.webapp;version='[7.6.1,7.6.2)',\
	org.eclipse.jetty.xml;version='[7.6.1,7.6.2)',\
	org.jaudiotagger;version='[2.0.4,2.0.5)',\
	osgi.enterprise;version='[4.2.0,4.2.1)',\
	scala-library;version='[2.9.1,2.9.2)',\
	slf4j.api;version='[1.6.4,1.6.5)',\
	slf4j.log4j12;version='[1.6.4,1.6.5)'
-runrepos: Local,\
	Bndtools Hub,\
	Workspace
-runproperties: ds.loglevel=3
-runvm: -Xmx256M -XX:+CMSClassUnloadingEnabled -XX:HeapDumpPath=/tmp -XX:+HeapDumpOnOutOfMemoryError
```
Original mailing list discussion: https://groups.google.com/forum/#!topic/bndtools-users/SyUZfuiUx8Q

**Comment by pkriens** [comment]
This should be ok in 3.0.0
