### ISSUE TITLE
 Java heap space

### ISSUE THREAD

**Issue by minikiller** [bndtools/bnd#724]
I use maven-bundle-plugin 2.5.3 to build my bundle under OSGI environment. When I add a 60k js script file to my project,it show errors to build  as following:

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at java.lang.StringBuilder.append(StringBuilder.java:179)
	at java.lang.StringBuilder.append(StringBuilder.java:72)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2724)
	at java.util.Formatter.format(Formatter.java:2476)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2797)
	at aQute.bnd.osgi.Processor.report(Processor.java:1678)
	at aQute.bnd.osgi.Processor.toString(Processor.java:2114)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2838)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2718)
	at java.util.Formatter.format(Formatter.java:2488)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2797)
	at aQute.bnd.osgi.Processor.formatArrays(Processor.java:1784)
	at aQute.bnd.osgi.Processor.warning(Processor.java:169)
	at aQute.bnd.osgi.Macro.replace(Macro.java:217)
	at aQute.bnd.osgi.Macro.process(Macro.java:62)
	at aQute.bnd.osgi.Macro.process(Macro.java:78)
	at aQute.bnd.osgi.Macro.process(Macro.java:48)
	at aQute.bnd.osgi.Macro.process(Macro.java:43)
	at aQute.bnd.osgi.Macro.process(Macro.java:1139)
	at aQute.bnd.osgi.PreprocessResource.getBytes(PreprocessResource.java:28)
	at aQute.bnd.osgi.AbstractResource.getLocalBytes(AbstractResource.java:31)
	at aQute.bnd.osgi.AbstractResource.write(AbstractResource.java:48)
	at aQute.bnd.osgi.Jar.writeResource(Jar.java:558)
	at aQute.bnd.osgi.Jar.write(Jar.java:318)
	at aQute.bnd.osgi.Jar.write(Jar.java:238)

**Comment by gamerson** [comment]
I ran into the same thing here: https://github.com/bndtools/bndtools/pull/982

When processing resources if the Macro processor starts running over obviously invalid files (in my case I linked to it was parsing through an eclipse_dir/configuration directory) then it fills up all available heapspace with error messages.  All of those error messages are valid, its just if the project is configured in a certain way it can exhaust memory.

**Comment by pkriens** [comment]
Should limit the # of errors when processing. Should limit the # of errors & warnings to about a 100

**Comment by akuhtz** [comment]
Hi,
I ran into the same issue and I think the issue is in 
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java#L228
where the domain is provided as parameter in the call to domain.warning().

Replace the ling with `domain.warning("No translation found for macro: %s", key);` solved the overflow, but I don't know if useful information is discarded.
