### ISSUE TITLE
org.osgi.service.indexer.impl.types.VersionRange fails on "[1,)"

### ISSUE THREAD

**Issue by pdwinkel** [bndtools/bnd#760]
```
[ERROR  ] 2015-01-02 14:15:15: Error calling analyzer "org.osgi.service.indexer.impl.BundleAnalyzer" on resource /home/peter/develop/bundles/netty-common-4.0.25.Final.jar.
java.lang.NumberFormatException: For input string: "[1,)"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.osgi.framework.Version.<init>(Version.java:127)
	at org.osgi.service.indexer.impl.types.VersionRange.<init>(VersionRange.java:59)
	at org.osgi.service.indexer.impl.BundleAnalyzer.doImports(BundleAnalyzer.java:299)
	at org.osgi.service.indexer.impl.BundleAnalyzer.analyzeResource(BundleAnalyzer.java:64)
	at org.osgi.service.indexer.impl.RepoIndex.generateResource(RepoIndex.java:266)
	at org.osgi.service.indexer.impl.RepoIndex.index(RepoIndex.java:185)
	at org.osgi.impl.bundle.bindex.cli.Index.main(Index.java:81)
```

**Comment by bjhargrave** [comment]
"[1,)" is not a valid version range so I would expect an exception.

**Comment by pdwinkel** [comment]
OK, so "[1,)" does not mean "[1,infinity)" ?

**Comment by bjhargrave** [comment]
No. "1" means 1 to infinity (no [] or () ).

**Comment by pdwinkel** [comment]
OK, Thx
