### ISSUE TITLE
[analyzer] suppress spurious version parsing errors

### ISSUE THREAD

**Issue by acourtis** [bndtools/bnd#915]
Oracle JDK 1.8.0_40, bndlib 2.4.1

Users are being flooded with version parsing exceptions which are not actually a problem. Those exceptions should be ignored at that point as the versions will be fuzzy matched later.

```
java.lang.IllegalArgumentException: Invalid syntax for version: 0.27.4-SNAPSHOT
	at aQute.bnd.version.Version.<init>(Version.java:46)
	at aQute.bnd.osgi.Analyzer.augmentExports(Analyzer.java:1711)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:229)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:344)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:618)
	at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:213)
	at org.apache.felix.bundleplugin.ManifestPlugin.getManifest(ManifestPlugin.java:114)
	at org.apache.felix.bundleplugin.ManifestPlugin.execute(ManifestPlugin.java:69)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:294)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:285)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojoImpl(MojoExecutor.java:172)
	at org.twdata.maven.mojoexecutor.MojoExecutor$ExecutionEnvironmentM3.executeMojo(MojoExecutor.java:476)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:75)
	at com.atlassian.maven.plugins.amps.MavenGoals.generateBundleManifest(MavenGoals.java:1405)
	at com.atlassian.maven.plugins.amps.osgi.GenerateManifestMojo.execute(GenerateManifestMojo.java:71)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by bjhargrave** [comment]
Isn't this an issue with the maven-bnd-plugin at Apache since it is exposing bnd to invalid OSGi versions?

**Comment by acourtis** [comment]
I'm going to say no to the maven-bnd-plugin - bndlib has always handled the version coercing and still does.

Maven versions such as `0.27.4-SNAPSHOT` has always been an acceptable input, as the Analyzer uses the fuzzy logic in `cleanupVersion` to convert to a proper OSGi version. It's still producing the same valid bundles with the same input.

It's just the exception printing that should be removed here - it was added in #2a15539 for some completely unrelated functionality and doesn't change the execution at all.

**Comment by acourtis** [comment]
Option 1 - use fuzzy version matching when comparing manifest to package versions - https://github.com/bndtools/bnd/pull/916
Option 2 - don't print these invalid version messages - https://github.com/bndtools/bnd/pull/914

I prefer Option 2 :)

**Comment by acourtis** [comment]
https://github.com/bndtools/bnd/pull/916 merged
